"use client";
import {useEffect,useMemo,useState} from "react";

type Entry={id:string;date:string;student:"Jerome"|"Kameron";attendance:string;mode:string;subject:string;hours:number;activity:string;instructor:string};
const modes=["Home","Co-op","Field Trip","Online","Instructor-Led","Travel Learning"];
const subjects=["Reading / ELA","Math","Science","Social Studies","Art","Music / Piano","PE / Karate","Spanish","Coding / Robotics","Health / Life Skills","Therapy / Services","Career / Practical Skills"];
const quick=[
 ["Kameron home block",3,"Home","Reading / ELA"],["Jerome learning block",3,"Home","Reading / ELA"],["Piano lesson",0.5,"Instructor-Led","Music / Piano"],["Karate",1,"Instructor-Led","PE / Karate"],["Spanish",1,"Online","Spanish"],["Coding",1.5,"Online","Coding / Robotics"],["Tutoring",1,"Instructor-Led","Reading / ELA"],["Co-op",3,"Co-op","Science"],["Therapy / service",0.5,"Instructor-Led","Therapy / Services"],["Field trip",3,"Field Trip","Social Studies"]
] as const;
const today=()=>new Date().toISOString().slice(0,10);
const quarter=(date:string)=>{const m=new Date(`${date}T12:00:00`).getMonth()+1;return m>=7&&m<=9?"Q1":m>=10&&m<=12?"Q2":m<=3?"Q3":"Q4"};

export function AttendanceCenter(){
 const[entries,setEntries]=useState<Entry[]>([]),[student,setStudent]=useState<"Jerome"|"Kameron">("Kameron"),[date,setDate]=useState(today()),[attendance,setAttendance]=useState("Present"),[mode,setMode]=useState("Home"),[subject,setSubject]=useState("Reading / ELA"),[hours,setHours]=useState(1),[activity,setActivity]=useState(""),[instructor,setInstructor]=useState("Jestina"),[filterStudent,setFilterStudent]=useState("All"),[filterQuarter,setFilterQuarter]=useState("All"),[message,setMessage]=useState("");
 useEffect(()=>{try{setEntries(JSON.parse(localStorage.getItem("weems-attendance-hours")||"[]"))}catch{}},[]);
 const save=(next:Entry[])=>{setEntries(next);localStorage.setItem("weems-attendance-hours",JSON.stringify(next))};
 const add=(preset?:typeof quick[number])=>{const title=preset?.[0]||activity.trim();const hrs=Number(preset?.[1]??hours);if(!date||!hrs||hrs<0||!title){setMessage("Add an activity and instructional hours first.");return}const next:Entry={id:crypto.randomUUID(),date,student,attendance,mode:preset?.[2]||mode,subject:preset?.[3]||subject,hours:hrs,activity:title,instructor};save([next,...entries]);setActivity("");setMessage("Instructional record saved on this device.");setTimeout(()=>setMessage(""),2200)};
 const shown=entries.filter(e=>(filterStudent==="All"||e.student===filterStudent)&&(filterQuarter==="All"||quarter(e.date)===filterQuarter));
 const total=(name:string)=>entries.filter(e=>e.student===name).reduce((n,e)=>n+e.hours,0);
 const days=(name:string)=>new Set(entries.filter(e=>e.student===name&&["Present","Partial Day"].includes(e.attendance)).map(e=>e.date)).size;
 const subjectTotals=useMemo(()=>subjects.map(s=>[s,shown.filter(e=>e.subject===s).reduce((n,e)=>n+e.hours,0)] as const).filter(x=>x[1]>0),[shown]);
 const exportCsv=()=>{const rows=[["Date","Quarter","Student","Attendance","Mode","Subject","Hours","Activity","Instructor"],...shown.map(e=>[e.date,quarter(e.date),e.student,e.attendance,e.mode,e.subject,String(e.hours),e.activity,e.instructor])];const csv=rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="weems-attendance-hours.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div className="page attendancePage"><div className="pagehead"><div><small>DAILY LOG • QUARTERLY REPORTS • YEAR TOTALS</small><h2>Attendance & Instructional Hours</h2><p>Record where learning happened, what was taught, who led it, and how much instructional time it included.</p></div><div className="attendanceActions"><button onClick={exportCsv}>Export CSV</button><button className="primary" onClick={()=>window.print()}>Print records</button></div></div>
 <div className="attendanceNotice"><b>Flexible learning counts when it is instruction.</b><span>Document home lessons, online courses, co-op, field trips, travel study, arts, physical education, practical skills and supervised services with a clear learning purpose.</span></div>
 <div className="attendanceStats">{(["Kameron","Jerome"] as const).map(name=>{const goal=name==="Kameron"?900:990,t=total(name);return <article key={name}><header><b>{name}</b><span>{name==="Kameron"?"Grade 3 • 900-hour goal":"Grade 10 • 990-hour goal"}</span></header><strong>{t.toFixed(1)} <small>hours</small></strong><p>{days(name)} attendance days recorded</p><em><i style={{width:`${Math.min(100,t/goal*100)}%`}}/></em><small>{Math.round(t/goal*100)}% of annual hour goal</small></article>})}</div>
 <section className="attendanceEntry"><div><small>ADD TODAY’S LEARNING</small><h3>One record per student, subject or activity</h3><p>Split a mixed day into several entries for cleaner quarterly subject totals.</p></div><div className="entryGrid"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Student<select value={student} onChange={e=>setStudent(e.target.value as "Jerome"|"Kameron")}><option>Kameron</option><option>Jerome</option></select></label><label>Attendance<select value={attendance} onChange={e=>setAttendance(e.target.value)}><option>Present</option><option>Partial Day</option><option>Excused Absence</option><option>Unexcused Absence</option></select></label><label>Learning setting<select value={mode} onChange={e=>setMode(e.target.value)}>{modes.map(x=><option key={x}>{x}</option>)}</select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label>Hours<input type="number" min="0.25" max="12" step="0.25" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label>Instructor<input value={instructor} onChange={e=>setInstructor(e.target.value)}/></label><label className="activityField">Activity / learning evidence<input value={activity} onChange={e=>setActivity(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Read chapter, math lesson, museum notes, karate practice…"/></label></div><button className="addAttendance" onClick={()=>add()}>＋ Save instructional record</button>{message&&<p className="attendanceMessage">{message}</p>}</section>
 <section className="quickHours"><div><small>QUICK ADD</small><h3>Common learning blocks</h3><p>Select the student and date above, then tap a block. Hours can be edited by removing and re-entering the record.</p></div><div>{quick.map(x=><button key={x[0]} onClick={()=>add(x)}><b>{x[0]}</b><span>{x[1]} hr{x[1]===1?"":"s"} • {x[3]}</span></button>)}</div></section>
 <div className="attendanceFilters"><b>Record book</b><select value={filterStudent} onChange={e=>setFilterStudent(e.target.value)}><option>All</option><option>Kameron</option><option>Jerome</option></select><select value={filterQuarter} onChange={e=>setFilterQuarter(e.target.value)}><option>All</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option></select><span>{shown.reduce((n,e)=>n+e.hours,0).toFixed(1)} displayed hours</span></div>
 <div className="attendanceTable"><div className="attendanceHead"><b>Date</b><b>Student / status</b><b>Instruction</b><b>Hours</b><b></b></div>{shown.length?shown.map(e=><article key={e.id}><time>{new Date(`${e.date}T12:00:00`).toLocaleDateString()}<small>{quarter(e.date)}</small></time><p><b>{e.student}</b><span>{e.attendance} • {e.mode}</span></p><p><b>{e.subject}</b><span>{e.activity} • {e.instructor}</span></p><strong>{e.hours.toFixed(2)}</strong><button onClick={()=>save(entries.filter(x=>x.id!==e.id))}>Remove</button></article>):<p className="emptyAttendance">No records match this view yet.</p>}</div>
 <div className="attendanceBottom"><section><small>SUBJECT-HOUR SUMMARY</small><h3>{filterStudent} • {filterQuarter}</h3>{subjectTotals.length?subjectTotals.map(([s,h])=><p key={s}><span>{s}</span><b>{h.toFixed(1)} hrs</b></p>):<p>No subject hours recorded in this view.</p>}</section><section className="complianceCard"><small>NEW YORK RECORDKEEPING CHECK</small><h3>Keep the official record complete</h3><ul><li><b>Annual instruction:</b> 900 hours for grades 1–6 and 990 hours for grades 7–12.</li><li><b>Quarterly reports:</b> include the number of instructional hours completed; subject hours are recommended for secondary students.</li><li><b>Attendance:</b> maintain records and make them available to the school district upon request.</li><li><b>Required subjects:</b> remember physical education and the grade-level subjects listed in the IHIP.</li></ul><p>This dashboard is a planning and recordkeeping aid. Follow your district’s requested forms and current NYSED guidance.</p><div><a href="https://www.nysed.gov/nonpublic-schools/home-instruction-questions-and-answers" target="_blank" rel="noreferrer">NYSED Home Instruction Q&amp;A ↗</a><a href="https://www.nysed.gov/nonpublic-schools/home-instruction" target="_blank" rel="noreferrer">NYSED Home Instruction ↗</a></div></section></div>
 </div>
}
