import "./drive.css";
const folders=[
 ["90-Day Curriculum","All 18 themed weeks, lesson materials and future Classroom-ready assignments.","https://drive.google.com/drive/folders/1pUE5YIsx1tpnRJNv2TPhehHysXn4_djx","18W"],
 ["Kameron — Grade 3","Reading, math, projects, accommodations and Grade 3 work samples.","https://drive.google.com/drive/folders/1LeW2a7xajQtBVMgo-RzgPrsRE1_inYgw","K3"],
 ["Jerome — Grade 10","English, math, coding, careers, financial literacy and Grade 10 evidence.","https://drive.google.com/drive/folders/1cGqRl1SeoFwmb5sjM6rcWJZOq2YL3uF9","J10"],
 ["Instructor Resources","Lesson links, answer guidance, accommodations and instructor handoffs.","https://drive.google.com/drive/folders/1dmIbhtBkVI6M-DAaPIL3NDG0SmSQMMN3","TEAM"],
 ["Reports & Portfolio","Quarterly reports, approved work samples, attendance and export backups.","https://drive.google.com/drive/folders/195JHwABo7Vnhtec7eNJo0KtAwLtNLzB0","DOC"]
];
export default function DriveResources(){return <main className="drivePage"><header><a href="/">← School Command Center</a><span>WEEMS-ROSENDUFT ACADEMY</span></header><section className="driveHero"><div><small>GOOGLE DRIVE RESOURCE CENTER</small><h1>One organized home for the school year.</h1><p>These folders are ready to hold lessons, assignments, student work and reports. They are organized so the same structure can later support Google Classroom.</p><a href="https://drive.google.com/drive/folders/1D2d2XpS82gKgixDVHNbDbeoB9J7tMmN0" target="_blank" rel="noreferrer">Open complete Academy Drive ↗</a></div><b>☁️</b></section><section className="driveGrid">{folders.map(x=><a href={x[2]} target="_blank" rel="noreferrer" key={x[0]}><span>{x[3]}</span><div><h2>{x[0]}</h2><p>{x[1]}</p><b>Open folder ↗</b></div></a>)}</section><section className="classroomReady"><div><small>CLASSROOM-READY PLAN</small><h2>How materials should move</h2></div><ol><li><b>1</b><span>Curriculum folder stores the master lesson and teacher materials.</span></li><li><b>2</b><span>Student folder receives the child’s assignment copy and completed work.</span></li><li><b>3</b><span>Approved work moves into the reporting and portfolio evidence trail.</span></li></ol><p>Google Classroom is not directly connected yet. These folders prepare the materials without claiming that assignments or grades are automatically syncing.</p></section></main>}
