"use client";
import {useMemo,useState} from "react";

const tracks=[
 {id:"work",icon:"$",title:"Work & Pay",skill:"Percentages · equations",prompt:"Jerome works 18 hours at $20 per hour. If 15% is withheld, what is his take-home pay?",steps:["Gross pay: 18 × $20 = $360","Taxes withheld: $360 × 0.15 = $54","Take-home pay: $360 − $54 = $306"],answer:"306",unit:"$"},
 {id:"build",icon:"▱",title:"Construction",skill:"Measurement · geometry",prompt:"A room is 12 ft by 15 ft. Flooring costs $4 per square foot. What is the material cost?",steps:["Area: 12 × 15 = 180 square feet","Cost: 180 × $4 = $720"],answer:"720",unit:"$"},
 {id:"fire",icon:"🚒",title:"Fire Service",skill:"Ratios · rates",prompt:"A tank holds 500 gallons. A hose uses 125 gallons per minute. How many minutes will the tank last?",steps:["Time = total gallons ÷ gallons per minute","500 ÷ 125 = 4 minutes"],answer:"4",unit:"minutes"},
 {id:"code",icon:"</>",title:"Coding & Data",skill:"Functions · tables",prompt:"An app charges $5 plus $2 per user. Use y = 2x + 5. What is the total for 12 users?",steps:["Substitute x = 12","y = 2(12) + 5","y = 24 + 5 = 29"],answer:"29",unit:"$"},
 {id:"business",icon:"↗",title:"Business",skill:"Revenue · profit/loss",prompt:"A business sells 35 items for $18 each. Total costs are $410. What is the profit?",steps:["Revenue: 35 × $18 = $630","Profit = revenue − costs","$630 − $410 = $220"],answer:"220",unit:"$"}
];

export function AppliedMath(){
 const[index,setIndex]=useState(0),[shown,setShown]=useState(0),[input,setInput]=useState(""),[checked,setChecked]=useState(false),[wins,setWins]=useState<string[]>([]);
 const t=tracks[index],correct=Number(input)===Number(t.answer);
 const choose=(i:number)=>{setIndex(i);setShown(0);setInput("");setChecked(false)};
 return <section className="appliedMath"><div className="mathHero"><div><p className="eyebrow">APPLIED HIGH-SCHOOL MATH</p><h1>Use math where life uses math.</h1><p>Practice one short problem at a time. See the pathway, explain the decision, and connect Algebra I to work, construction, coding, firefighting, business, and independence.</p></div><div className="mathRoutine"><b>15-minute routine</b><ol><li>Read the situation</li><li>Choose an operation</li><li>Show each step</li><li>Check if the answer makes sense</li></ol></div></div>
 <div className="mathLabBody"><div className="trackTabs">{tracks.map((x,i)=><button key={x.id} className={index===i?"active":""} onClick={()=>choose(i)}><span>{x.icon}</span><b>{x.title}</b><small>{x.skill}</small></button>)}</div>
  <section className="challenge"><div className="challengeTop"><div><p className="eyebrow">TODAY’S REAL-WORLD CHALLENGE</p><h2>{t.title}</h2></div><span>{t.skill}</span></div><p className="problem">{t.prompt}</p><div className="workArea"><article><h3>Plan the pathway</h3><p>What information matters? What operation or formula will you use?</p><textarea placeholder="My plan is…"/><h3>Show the work</h3>{t.steps.slice(0,shown).map((s,i)=><p className="revealed" key={s}><b>{i+1}</b>{s}</p>)}<button disabled={shown===t.steps.length} onClick={()=>setShown(Math.min(t.steps.length,shown+1))}>{shown===0?"Reveal first step":"Reveal next step"}</button></article><aside><h3>Check your answer</h3><label><span>{t.unit==="$"?"$":""}</span><input inputMode="decimal" value={input} onChange={e=>{setInput(e.target.value);setChecked(false)}} placeholder="Answer"/><small>{t.unit!=="$"?t.unit:""}</small></label><button onClick={()=>setChecked(true)}>Check</button>{checked&&<div className={correct?"right":"try"}>{correct?"✓ Correct. Now explain why it makes sense.":"Not yet. Compare your work to the revealed steps and try again."}</div>}<textarea placeholder="My answer makes sense because…"/>{correct&&!wins.includes(t.id)&&<button className="finishMath" onClick={()=>setWins([...wins,t.id])}>Mark challenge complete</button>}</aside></div></section>
  <MathTools/>
  <section className="projectMath"><div><p className="eyebrow">HANDS-ON PROJECT</p><h2>Independent Living: Can this career support the plan?</h2><p>Choose a career, estimate monthly take-home pay, and test a realistic budget. This connects wages, taxes, percentages, equations, and decision-making.</p></div><BudgetProject/></section>
  <section className="tutorPanel"><div><h2>Tutor & teacher follow-up</h2><p>Use this after each short practice session so progress is visible and the next lesson stays focused.</p></div><div>{["Equation or skill practiced","Step Jerome completed independently","Step that needs another example","Real-world connection he understood","One target for the next session"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div><p className="mathWins"><b>{wins.length}</b> career challenges completed</p></section>
 </div></section>
}

function MathTools(){const cards=[["Equation","Keep both sides balanced. Undo addition/subtraction, then multiplication/division."],["Percent","Part = whole × decimal. Change 15% to 0.15 before multiplying."],["Rate","Rate compares two quantities: dollars per hour, miles per hour, gallons per minute."],["Graph","Read the labels and scale first. Then describe what changes and what stays constant."],["Area","Rectangle area = length × width. Always include square units."],["Profit","Profit = revenue − total costs. A negative answer means a loss."]];return <section className="mathTools"><div><p className="eyebrow">QUICK REFERENCE</p><h2>Choose the tool that matches the situation</h2></div><div>{cards.map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>}

function BudgetProject(){const[hourly,setHourly]=useState(22),[hours,setHours]=useState(40),[tax,setTax]=useState(18),[rent,setRent]=useState(1100),[food,setFood]=useState(350),[travel,setTravel]=useState(180),[other,setOther]=useState(300);const m=hourly*hours*52/12,take=m*(1-tax/100),left=take-rent-food-travel-other;const fields:Array<[string,number,(n:number)=>void,string]>=[["Hourly wage",hourly,setHourly,"$"],["Hours each week",hours,setHours,""],["Estimated taxes",tax,setTax,"%"],["Rent",rent,setRent,"$"],["Food",food,setFood,"$"],["Transportation",travel,setTravel,"$"],["Other expenses",other,setOther,"$"]];return <div className="budgetProject"><div>{fields.map(([label,val,setter,unit])=><label key={label}><span>{label}</span><div>{unit==="$"&&"$"}<input type="number" value={val} onChange={e=>setter(+e.target.value)}/>{unit==="%"&&"%"}</div></label>)}</div><article><p><span>Estimated gross monthly pay</span><b>${m.toFixed(2)}</b></p><p><span>Estimated take-home pay</span><b>${take.toFixed(2)}</b></p><p><span>Total monthly expenses</span><b>${(rent+food+travel+other).toFixed(2)}</b></p><strong className={left>=0?"positive":"negative"}><span>{left>=0?"Money remaining":"Budget shortage"}</span>${Math.abs(left).toFixed(2)}</strong><small>Estimate only. Actual pay, taxes, and expenses vary.</small></article></div>}
