"use client";
import {useEffect,useState} from "react";

const assignments=[
 {week:"Week 5",title:"Artificial Sea",role:"Lead scientist",mission:"Analyze the minerals and chemical processes, then explain two limits of the model ecosystem.",deliverable:"Comparison paragraph + labeled photo",career:"Environmental scientist"},
 {week:"Week 6",title:"Crane, Pump & Boomerang Car",role:"Test engineer",mission:"Help assemble safely, run three fair trials, graph one measurement, and recommend a design change.",deliverable:"Data table + graph + redesign note",career:"Mechanical engineer"},
 {week:"Week 10",title:"MEL Med Clinical Simulation",role:"Clinical lab trainee",mission:"Use a fictional patient case, record results precisely, protect privacy, and explain the limits of the test.",deliverable:"Lab record + medical-career reflection",career:"Medical laboratory scientist"},
 {week:"Week 11",title:"Kitchen Chemistry",role:"Chemistry explainer",mission:"Support Kameron’s measurements and explain the heat transfer or color-changing reaction using scientific vocabulary.",deliverable:"Science explanation + recipe evidence",career:"Food scientist"},
 {week:"Week 12",title:"Heat Transfer & Pure Water",role:"Environmental systems analyst",mission:"Collect results from both investigations and propose one improvement for a home or community system.",deliverable:"Two data tables + graph + recommendation",career:"Environmental engineer"},
 {week:"Week 16",title:"Screen-Printed Canvas Bins",role:"Product designer",mission:"Create the product, inspect quality, calculate cost and possible profit, and deliver a 30-second sales pitch.",deliverable:"Product photos + cost sheet + pitch",career:"Product designer / entrepreneur"}
];

export function AssignedLabs(){const[state,setState]=useState<Record<string,string>>({}),[drafts,setDrafts]=useState<Record<string,{reflection:string;evidence:string}>>({}),[notice,setNotice]=useState("");useEffect(()=>{try{setState(JSON.parse(localStorage.getItem("jerome-assigned-labs")||"{}"));setDrafts(JSON.parse(localStorage.getItem("jerome-lab-drafts")||"{}"))}catch{}},[]);const save=(k:string,v:string)=>{const n={...state,[k]:v};setState(n);localStorage.setItem("jerome-assigned-labs",JSON.stringify(n))};const draft=(k:string,p:Partial<{reflection:string;evidence:string}>)=>{const n={...drafts,[k]:{...(drafts[k]??{reflection:"",evidence:""}),...p}};setDrafts(n);localStorage.setItem("jerome-lab-drafts",JSON.stringify(n))};const submit=async(x:typeof assignments[number])=>{const d=drafts[x.title]||{reflection:"",evidence:""};const code=JSON.stringify({student:"Jerome",week:x.week,title:x.title,reflection:d.reflection,evidence:d.evidence,submittedAt:new Date().toLocaleDateString()});await navigator.clipboard.writeText(code);save(x.title,"Submitted");setNotice(`${x.title} submission code copied. Give it to Mom for the Lab Center.`);setTimeout(()=>setNotice(""),3500)};return <section className="assignedLabs"><div className="assignedHead"><div><p className="eyebrow">MY ASSIGNED LABS</p><h2>Know your role before the box opens</h2><p>These missions connect your kit work to Grade 10 science, technical writing, careers, and portfolio evidence.</p></div><b>{assignments.filter(x=>state[x.title]==="Submitted").length}/6 submitted</b></div>{notice&&<p className="submitNotice">{notice}</p>}<div className="assignmentGrid">{assignments.map(x=><article key={x.title}><div><span>{x.week}</span><small>{x.career}</small></div><h3>{x.title}</h3><b>{x.role}</b><p>{x.mission}</p><aside><strong>Turn in</strong>{x.deliverable}</aside><label>Status<select value={state[x.title]||"Assigned"} onChange={e=>save(x.title,e.target.value)}><option>Assigned</option><option>Ready</option><option>In progress</option><option>Submitted</option><option>Needs revision</option></select></label><label>Reflection<textarea value={drafts[x.title]?.reflection||""} onChange={e=>draft(x.title,{reflection:e.target.value})} placeholder="What did the evidence show?"/></label><label>Evidence prepared<textarea value={drafts[x.title]?.evidence||""} onChange={e=>draft(x.title,{evidence:e.target.value})} placeholder="Photos, graph, data sheet, paragraph…"/></label><button className="submitLab" onClick={()=>submit(x)}>Copy submission for Mom</button></article>)}</div><p className="assignmentNote">Your parent pastes the submission into the Weems Homeschool Hub, verifies safety, uploads files, grades the work, and approves it for your portfolio.</p></section>}
