"use client";
import {useState} from "react";
import {SmartResponse} from "./smart-response";

const careers=[
 {icon:"⌨",name:"Cybersecurity Analyst",learn:"Protect networks, investigate threats, document risks",path:"Practice networking, Linux, security labs, certifications, and communication",question:"Would I enjoy investigating problems and explaining how to prevent them?"},
 {icon:"▤",name:"Librarian / Information Specialist",learn:"Organize information, research, teach, preserve records",path:"Build research, database, writing, public-service, and library technology skills",question:"Would I enjoy helping people find accurate information?"},
 {icon:"🚒",name:"Firefighter",learn:"Emergency response, teamwork, safety, physical readiness",path:"Study fire science, CPR, public safety, fitness, and department requirements",question:"Can I stay calm, follow procedures, and support a team?"},
 {icon:"⌂",name:"Construction / CAD",learn:"Read plans, measure, build safely, coordinate projects",path:"Practice geometry, drawing, tools, OSHA safety, CAD, and apprenticeships",question:"Do I enjoy seeing a physical project take shape?"},
 {icon:"</>",name:"Coding Instructor",learn:"Build programs and teach technical ideas clearly",path:"Create projects, explain code, debug patiently, and help beginners",question:"Can I break one big idea into small teachable steps?"},
];

export function MoneyLab(){
 const [price,setPrice]=useState(50),[shares,setShares]=useState(10),[change,setChange]=useState(5),[lesson,setLesson]=useState(0);
 const start=price*shares,end=start*(1+change/100),profit=end-start;
 const lessons=[
  ["1. Build the foundation","Income, spending, saving, banking, credit, taxes, and insurance come before trading."],
  ["2. Understand ownership","A stock is a small ownership share in a company. A bond is generally a loan to a company or government."],
  ["3. Learn risk and return","Prices rise and fall. Higher possible return usually comes with higher risk. Losses are possible."],
  ["4. Research before decisions","Study the business, revenue, expenses, debt, competition, leadership, and risks—not social-media excitement."],
  ["5. Practice without real money","Use this simulator and a watchlist to learn. This class does not tell Jerome what to buy or sell."],
 ];
 return <section className="page expanded"><Title step="FINANCIAL LITERACY" title="Money first. Markets second." text="Learn everyday money management, then understand investing and trading without risking real money."/>
  <div className="lessonPath">{lessons.map((x,i)=><button key={x[0]} className={lesson===i?"selected":""} onClick={()=>setLesson(i)}><b>{x[0]}</b><span>{i===lesson?x[1]:"Open lesson"}</span></button>)}</div>
  <div className="financeGrid"><article><p className="eyebrow">PAPER-TRADING SIMULATOR</p><h3>Test a “what if” scenario</h3><label>Starting price <input type="number" value={price} min="1" onChange={e=>setPrice(+e.target.value)}/></label><label>Number of shares <input type="number" value={shares} min="1" onChange={e=>setShares(+e.target.value)}/></label><label>Price change (%) <input type="number" value={change} onChange={e=>setChange(+e.target.value)}/></label><div className="tradeResult"><span>Starting value <b>${start.toFixed(2)}</b></span><span>Ending value <b>${end.toFixed(2)}</b></span><strong className={profit<0?"loss":"gain"}>{profit>=0?"Gain":"Loss"}: ${Math.abs(profit).toFixed(2)}</strong></div></article>
  <article><p className="eyebrow">RESEARCH BEFORE TRADING</p><h3>Jerome’s company checklist</h3>{["What does the company sell?","How does it make money?","Are revenue and profit growing?","How much debt does it have?","Who are its competitors?","What could cause the price to fall?","Am I reacting to facts or excitement?"].map(x=><label className="checkLine" key={x}><input type="checkbox"/> {x}</label>)}<p className="note">Education only. The simulator uses imaginary scenarios and is not investment advice.</p></article></div>
  <div className="conceptGrid">{[["Stock","Partial ownership in a company"],["Bond","A loan that may pay interest"],["ETF","A fund holding a group of investments"],["Dividend","Money some companies pay shareholders"],["Volatility","How sharply price changes"],["Diversification","Spreading risk across investments"]].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div><WorkPack title="Money & Stocks Work Pack" tasks={["Bring a calculator, notebook, and pencil","Complete one paper-trading scenario without real money","Choose a familiar company and describe how it earns money","List two company risks and explain diversification","Write a five-sentence reflection using three vocabulary terms"]} links={[["Investor.gov: Introduction to Investing","https://www.investor.gov/introduction-investing"],["Investor.gov: Student Classroom Resources","https://www.investor.gov/additional-resources/information/youth/resources-classrooms"],["Investor.gov: Diversification Lesson","https://www.investor.gov/introduction-investing/investing-basics/save-and-invest/diversify-your-investments"]]}/>
 </section>;
}

export function LearningLab(){const [topic,setTopic]=useState("thesis"),[claim,setClaim]=useState(""),[why,setWhy]=useState("");return <section className="page expanded"><Title step="ACADEMIC STRENGTH LAB" title="Think deeply. Research carefully. Write clearly." text="Build high-school math and writing skills through organized, meaningful work."/><div className="labTabs">{[["thesis","Thesis Writing"],["coach","Answer Coach"],["crt","Critical Race Theory"],["math","Strong Math"],["write","Strong Writing"],["careers","Career Research"]].map(x=><button className={topic===x[0]?"selected":""} onClick={()=>setTopic(x[0])} key={x[0]}>{x[1]}</button>)}</div>
 {topic==="thesis"&&<div className="academicCard"><h3>Thesis Builder</h3><p>A thesis is a focused, arguable answer to a research question—not merely a topic.</p><label>My claim<SmartResponse value={claim} onChange={setClaim} mode="argue" placeholder="I argue that…"/></label><label>Why it matters<SmartResponse value={why} onChange={setWhy} mode="analyze" placeholder="This matters because…"/></label><div className="thesisPreview"><b>Draft:</b> {claim&&why?`${claim}. This matters because ${why.toLowerCase()}.`:"Complete both boxes to form a draft thesis."}</div><ol><li>Ask a focused research question.</li><li>Read credible sources with different perspectives.</li><li>Make an arguable claim.</li><li>Support it with evidence and citations.</li><li>Explain how the evidence proves the claim.</li><li>Revise after feedback.</li></ol></div>}
 {topic==="coach"&&<AnswerCoach/>}
 {topic==="crt"&&<div className="academicCard"><h3>Critical Race Theory: an age-appropriate introduction</h3><p>In this course, Jerome examines how laws, policies, institutions, and history can shape racial inequality—not whether individual people are simply “good” or “bad.”</p><div className="inquiryGrid"><article><b>History</b><p>What happened, when, and under which laws?</p></article><article><b>Systems</b><p>How did policies affect education, housing, voting, policing, or wealth?</p></article><article><b>Evidence</b><p>What do primary sources, court cases, data, and scholars show?</p></article><article><b>Perspectives</b><p>Where do interpretations agree or disagree?</p></article></div><h4>Research sequence</h4><ol><li>Define the term and distinguish it from general diversity education.</li><li>Study one historical policy, such as redlining or school segregation.</li><li>Analyze a primary source and a data source.</li><li>Compare two scholarly interpretations.</li><li>Write a claim supported by cited evidence.</li></ol></div>}
 {topic==="math"&&<div className="academicCard"><h3>Strong Math Routine</h3><div className="skillSteps">{[["1","Read and mark what is known"],["2","Draw a model, table, graph, or number line"],["3","Solve one visible step"],["4","Check with estimation or substitution"],["5","Explain the answer in words"]].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div><p className="note">Plan: short practice several days each week, visual support first, repetition without shame, and guided help on multi-step work.</p></div>}
 {topic==="write"&&<div className="academicCard"><h3>Strong Writing Routine</h3><div className="skillSteps">{[["P","Plan the purpose and audience"],["C","State a clear claim"],["E","Choose specific evidence"],["R","Explain the reasoning"],["R","Revise for structure and clarity"],["P","Proofread spelling, punctuation, and citations"]].map((x,i)=><article key={i}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div></div>}
 {topic==="careers"&&<div className="careerResearch">{careers.map(c=><article key={c.name}><span>{c.icon}</span><h3>{c.name}</h3><p><b>Work:</b> {c.learn}</p><p><b>Preparation:</b> {c.path}</p><p><b>Ask yourself:</b> {c.question}</p><textarea placeholder="What I learned from my research…"/></article>)}</div>}<WorkPack title="Lesson Preparation & Assignment" tasks={topic==="math"?["Prepare graph paper, calculator, and pencil","Warm up with two one-step equations","Complete one modeled example","Solve three problems independently","Check each answer and explain one aloud"]:topic==="crt"?["Open one Library of Congress primary source","Record its creator, date, audience, and purpose","Explain what it shows and what it cannot prove alone","Compare it with a secondary source","Write one evidence-based claim with a citation"]:topic==="careers"?["Choose one career","Record duties, training, work setting, salary, and outlook","List three existing strengths and two skills to build","Find one training program or apprenticeship","Write whether the career stays on the exploration list"]:["Read the prompt twice and underline the action word","Open the Purdue lesson below","Create a claim-evidence-reasoning outline","Draft one complete paragraph","Revise structure, then proofread mechanics"]} links={topic==="crt"?[["Library of Congress: Brown v. Board Exhibit","https://www.loc.gov/exhibits/brown/brown-segregation.html"],["Library of Congress: Great Migration","https://www.loc.gov/classroom-materials/great-migration/"],["Library of Congress: African American Studies","https://guides.loc.gov/african-american-studies"]]:topic==="careers"?[["BLS Career Exploration","https://www.bls.gov/k12/students/careers/career-exploration.htm"],["BLS Occupational Outlook Handbook","https://www.bls.gov/ooh/"],["BLS Computer & IT Careers","https://www.bls.gov/ooh/computer-and-information-technology/"]]:topic==="math"?[]:[["Purdue OWL: Thesis Statements","https://owl.purdue.edu/owl/general_writing/the_writing_process/thesis_statement_tips.html"],["Purdue OWL: Argument Essays","https://owl.purdue.edu/owl/general_writing/academic_writing/essay_writing/argumentative_essays.html"],["Purdue OWL: Body Paragraphs","https://owl.purdue.edu/owl/general_writing/common_writing_assignments/argument_papers/body_paragraphs.html"]]}/>
 </section>}

function AnswerCoach(){
 const [answer,setAnswer]=useState(""),[mode,setMode]=useState("explain"),[checked,setChecked]=useState(false);
 const tidy=(value:string)=>{let x=value.trim().replace(/\s+/g," ").replace(/\bi\b/g,"I").replace(/\bcant\b/gi,"can't").replace(/\bdont\b/gi,"don't").replace(/\bwont\b/gi,"won't").replace(/\bbecause of the fact that\b/gi,"because").replace(/\ba lot of\b/gi,"many");if(x)x=x[0].toUpperCase()+x.slice(1);if(x&&!/[.!?]$/.test(x))x+=".";return x};
 const corrected=tidy(answer),starters:{[key:string]:string[]}={explain:["The main idea is…","This means…","For example…"],analyze:["The evidence suggests…","This is important because…","A connection I notice is…"],compare:["Both sources show…","However, they differ because…","The stronger evidence is…"],argue:["I argue that…","One piece of evidence is…","This supports my claim because…"]};
 return <div className="answerCoach"><div className="coachIntro"><div><p className="eyebrow">WRITE → REVIEW → IMPROVE</p><h3>Answer & Analysis Coach</h3><p>Write the answer in your own words first. The coach helps with structure and shows ways to deepen the thinking—it does not replace Jerome’s ideas.</p></div><div className="answerModes">{[["explain","Explain"],["analyze","Analyze"],["compare","Compare"],["argue","Make an argument"]].map(x=><button className={mode===x[0]?"selected":""} onClick={()=>setMode(x[0])} key={x[0]}>{x[1]}</button>)}</div></div><label className="answerDraft"><b>Jerome’s original answer</b><textarea value={answer} onChange={e=>{setAnswer(e.target.value);setChecked(false)}} placeholder="Type or use talk-to-text to answer in your own words…"/></label><button className="reviewAnswer" disabled={!answer.trim()} onClick={()=>setChecked(true)}>Review my answer</button>{checked&&<div className="coachResults"><article><small>1 · CORRECTED STRUCTURE</small><h4>Clear sentence version</h4><p>{corrected}</p><ul><li>Starts with a capital letter</li><li>Uses complete punctuation</li><li>Fixes spacing and common informal spellings</li></ul></article><article><small>2 · DEEPER RESPONSE</small><h4>Choose a sentence starter</h4>{starters[mode].map(x=><button key={x} onClick={()=>setAnswer(`${corrected} ${x} `)}>{x}</button>)}<p className="coachTip"><b>Analysis check:</b> Add what the evidence shows, why it matters, and how it connects to the question.</p></article><article><small>3 · SELF-CHECK</small><h4>Before submitting</h4>{["Did I answer every part of the question?","Did I include a specific fact, quote, example, or calculation?","Did I explain how my evidence supports my answer?","Did I reread it aloud for clarity?"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article></div>}</div>
}

const videos=[
 {cat:"Money & Stocks",title:"Stocks and Bonds — Khan Academy",url:"https://www.youtube.com/watch?v=Qh-M3_L4xYk",note:"Understand ownership, borrowing, stocks, and bonds."},
 {cat:"Money & Stocks",title:"Investments and Retirement — Khan Academy",url:"https://www.youtube.com/watch?v=jhvCc5tKAno",note:"Connect investing to long-term planning."},
 {cat:"Cybersecurity",title:"A Real Day in Cybersecurity",url:"https://www.youtube.com/watch?v=dUjNVzzqTiA",note:"Observe tasks performed by a cybersecurity analyst."},
 {cat:"Library Careers",title:"On My Way: A Day in the Life of a Librarian",url:"https://www.youtube.com/watch?v=xtHlrqyWtbc",note:"See modern library work beyond shelving books."},
 {cat:"Library Careers",title:"Career Day: Careers at the Library",url:"https://www.youtube.com/watch?v=tw0uqiyXk1o",note:"Explore different jobs inside library systems."},
 {cat:"Construction",title:"Read and Understand Construction Drawings",url:"https://www.youtube.com/watch?v=gm1VPqa-dRk",note:"Practice interpreting professional building plans."},
];
export function VideoLibrary(){const [filter,setFilter]=useState("All"),cats=["All",...Array.from(new Set(videos.map(v=>v.cat)))];return <section className="page expanded"><Title step="LEARNING LIBRARY" title="Watch with a purpose" text="Each video has a learning goal. After watching, record one fact, one question, and one possible next step."/><div className="labTabs">{cats.map(c=><button className={filter===c?"selected":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="videoGrid">{videos.filter(v=>filter==="All"||v.cat===filter).map(v=><article key={v.url}><div className="videoIcon">▶</div><small>{v.cat}</small><h3>{v.title}</h3><p>{v.note}</p><a href={v.url} target="_blank" rel="noreferrer">Watch on YouTube ↗</a><textarea placeholder="One fact, one question, or one next step…"/></article>)}</div><p className="note">YouTube may show recommended content or advertising. Jerome should use the linked lesson pages with normal family supervision.</p></section>}
const recapSubjects=[
 ["⚖","Tuttle Twins","Civics, economics, freedom, government, and responsibility"],["♫","Music, Piano & Production","Performance, rhythm, theory, listening, recording, and production"],["¡","Spanish","Vocabulary, pronunciation, listening, speaking, reading, and culture"],["⚗","Biology & Science","Labs, systems, evidence, variables, observations, and data"],["⌛","History & Geography","Timelines, people, places, causes, consequences, maps, and perspectives"],["</>","Coding & Cybersecurity","Logic, debugging, app development, privacy, safety, and systems"],["📖","Literature & English","Comprehension, Poe, Maya Angelou, themes, evidence, and analysis"],["∑","Mathematics","Algebra, geometry, reasoning, visual models, and checking work"],["✎","Art, Drawing & Media","Drawing, photography, film, editing, and design"],["🥋","Karate, Health & Fitness","Technique, movement, regulation, leadership, and perseverance"],["🧯","Safety & Independent Living","Fire safety, hygiene, food, transportation, scheduling, and home skills"],["◆","Financial Literacy","Budgeting, banking, credit, taxes, investing, and entrepreneurship"],["◎","Speech, OT & Social-Emotional","Communication, self-advocacy, organization, coping, and regulation"],["🤝","Community Service & Leadership","Service, debate, civic participation, teamwork, and mentoring"]
];
export function SubjectRecap(){const [selected,setSelected]=useState(0),[answers,setAnswers]=useState<Record<string,string[]>>(()=>{try{return JSON.parse(localStorage.getItem("jerome-subject-recaps")||"{}")}catch{return{}}});const s=recapSubjects[selected],values=answers[s[1]]||["","",""];const prompts=["What was the main idea, skill, or lesson?","What example, evidence, creation, or experience helps me remember it?","How does this connect to real life, another subject, or my next goal?"];const update=(i:number,v:string)=>{const next={...answers,[s[1]]:values.map((x,n)=>n===i?v:x)};setAnswers(next);localStorage.setItem("jerome-subject-recaps",JSON.stringify(next))};return <section className="page expanded"><Title step="WHOLE-PROGRAM REVIEW" title="Subject Recap Studio" text="Remember it, explain it, connect it, and decide what comes next. Recaps save on this device."/><div className="recapLayout"><aside className="subjectList">{recapSubjects.map((x,i)=><button key={x[1]} className={i===selected?"selected":""} onClick={()=>setSelected(i)}><span>{x[0]}</span><b>{x[1]}</b><small>{(answers[x[1]]||[]).filter(Boolean).length}/3 answered</small></button>)}</aside><article className="recapCard"><div className="recapHead"><span>{s[0]}</span><div><p className="eyebrow">SUBJECT RECAP</p><h2>{s[1]}</h2><p>{s[2]}</p></div></div>{prompts.map((p,i)=><label key={p}><b>{i+1}. {p}</b><SmartResponse value={values[i]} onChange={v=>update(i,v)} mode={i===0?"explain":"analyze"}/></label>)}<div className="recapTools"><button onClick={()=>window.print()}>Print this recap</button><b>{values.filter(Boolean).length===3?"✓ Recap complete":"Complete all three reflections"}</b></div></article></div><section className="weeklyReview"><h3>Friday Whole-Week Review</h3><div>{["My strongest subject this week","Something that was difficult","A connection between two subjects","My priority for next week"].map(x=><label key={x}>{x}<input placeholder="Write a short reflection…"/></label>)}</div></section></section>}
function Title({step,title,text}:{step:string;title:string;text:string}){return <div className="title"><p className="eyebrow">{step}</p><h2>{title}</h2><p>{text}</p></div>}
function WorkPack({title,tasks,links}:{title:string;tasks:string[];links:string[][]}){return <section className="workPack"><h3>{title}</h3><div><article><b>Prepare and complete</b>{tasks.map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article><article><b>Internet resources woven into this lesson</b>{links.length?links.map(x=><a href={x[1]} target="_blank" rel="noreferrer" key={x[1]}>{x[0]} ↗</a>):<p>Use the interactive lesson and teacher-provided practice problems.</p>}</article></div></section>}
