"use client";
import {useEffect,useMemo,useState} from "react";

const weekly=[
 {group:"Personal care",items:["Shower and use deodorant","Brush teeth morning and night","Choose clean clothes","Manage hair, nails, and needed personal supplies"]},
 {group:"Space & belongings",items:["Laundry moved through wash, dry, and put away","School workspace reset","Bag, charger, and headphones returned to their places","Trash, dishes, and personal items handled"]},
 {group:"Schedule & preparation",items:["Review the week’s appointments and classes","Prepare materials the night before travel","Set reminders for deadlines","Tell an adult about a conflict or missing item early"]},
 {group:"Home responsibility",items:["Complete one assigned household responsibility","Prepare one simple meal or snack safely","Check personal supplies before they run out","Help with one family or sibling responsibility as agreed"]}
];
const situations=[
 {title:"The plan suddenly changes",steps:["Pause before answering.","Ask: What changed, what stayed the same, and what happens first?","Write or repeat the new first step.","Request time or support if the change is too much."]},
 {title:"I do not know what to do",steps:["Look for the instruction, schedule, sign, or contact.","Name the exact part you understand.","Ask one specific question.","Wait in a safe place if immediate action is not required."]},
 {title:"I made a mistake",steps:["Stop and make sure everyone is safe.","State what happened without hiding or exaggerating.","Ask what can be corrected now.","Record what will prevent the same mistake next time."]},
 {title:"I am running late",steps:["Check the actual time and travel estimate.","Contact the responsible person before arrival time.","Give a short honest update and new estimate.","Adjust preparation time for the next trip."]}
];

export function IndependenceLab(){const[done,setDone]=useState<string[]>([]),[task,setTask]=useState(""),[steps,setSteps]=useState(["","",""]),[situation,setSituation]=useState(0);useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("jerome-independence-week")||"[]"))}catch{}},[]);const toggle=(x:string)=>setDone(d=>{const n=d.includes(x)?d.filter(y=>y!==x):[...d,x];localStorage.setItem("jerome-independence-week",JSON.stringify(n));return n});const total=weekly.flatMap(x=>x.items).length,percent=Math.round(done.length/total*100);return <section className="independenceLab"><div className="indHero"><div><p className="eyebrow">INDEPENDENT LIVING & EXECUTIVE SKILLS</p><h1>Build systems that make adulthood easier.</h1><p>Independence does not mean never needing help. It means knowing the routine, preparing ahead, recognizing a problem, and asking for the right support.</p></div><div className="indScore"><b>{percent}%</b><span>weekly routine complete</span><i><em style={{width:`${percent}%`}}/></i><button onClick={()=>{setDone([]);localStorage.removeItem("jerome-independence-week")}}>Start a new week</button></div></div>
 <div className="indBody"><section><Heading n="01" title="Weekly independent-living routine" text="Use one checklist for the entire week. The goal is fewer prompts over time—not perfection."/><div className="weeklyGrid">{weekly.map(g=><article key={g.group}><h3>{g.group}</h3>{g.items.map(x=><button key={x} className={done.includes(x)?"done":""} onClick={()=>toggle(x)}><span>{done.includes(x)?"✓":"○"}</span>{x}</button>)}</article>)}</div></section>
 <section><Heading n="02" title="Turn a big task into a visible sequence" text="Write the finish line first. Then create only the next three actions."/><div className="sequenceBuilder"><label><b>The finished result should look like…</b><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="My school bag is ready by the door with…"/></label><div>{steps.map((x,i)=><label key={i}><span>{i+1}</span><input value={x} onChange={e=>setSteps(s=>s.map((v,n)=>n===i?e.target.value:v))} placeholder={["First visible action","Next action","Final check"][i]}/></label>)}</div><article><b>My plan</b><p>{task||"Describe the finished result."}</p>{steps.filter(Boolean).map((x,i)=><p key={i}><span>{i+1}</span>{x}</p>)}</article></div></section>
 <section><Heading n="03" title="Handle an unexpected situation without guessing" text="Choose a situation and follow a reliable response pathway."/><div className="situationTabs">{situations.map((x,i)=><button key={x.title} className={situation===i?"active":""} onClick={()=>setSituation(i)}>{x.title}</button>)}</div><div className="situationPlan"><h3>{situations[situation].title}</h3><ol>{situations[situation].steps.map(x=><li key={x}>{x}</li>)}</ol><b>Safety rule: If you feel unsafe, are lost, or do not know who to trust, contact your parent or designated trusted adult and stay in a visible public place.</b></div></section>
 <section><Heading n="04" title="Plan an appointment or trip" text="Complete this before tutoring, co-op, an appointment, work experience, or independent travel practice."/><div className="tripPlan">{["Where am I going?","Date and arrival time","How will I get there?","What time should I leave?","Who is the contact person?","What do I need to bring?","What is the backup plan?","How will I confirm I arrived safely?"].map(x=><label key={x}><b>{x}</b><input/></label>)}</div><div className="travelCheck">{["Address checked","Route reviewed","Travel time checked","Phone charged","Fare/payment ready","Contact saved","Weather checked","Return plan known"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></section>
 <section><Heading n="05" title="Practice workplace-ready communication" text="Clear, short communication is professional self-advocacy."/><div className="workScripts">{[["Clarify","“I understand the goal. Could you show me what the finished result should look like?”"],["Prioritize","“I have two tasks. Which one needs to be completed first?”"],["Report a problem","“I noticed a problem with ___. I stopped because I was unsure whether it was safe to continue.”"],["Ask for time","“I need a few minutes to process the instructions. I will check back at ___.”"],["Report progress","“I finished ___. My next step is ___. I need help with ___.”"],["Own a mistake","“I made an error on ___. Here is what happened and the step I can take to correct it.”"]].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>
 <section><Heading n="06" title="Track growth without turning it into a grade" text="Review this monthly with Jerome, a parent, counselor, OT, or job coach."/><div className="growthScale">{["I need someone to do it with me.","I can do it with step-by-step prompts.","I can do it with one reminder.","I can do it independently.","I can explain or teach the system to someone else."].map((x,i)=><label key={x}><input type="radio" name="growth"/><b>{i+1}</b><span>{x}</span></label>)}</div><textarea className="growthNote" placeholder="This month I became more independent with…"/><button className="printInd" onClick={()=>window.print()}>Print / save progress as PDF</button></section></div></section>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="indHeading"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
