"use client";
import {useEffect,useMemo,useState} from "react";
type Entry={id:number;date:string;place:string;kind:string;hours:string;role:string;impact:string;reflection:string;feedback:string;evidence:string};
const blank=()=>({id:Date.now(),date:"",place:"",kind:"Community service",hours:"",role:"",impact:"",reflection:"",feedback:"",evidence:""});
const milestones=[
 {q:"Quarter 1",due:"November 15, 2026",goal:"Complete at least one community or civic activity and establish mentor/work-based expectations."},
 {q:"Quarter 2",due:"January 31, 2027",goal:"Complete two additional service experiences and assume one supervised responsibility at the dojo or GoCoding."},
 {q:"Quarter 3",due:"April 15, 2027",goal:"Complete two additional service experiences and connect leadership to skilled trades or career comparison."},
 {q:"Quarter 4",due:"June 30, 2027",goal:"Complete the sixth experience, demonstrate leadership, and finish the vocational/personal-growth portfolio."}
];
export function LeadershipTracker(){const[entries,setEntries]=useState<Entry[]>([]),[form,setForm]=useState<Entry>(blank());useEffect(()=>{try{setEntries(JSON.parse(localStorage.getItem("jerome-leadership-record")||"[]"))}catch{}},[]);const save=(all:Entry[])=>{setEntries(all);localStorage.setItem("jerome-leadership-record",JSON.stringify(all))};const add=()=>{if(!form.date||!form.place||!form.role)return alert("Add the date, organization/location, and Jerome’s responsibility.");save([...entries,form]);setForm(blank())};const serviceCount=entries.filter(x=>x.kind==="Community service"||x.kind==="Civic activity").length,totalHours=entries.reduce((n,x)=>n+(Number(x.hours)||0),0),leadership=entries.filter(x=>["Dojo leadership","GoCoding responsibility","Internship / job shadow"].includes(x.kind)).length;return <section className="leadershipTracker"><div className="leadHero"><div><p className="eyebrow">LEADERSHIP, SERVICE & WORK-BASED LEARNING</p><h1>Turn responsibility into a record of readiness.</h1><p>Jerome’s service, internship practice, supervised responsibilities, and leadership demonstrations become evidence he can explain in a portfolio, interview, quarterly report, or future application.</p></div><div className="leadStats"><article><b>{Math.min(serviceCount,6)}/6</b><span>yearly service experiences</span></article><article><b>{totalHours}</b><span>documented hours</span></article><article><b>{leadership}</b><span>leadership experiences</span></article></div></div>
 <div className="leadBody"><section><Heading n="01" title="Follow the quarterly pathway" text="The work builds from participation to supervised responsibility to demonstrated leadership."/><div className="quarterPath">{milestones.map((x,i)=><article key={x.q}><span>{i+1}</span><small>{x.due}</small><h3>{x.q}</h3><p>{x.goal}</p></article>)}</div></section>
 <section><Heading n="02" title="Know what supervised leadership can look like" text="Start with clear, safe responsibilities and increase independence with mentor approval."/><div className="roleGrid"><article><h3>Dojo pathway</h3>{["Set up and clean the learning space","Greet students respectfully","Demonstrate an exercise","Support warmups","Model focus and safety","Give one clear direction","Help organize equipment","Reflect with Master Pascal"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article><article><h3>GoCoding pathway</h3>{["Prepare devices or materials","Help a learner begin a task","Explain one coding concept","Test or debug a project","Demonstrate a Newman milestone","Track a small project step","Practice professional communication","Reflect with the GoCoding mentor"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article><article><h3>Community pathway</h3>{["Follow the organization’s expectations","Arrive prepared and on time","Complete the assigned responsibility","Ask before changing the task","Communicate respectfully","Notice who benefits from the work","Request supervisor feedback","Write a brief impact reflection"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article></div></section>
 <section><Heading n="03" title="Add a service or leadership experience" text="Record enough detail to show what Jerome actually did—not simply where he went."/><div className="entryForm"><label><b>Date</b><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label><b>Organization or location</b><input value={form.place} onChange={e=>setForm({...form,place:e.target.value})} placeholder="Dojo, GoCoding, community event…"/></label><label><b>Experience type</b><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{["Community service","Civic activity","Dojo leadership","GoCoding responsibility","Internship / job shadow","Career demonstration","Fire-safety / public service"].map(x=><option key={x}>{x}</option>)}</select></label><label><b>Hours</b><input type="number" min="0" step="0.25" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></label><label className="wide"><b>What was Jerome responsible for?</b><textarea value={form.role} onChange={e=>setForm({...form,role:e.target.value})} placeholder="Specific actions, task, or supervised duty…"/></label><label><b>Who benefited, and how?</b><textarea value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}/></label><label><b>What did Jerome learn?</b><textarea value={form.reflection} onChange={e=>setForm({...form,reflection:e.target.value})}/></label><label><b>Supervisor or mentor feedback</b><textarea value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})}/></label><label><b>Evidence saved</b><textarea value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})} placeholder="Photo, work sample, note, certificate, demonstration…"/></label></div><button className="addExperience" onClick={add}>Add experience to Jerome’s record</button></section>
 <section><Heading n="04" title="Review Jerome’s transition record" text="These entries stay on this device until copied, printed, or added to the official instructor records."/>{entries.length===0?<p className="emptyRecord">No experiences recorded yet.</p>:<div className="experienceList">{entries.map((x,i)=><article key={x.id}><div><span>#{i+1}</span><small>{x.date}</small><button onClick={()=>save(entries.filter(e=>e.id!==x.id))}>Remove</button></div><h3>{x.place}</h3><b>{x.kind} · {x.hours||"0"} hours</b><p><strong>Responsibility:</strong> {x.role}</p>{x.impact&&<p><strong>Impact:</strong> {x.impact}</p>}{x.reflection&&<p><strong>Reflection:</strong> {x.reflection}</p>}{x.feedback&&<p><strong>Feedback:</strong> {x.feedback}</p>}{x.evidence&&<p><strong>Evidence:</strong> {x.evidence}</p>}</article>)}</div>}<button className="printLead" onClick={()=>window.print()}>Print / save the transition record as PDF</button></section>
 <section><Heading n="05" title="Prepare for an interview or portfolio presentation" text="Jerome should be able to explain one experience with a clear example."/><div className="storyBuilder">{[["Situation","Where were you, and what needed to be done?"],["Task","What responsibility were you given?"],["Action","What specific steps did you take?"],["Result","What changed, who benefited, or what did you learn?"]].map((x,i)=><label key={x[0]}><span>{i+1}</span><b>{x[0]}</b><small>{x[1]}</small><textarea/></label>)}</div></section></div></section>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="leadHeading"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
