"use client";
import {useEffect,useState} from "react";
import {LearningLab,MoneyLab,SubjectRecap,VideoLibrary} from "./expanded";
import {Jerome90DayPlan} from "./agenda90";
import {Careers} from "./careers";
import {WritingCoach} from "./writing-coach";
import {ThesisLab} from "./thesis-lab";
import {AppliedMath} from "./applied-math";
import {LessonSupport} from "./lesson-support";
import {WellnessPlan} from "./wellness-plan";
import {IndependenceLab} from "./independence-lab";
import {MentorCenter} from "./mentor-center";
import {LeadershipTracker} from "./leadership-tracker";
import {SkillBadges} from "./skill-badges";
import {SpeakingLab} from "./speaking-lab";
import {ScienceLab} from "./science-lab";
import {Portfolio} from "./portfolio";
import {WorkPlanner} from "./planner";
import {StudentReminders} from "./student-reminders";
import {CivilRightsLab} from "./civil-rights-lab";
import {DrivingBasics,FamilyDigitalLab} from "./life-tech-lab";
const routines=["Shower + deodorant","Brush teeth","Get dressed","Set up workspace"];
const missions=[
 ["∑","Math: One Step at a Time","Visual Algebra and multi-step practice","math"],
 ["</>","Code + Create","Move the Newman app or a coding challenge forward","future"],
 ["✦","Read, Think, Explain","Build a claim with evidence","writing"]
];
const sectionGroups=[
 {label:"My School Day",items:[["today","Today"],["planner","Work Planner"],["agenda","90-Day Plan"],["recap","Subject Recap"],["portfolio","Portfolio"],["mentors","Mentors & Services"]]},
 {label:"Academic Labs",items:[["learning","Learning Lab"],["digital","Family Internet & AI"],["rights","Civil Law & My Rights"],["science","Science & Engineering"],["thesis","Thesis Lab"],["speaking","Debate & Speaking"],["appliedMath","Applied Math"],["lessons","Lesson Support"]]},
 {label:"Future & Independence",items:[["future","Careers"],["driving","Driving Readiness"],["money","Money & Stocks"],["independence","Independent Living"],["leadership","Leadership & Service"],["badges","Courses & Skill Badges"],["wellness","Wellness"],["support","Support Tools"]]},
 {label:"Media",items:[["library","Video Library"]]}
];
export default function Home(){
 const stamp=new Date().toISOString().slice(0,10),key=`jerome-${stamp}`;
 const [view,setView]=useState("today"),[done,setDone]=useState<string[]>([]),[energy,setEnergy]=useState(""),[goal,setGoal]=useState(""),[reply,setReply]=useState(""),[wins,setWins]=useState<string[]>([]),[readMode,setReadMode]=useState(false),[speaking,setSpeaking]=useState(false);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(key)||"{}");setDone(x.done||[]);setEnergy(x.energy||"");setGoal(x.goal||"");setWins(x.wins||[])}catch{}},[key]);
 useEffect(()=>localStorage.setItem(key,JSON.stringify({done,energy,goal,wins})),[key,done,energy,goal,wins]);
 const toggle=(x:string)=>setDone(d=>d.includes(x)?d.filter(y=>y!==x):[...d,x]);
 const speak=(x:string)=>{if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(x.slice(0,2200));u.rate=.88;u.pitch=.92;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u)};
 const readSection=(e:React.MouseEvent<HTMLElement>)=>{if(!readMode)return;const target=e.target as HTMLElement;if(target.closest("button,input,textarea,select,a,label"))return;const block=target.closest("section,article") as HTMLElement|null;if(block)speak(block.innerText)};
 return <main onClickCapture={readSection}><header><a className="brand" href="#top" onClick={e=>{e.preventDefault();setView("today")}}><span>J</span><div><b>JEROME’S NEXT LEVEL</b><small>Build skills. Build independence.</small></div></a><label className="sectionPicker"><span>Choose a section</span><select value={view} onChange={e=>{setView(e.target.value);window.scrollTo({top:0,behavior:"smooth"})}} aria-label="Choose a section">{sectionGroups.map(g=><optgroup key={g.label} label={g.label}>{g.items.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</optgroup>)}</select></label><LiveClock/></header><div className="accessBar" role="region" aria-label="Reading and voice tools"><b>Accessibility</b><button className={readMode?"active":""} aria-pressed={readMode} onClick={()=>{setReadMode(!readMode);speak(!readMode?"Click-to-read is on. Tap the text area of any section to hear it.":"Click-to-read is off.")}}>🔊 Click-to-read {readMode?"on":"off"}</button><button onClick={()=>{window.speechSynthesis?.cancel();setSpeaking(false)}} disabled={!speaking}>■ Stop reading</button><Voice onText={()=>{}} checkOnly/></div>
 {view==="today"&&<><section className="hero" id="top"><div><p className="eyebrow">YOUR DAY. YOUR PACE. YOUR PLAN.</p><h1>Good afternoon, Jerome.</h1><p>You do not have to do everything at once. Choose the next clear step, use the supports that work, and keep moving forward.</p><div className="actions"><button onClick={()=>document.querySelector(".launch")?.scrollIntoView({behavior:"smooth"})}>Start today’s launch</button><button className="ghost" onClick={()=>speak("Good afternoon, Jerome. Choose the next clear step, use the supports that work, and keep moving forward.")}>🔊 Listen</button></div></div><div className="status"><small>TODAY’S PROGRESS</small><strong>{done.length}</strong><span>steps completed</span><i><b style={{width:`${globalThis.Math.min(100,done.length/7*100)}%`}}/></i></div></section><StudentReminders/>
 <section className="launch"><Title step="01 — DAILY LAUNCH" title="Get ready without the guesswork" text="A predictable start clears mental traffic. Complete these in the order that works for you."/><div className="routineGrid">{routines.map((x,i)=><button key={x} onClick={()=>toggle(`r${i}`)} className={done.includes(`r${i}`)?"done":""}><span>{done.includes(`r${i}`)?"✓":"○"}</span><b>{x}</b><small>{["Health and readiness","Two focused minutes","Comfortable and ready","Water, charger, materials"][i]}</small></button>)}</div><LearningPortals/></section>
 <section className="check"><Title step="02 — SELF CHECK" title="What does your system need?" text="This is information—not a grade. Choose the answer that fits right now."/><div className="energy">{[["Focused","Ready for a challenge"],["Starting Slow","Begin with an easy win"],["Overloaded","Reduce noise and choices"],["Need Movement","Take a five-minute reset"]].map(x=><button className={energy===x[0]?"selected":""} onClick={()=>{setEnergy(x[0]);speak(`${x[0]}. Good self awareness.`)}} key={x[0]}><span>◎</span><b>{x[0]}</b><small>{x[1]}</small></button>)}</div>{energy&&<p className="response">You chose <b>{energy}</b>. {energy==="Overloaded"?"Pause notifications, lower the noise, and choose one next step.":energy==="Need Movement"?"Walk, stretch, or do a short karate pattern—then return.":energy==="Starting Slow"?"Start with a five-minute task to create momentum.":"Use that focus on the mission that matters most."}</p>}</section>
 <section className="goal"><div><p className="eyebrow">03 — OWN THE DAY</p><h2>What do you want to accomplish?</h2><p>Jerome sets the objective. Adults can support the plan, but the goal belongs to him.</p></div><div className="goalBox"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Today I want to…"/><div className="actions"><button onClick={()=>{if(goal.trim()){setReply(`Strong choice. “${goal}” is clear enough to start. Pick the smallest first action.`);speak(`Strong choice, Jerome. ${goal}. Pick the smallest first action.`)}}}>Set my objective</button><Voice onText={setGoal}/></div>{reply&&<p className="coachReply">{reply}</p>}</div></section>
 <section className="missions"><Title step="04 — FOCUSED WORK" title="Choose three meaningful missions" text="Short blocks, visible finish lines, and real-world reasons for the work."/><div className="missionGrid">{missions.map((m,i)=><article key={m[1]}><span>{m[0]}</span><small>{["CORE · 20 MIN","BUILD · 30 MIN","VOICE · 25 MIN"][i]}</small><h3>{m[1]}</h3><p>{m[2]}</p><div className="actions"><button onClick={()=>document.getElementById(m[3])?.scrollIntoView({behavior:"smooth"})}>Open</button><button className="soft" onClick={()=>toggle(`m${i}`)}>{done.includes(`m${i}`)?"✓ Complete":"Mark complete"}</button></div></article>)}</div></section>
 <Math speak={speak}/><Writing/><section className="finish"><p className="eyebrow">END-OF-DAY CHECK</p><h2>Progress counts—even when the plan changes.</h2><p>Name one thing you completed, understood, handled, or tried today.</p><input placeholder="One win from today…" onKeyDown={e=>{if(e.key==="Enter"&&e.currentTarget.value.trim()){setWins([...wins,e.currentTarget.value]);e.currentTarget.value=""}}}/>{wins.map((w,i)=><div className="win" key={i}>✓ {w}</div>)}</section></>}
 {view==="planner"&&<WorkPlanner/>} {view==="agenda"&&<Jerome90DayPlan speak={speak}/>} {view==="recap"&&<SubjectRecap/>} {view==="portfolio"&&<Portfolio/>} {view==="mentors"&&<MentorCenter/>} {view==="future"&&<Careers done={done} toggle={toggle}/>} {view==="driving"&&<DrivingBasics speak={speak}/>} {view==="digital"&&<FamilyDigitalLab speak={speak}/>} {view==="money"&&<MoneyLab/>} {view==="learning"&&<><LearningLab/><WritingCoach/></>} {view==="rights"&&<CivilRightsLab speak={speak}/>} {view==="science"&&<ScienceLab/>} {view==="thesis"&&<ThesisLab/>} {view==="speaking"&&<SpeakingLab/>} {view==="appliedMath"&&<AppliedMath/>} {view==="lessons"&&<LessonSupport/>} {view==="independence"&&<IndependenceLab/>} {view==="leadership"&&<LeadershipTracker/>} {view==="badges"&&<SkillBadges/>} {view==="wellness"&&<WellnessPlan/>} {view==="library"&&<VideoLibrary/>} {view==="support"&&<Support speak={speak}/>}<footer><b>Jerome’s Next Level</b><p>A private, strengths-based space for learning, self-advocacy, and teen independence.</p></footer></main>
}
function Title({step,title,text}:{step:string;title:string;text:string}){return <div className="title"><p className="eyebrow">{step}</p><h2>{title}</h2><p>{text}</p></div>}
function LiveClock(){const [now,setNow]=useState(new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);return <div className="date liveClock"><b>{now.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</b><span>{now.toLocaleDateString([],{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</span></div>}
function LearningPortals(){return <div className="portalWrap"><div><p className="eyebrow">MY LEARNING APPS</p><h2>Open today’s classes</h2><p>Use the official sign-in pages. Your login information stays with each learning service and is never saved here.</p></div><div className="portalGrid"><a href="https://preply.com/en/login" target="_blank" rel="noopener noreferrer"><span>HOLA</span><div><small>SPANISH · LIVE TUTORING</small><h3>Preply</h3><p>Join Spanish lessons, message your tutor, and review your practice.</p><b>Open Preply ↗</b></div></a><a href="https://www.time4learning.com/pages/student-login" target="_blank" rel="noopener noreferrer"><span>T4L</span><div><small>CORE COURSEWORK</small><h3>Time4Learning</h3><p>Continue assigned math, language arts, science, and social studies.</p><b>Open student login ↗</b></div></a></div></div>}
function Voice({onText,checkOnly=false}:{onText:(x:string)=>void;checkOnly?:boolean}){const[listening,setListening]=useState(false),[status,setStatus]=useState("");const start=()=>{const w=window as any,R=w.SpeechRecognition||w.webkitSpeechRecognition;if(!window.isSecureContext){setStatus("Use the secure site address or type instead.");return}if(!R){setStatus("Talk-to-text is not supported here. Typing still works.");return}try{const r=new R();r.lang="en-US";r.interimResults=false;r.maxAlternatives=1;r.onstart=()=>{setListening(true);setStatus("Listening…")};r.onresult=(e:any)=>{const text=e.results[0][0].transcript;onText(text);setStatus(checkOnly?`Microphone ready: “${text}”`:`Added: “${text}”`)};r.onerror=(e:any)=>setStatus(e.error==="not-allowed"?"Microphone permission is blocked. Allow it in browser settings or type instead.":"I couldn’t hear that. Retry or type instead.");r.onend=()=>setListening(false);r.start()}catch{setStatus("The microphone could not start. Typing still works.")}};return <span className="voiceControl"><button type="button" className={listening?"ghost listening":"ghost"} onClick={start}>{listening?"🎙 Listening…":checkOnly?"🎤 Check microphone":"🎙 Talk instead"}</button>{status&&<small role="status">{status}</small>}</span>}
function Math({speak}:{speak:(x:string)=>void}){const s=["Read: 3x + 5 = 20","Undo plus 5: 20 minus 5 equals 15","Divide by 3: x equals 5"],[n,setN]=useState(0);return <section className="math" id="math"><Title step="MATH SUPPORT" title="See the pathway—not just the answer" text="Reveal one move at a time to reduce overload in multi-step problems."/><div className="mathCard"><div><small>ALGEBRA PATHWAY</small><h3>Solve: 3x + 5 = 20</h3>{s.slice(0,n+1).map((x,i)=><p className="mathStep" key={x}><b>{i+1}</b>{x}</p>)}<div className="actions"><button disabled={n===2} onClick={()=>setN(globalThis.Math.min(2,n+1))}>Show next step</button><button className="ghost" onClick={()=>speak(s.slice(0,n+1).join(". "))}>🔊 Hear steps</button></div></div><aside><b>Remember</b><p>Only solve the step you can see. Writing each move is a strategy, not a weakness.</p></aside></div></section>}
function Writing(){const [a,setA]=useState(""),[b,setB]=useState("");return <section className="writing" id="writing"><Title step="WRITING SUPPORT" title="Build an argument like a structure" text="Separate the idea from the proof so the paragraph is easier to organize."/><div className="writingGrid"><label><b>1. My claim</b><small>What do I believe or notice?</small><textarea value={a} onChange={e=>setA(e.target.value)}/></label><label><b>2. My evidence</b><small>What fact, quote, or example supports it?</small><textarea value={b} onChange={e=>setB(e.target.value)}/></label><article><b>3. My reasoning</b><p>{a&&b?`My evidence supports “${a}” because it shows ${b.toLowerCase()}.`:"Complete the claim and evidence boxes to create a reasoning starter."}</p></article></div></section>}
function Future({done,toggle}:{done:string[];toggle:(x:string)=>void}){const jobs=[["🚒","Fire & Emergency Services","Safety, teamwork, fitness, calm communication"],["⌨","Cybersecurity / IT","Networks, privacy, threats, problem solving"],["▣","App Development","Plan, code, test, explain, improve"],["⌂","Construction / CAD","Measurement, design, tools, safety"],["◫","Technical Teaching","Turn knowledge into clear instructions"]];return <section className="page"><Title step="FUTURE LAB" title="Practice adulthood before adulthood arrives" text="Real skills connected to Jerome’s interests, independence, and possible career paths."/><div className="careerGrid">{jobs.map((x,i)=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><button onClick={()=>toggle(`c${i}`)}>{done.includes(`c${i}`)?"✓ Explored":"Explore path"}</button></article>)}</div><div className="lifeGrid"><article><h3>Money Simulator</h3><p>Monthly take-home pay: <b>$2,400</b></p>{[["Housing",900],["Food",350],["Transportation",180],["Savings",240],["Other",300]].map(x=><div className="budget" key={x[0]}><span>{x[0]}</span><i style={{width:`${+x[1]/24}%`}}/><b>${x[1]}</b></div>)}<strong>$430 remains</strong></article><article><h3>Workplace Practice</h3><p>A supervisor gives an unclear instruction. Strong responses:</p><button>“Could you show me what finished should look like?”</button><button>“What is the first priority and when is it due?”</button><small>Both are professional self-advocacy.</small></article></div></section>}
function Support({speak}:{speak:(x:string)=>void}){const scripts=[["I need clarification","I understand part of the instruction, but I need the next step explained another way."],["I need a pause","I am getting overloaded. I need a short break, and then I can return."],["I disagree respectfully","I see it differently. Can I explain my reasoning before we decide?"],["Help me prioritize","I have several tasks. Which one needs to be finished first?"]];return <section className="page"><Title step="SUPPORT TOOLS" title="Self-advocacy is an independence skill" text="Use clear scripts when finding the words takes extra energy."/><div className="scriptGrid">{scripts.map(x=><article key={x[0]}><h3>{x[0]}</h3><blockquote>“{x[1]}”</blockquote><button onClick={()=>speak(x[1])}>🔊 Practice aloud</button></article>)}</div><div className="reset"><div><p className="eyebrow">REGULATION PLAN</p><h2>When the system feels overloaded</h2></div><ol>{[["Notice","Name what your body or brain is doing."],["Reduce","Lower noise, light, choices, or conversation."],["Reset","Move, breathe, use music, or take quiet time."],["Return","Choose one small next action."]].map(x=><li key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></li>)}</ol></div></section>}
