"use client";
import {useEffect,useState} from "react";

const resources=[
 {subject:"History & Justice",title:"Civil Rights Movement Primary Sources",source:"Library of Congress",url:"https://www.loc.gov/classroom-materials/civil-rights-movement/",type:"Primary sources",why:"Study photographs, documents, interviews, and newspapers instead of relying only on a summary.",before:"Choose one item. Record its creator, date, and what you notice first.",after:"What does this source reveal—and what can it not tell us by itself?"},
 {subject:"History & Justice",title:"Brown v. Board of Education",source:"National Archives",url:"https://www.archives.gov/education/lessons/brown-v-board",type:"Document lesson",why:"Read evidence from a landmark case and connect constitutional principles to lived experience.",before:"Define segregation and the 14th Amendment in your own words.",after:"Which piece of evidence best supports the Court’s decision? Explain why."},
 {subject:"Civil Law & Rights",title:"Know My Rights",source:"New York State Attorney General",url:"https://ag.ny.gov/i-want/know-my-rights",type:"Official rights guides",why:"Learn how New York law protects students, workers, tenants, consumers, and people facing discrimination.",before:"Choose one setting—school, work, housing, or public life—and write what you think the law protects.",after:"Name one right, one responsibility, and one trusted person who can help you use the information safely."},
 {subject:"Civil Law & Rights",title:"Police Encounters: Know Your Rights",source:"NYC Civilian Complaint Review Board",url:"https://www.nyc.gov/site/ccrb/complaints/file-a-complaint/know-your-rights.page",type:"Official NYC guide",why:"Learn the levels of police encounters, useful calm questions, and how to document concerns after reaching safety.",before:"Practice saying: Am I free to leave? and I do not consent to a search.",after:"Explain why knowing a right does not mean physically resisting an officer."},
 {subject:"Civil Law & Rights",title:"Right to Know Act",source:"NYC Civilian Complaint Review Board",url:"https://www.nyc.gov/site/ccrb/complaints/file-a-complaint/right-to-know-act.page",type:"Official NYC law guide",why:"Understand when officers must identify themselves and explain that a person may refuse a consent search.",before:"Write the difference between giving consent and obeying a lawful command.",after:"What officer information could you calmly request and record later?"},
 {subject:"Writing & Research",title:"Writing a Strong Thesis Statement",source:"Purdue OWL",url:"https://owl.purdue.edu/owl/general_writing/the_writing_process/thesis_statement_tips.html",type:"Writing guide",why:"Compare your working thesis to clear academic criteria before drafting the essay.",before:"Bring your research question and current one-sentence answer.",after:"Rewrite your thesis so it is specific and can be supported with evidence."},
 {subject:"Writing & Research",title:"Using Research and Evidence",source:"Purdue OWL",url:"https://owl.purdue.edu/owl/general_writing/academic_writing/establishing_arguments/research_and_evidence.html",type:"Source guide",why:"Learn how to judge credibility and connect research to a claim.",before:"Choose one source you plan to use and identify its author.",after:"List two reasons the source is credible—or two reasons it needs verification."},
 {subject:"Math",title:"Algebra 1 Practice",source:"Khan Academy",url:"https://www.khanacademy.org/math",type:"Guided practice",why:"Reinforce equations, functions, graphing, and other Algebra I skills in short sessions.",before:"Choose the skill named by your tutor or today’s Applied Math challenge.",after:"Write the step that became clearer and one question to bring to tutoring."},
 {subject:"Careers",title:"Occupational Outlook Handbook",source:"U.S. Bureau of Labor Statistics",url:"https://www.bls.gov/ooh/",type:"Career data",why:"Compare actual duties, education, pay, work conditions, and projected job growth.",before:"Choose one career and predict its training requirement and work environment.",after:"Record one benefit, one risk, one training step, and one action Jerome can take now."},
 {subject:"Careers",title:"Cybersecurity Learning Resources",source:"NIST NICE",url:"https://www.nist.gov/itl/applied-cybersecurity/nice/resources/online-learning-content",type:"Training directory",why:"Explore free and low-cost cybersecurity learning from a federal workforce-education source.",before:"Choose one beginner resource and write the skill it teaches.",after:"How could this skill connect to Jerome’s app project or an entry-level role?"},
 {subject:"Safety & Service",title:"Teen Emergency Preparedness",source:"Ready.gov",url:"https://www.ready.gov/kids/teens",type:"Preparedness",why:"Connect firefighter interest and family responsibility to real emergency planning.",before:"List the emergencies most likely to affect home, travel, or the community.",after:"Name one improvement to the family plan, communication list, or emergency kit."},
 {subject:"Safety & Service",title:"Young Workers in Construction",source:"OSHA",url:"https://www.osha.gov/young-workers-construction",type:"Workplace safety",why:"Learn age restrictions, job hazards, worker rights, and required safety training before hands-on work.",before:"Predict three hazards a young construction worker might face.",after:"Which hazard needs the strongest control, and what should the employer provide?"}
];
const subjects=["All",...Array.from(new Set(resources.map(x=>x.subject)))];

export function LessonSupport(){const[filter,setFilter]=useState("All"),[done,setDone]=useState<string[]>([]),[note,setNote]=useState("");useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("jerome-lesson-resources")||"[]"))}catch{}},[]);const toggle=(x:string)=>setDone(d=>{const next=d.includes(x)?d.filter(y=>y!==x):[...d,x];localStorage.setItem("jerome-lesson-resources",JSON.stringify(next));return next});const shown=filter==="All"?resources:resources.filter(x=>x.subject===filter);return <section className="lessonSupport"><div className="supportHero"><div><p className="eyebrow">LESSON-LINKED SUPPORT</p><h1>Know why you are opening the link.</h1><p>Every resource has a purpose, a before-class task, and a recap question. Jerome can prepare, learn, explain, and leave evidence of what he understood.</p></div><div className="learnCycle">{["PREPARE","OPEN","EXPLAIN","SAVE"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div></div>
 <div className="supportBody"><section className="thisWeek"><div><p className="eyebrow">THIS WEEK’S RESOURCE ROUTINE</p><h2>One strong resource is enough for one lesson.</h2></div><ol><li><b>Before class</b><span>Read the preparation task and gather a notebook, question, and assigned material.</span></li><li><b>During</b><span>Pause to write one fact, one question, and one connection.</span></li><li><b>After</b><span>Answer the recap prompt in two to four sentences or record it aloud.</span></li><li><b>Evidence</b><span>Save notes, a photo, completed work, or the link in Jerome’s portfolio.</span></li></ol></section>
 <div className="resourceFilters">{subjects.map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="resourceGrid">{shown.map(r=><article key={r.title} className={done.includes(r.title)?"completed":""}><div className="resourceMeta"><span>{r.subject}</span><small>{r.type}</small></div><h3>{r.title}</h3><p className="sourceName">{r.source}</p><p>{r.why}</p><div className="lessonSteps"><p><b>Before opening</b>{r.before}</p><p><b>Recap after</b>{r.after}</p></div><div className="resourceActions"><a href={r.url} target="_blank" rel="noopener noreferrer">Open trusted resource ↗</a><button onClick={()=>toggle(r.title)}>{done.includes(r.title)?"✓ Used in a lesson":"Mark used"}</button></div></article>)}</div>
 <section className="travelLearning"><div><p className="eyebrow">LOW-SCREEN / CAR-TIME OPTION</p><h2>Turn travel into discussion—not more scrolling.</h2><p>Open or download the assigned material before leaving. During travel, listen to approved audio or discuss: What happened? Whose perspective did we hear? What evidence stood out? What question should we research later?</p></div><label><b>Question to carry into the lesson</b><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="I want to find out…"/></label></section>
 <section className="resourceRecord"><div><b>{done.length}</b><span>resources used in lessons</span></div><p>Completion means Jerome used the resource for a real lesson and answered its recap prompt—not simply opened the page.</p></section></div></section>}
