"use client";
import {useMemo,useState} from "react";

const pathways=[
 {name:"Math Tutor",person:"Tutor to be confirmed",focus:["Algebra I foundations","Equations and inequalities","Functions and graphing","Real-world problem solving"],evidence:"Completed practice, tutor note, corrected problem, or skill check"},
 {name:"Counseling / SEL",person:"Counselor / Ms. Flanagan as assigned",focus:["Stress and emotional regulation","Self-advocacy","Thinking before speaking","Safe coping and communication"],evidence:"Student reflection, coping plan update, or provider progress note"},
 {name:"Occupational Therapy",person:"OT provider as assigned",focus:["Hygiene and personal routines","Executive functioning","Sensory regulation","Planning and daily independence"],evidence:"Routine checklist, strategy trial, demonstration, or provider note"},
 {name:"Coding & App Development",person:"GoCoding / Newman mentorship",focus:["Newman app milestone","Coding foundations","Testing and debugging","Explaining code to another learner"],evidence:"Screenshot, code milestone, demo, mentor feedback, or project link"},
 {name:"Cybersecurity",person:"Richard Pruitt",focus:["Career awareness","Networks and privacy","Threats and safe practices","Internship and training preparation"],evidence:"Career interview, lesson reflection, certificate, project, or mentor feedback"},
 {name:"Dojo Leadership",person:"Master Pascal",focus:["Junior-instructor preparation","Following professional expectations","Communication under pressure","One supervised responsibility"],evidence:"Demonstration, supervisor feedback, self-evaluation, or responsibility log"}
];

export function MentorCenter(){const[index,setIndex]=useState(0),[date,setDate]=useState(""),[goal,setGoal]=useState(""),[question,setQuestion]=useState(""),[learned,setLearned]=useState(""),[next,setNext]=useState(""),[status,setStatus]=useState("completed"),[reason,setReason]=useState("");const p=pathways[index];const summary=useMemo(()=>`${p.name} — ${date||"date not entered"}\nProvider/mentor: ${p.person}\nStatus: ${status}\nSession goal: ${goal||"Not entered"}\nQuestion brought to session: ${question||"Not entered"}\nWhat Jerome learned/practiced: ${learned||"Not entered"}\nCarry-forward action: ${next||"Not entered"}${status!=="completed"?`\nMissed/rescheduled reason and follow-up: ${reason||"Not entered"}`:""}`,[p,date,status,goal,question,learned,next,reason]);return <section className="mentorCenter"><div className="mentorHero"><div><p className="eyebrow">MENTOR, TUTOR & SERVICES PREP</p><h1>Arrive with a goal. Leave with a next step.</h1><p>This student-facing center helps Jerome prepare, participate, reflect, and save evidence. Official attendance, service compliance, and quarterly reporting stay in the private instructor hub.</p></div><aside><b>LEARN → PRACTICE → EXPLAIN → CARRY FORWARD</b><p>Every support session should connect to an objective Jerome understands and a next action he can find later.</p></aside></div>
 <div className="mentorBody"><section><div className="pathTabs">{pathways.map((x,i)=><button key={x.name} className={index===i?"active":""} onClick={()=>setIndex(i)}><b>{x.name}</b><span>{x.person}</span></button>)}</div><div className="pathOverview"><div><p className="eyebrow">CURRENT PATHWAY</p><h2>{p.name}</h2><p>{p.person}</p></div><div><b>Focus areas</b>{p.focus.map(x=><span key={x}>✓ {x}</span>)}</div><aside><b>Useful evidence</b><p>{p.evidence}</p></aside></div></section>
 <section><Heading n="01" title="Prepare before the session" text="Five focused minutes can make a support session more useful."/><div className="prepGrid"><label><b>Session date</b><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><b>Today I want help with…</b><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="One clear skill, problem, or situation…"/></label><label><b>The question I want to ask is…</b><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Could you show me…?"/></label></div><div className="bringList">{["Charged device","Assigned work or project","Notes from the last session","One question","Needed login or materials","Water / regulation support"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></section>
 <section><Heading n="02" title="Complete the session check-out" text="Capture the learning while it is still fresh."/><div className="checkoutGrid"><label><b>What did I learn or practice?</b><textarea value={learned} onChange={e=>setLearned(e.target.value)}/></label><label><b>What is the next action—and when?</b><textarea value={next} onChange={e=>setNext(e.target.value)} placeholder="Before the next session, I will…"/></label></div><div className="understanding">{["I can do this independently","I can do it with one reminder","I need another example","I need the instruction explained differently"].map(x=><label key={x}><input type="radio" name="understanding"/> {x}</label>)}</div></section>
 <section><Heading n="03" title="Handle missed, canceled, or unavailable support" text="A missed session should create a follow-up action—not disappear from the plan."/><div className="statusRow">{[["completed","Session completed"],["rescheduled","Rescheduled"],["provider-canceled","Provider unavailable"],["student-missed","Student missed"]].map(x=><button key={x[0]} className={status===x[0]?"active":""} onClick={()=>setStatus(x[0])}>{x[1]}</button>)}</div>{status!=="completed"&&<div className="missedPlan"><label><b>What happened?</b><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div>{["New date requested or confirmed","Parent/instructor informed","Make-up work identified","Official admin record updated"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></div>}</section>
 <section><Heading n="04" title="Create a carry-forward record" text="Copy this into the Work Planner, save it as a PDF, or use it when uploading evidence to the Portfolio."/><pre className="mentorSummary">{summary}</pre><div className="mentorActions"><button onClick={()=>navigator.clipboard.writeText(summary)}>Copy session summary</button><button onClick={()=>window.print()}>Print / save as PDF</button></div></section>
 <section><Heading n="05" title="Quarterly mentor evidence check" text="Use this concise check before the instructor completes the formal quarterly report."/><div className="quarterEvidence">{["At least one specific objective was addressed","Jerome can describe what he practiced","Provider or mentor feedback was collected","A work sample, photo, project, or reflection exists","The next milestone is identified","Missed sessions have a documented follow-up"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></section></div></section>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="mentorHeading"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
