"use client";
import {useEffect,useState} from "react";
type Step={text:string;done:boolean};
export function WorkPlanner(){
 const [task,setTask]=useState(""),[draft,setDraft]=useState(""),[steps,setSteps]=useState<Step[]>(()=>{try{return JSON.parse(localStorage.getItem("jerome-work-steps")||"[]")}catch{return[]}}),[seconds,setSeconds]=useState(15*60),[running,setRunning]=useState(false),[breakMode,setBreakMode]=useState(false);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);if("speechSynthesis" in window)window.speechSynthesis.speak(new SpeechSynthesisUtterance("Focus block complete. Check your work and choose your next step."));return 0}return s-1}),1000);return()=>clearInterval(id)},[running]);
 const save=(x:Step[])=>{setSteps(x);localStorage.setItem("jerome-work-steps",JSON.stringify(x))},add=()=>{if(!draft.trim())return;save([...steps,{text:draft.trim(),done:false}]);setDraft("")},active=steps.findIndex(s=>!s.done),reset=(mins:number)=>{setRunning(false);setBreakMode(mins===5);setSeconds(mins*60)};
 return <section className="page planner"><div className="title"><p className="eyebrow">EXECUTIVE-FUNCTION CENTER</p><h2>Make the next step visible</h2><p>Plan one assignment, reduce it into manageable pieces, focus for a clear amount of time, and take breaks on purpose.</p></div><div className="plannerHero"><div><label>Assignment or goal<input value={task} onChange={e=>setTask(e.target.value)} placeholder="Example: Complete my history source analysis"/></label><p>{task?<>Current goal: <b>{task}</b></>:"Name one assignment—not the whole week."}</p></div><div className={breakMode?"timer breakTimer":"timer"}><small>{breakMode?"PLANNED RESET":"FOCUS TIMER"}</small><b>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</b><div><button onClick={()=>setRunning(!running)}>{running?"Pause":"Start"}</button><button onClick={()=>reset(15)}>15 min</button><button onClick={()=>reset(25)}>25 min</button><button onClick={()=>reset(5)}>5 min break</button></div></div></div><div className="stepBuilder"><h3>Break it into steps</h3><p>Each step should describe one action that can be clearly finished.</p><div><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Example: Open the Library of Congress source"/><button onClick={add}>Add step</button></div></div><div className="kanban"><section><h3>NOW</h3>{active>=0?<StepCard step={steps[active]} onDone={()=>save(steps.map((s,i)=>i===active?{...s,done:true}:s))}/>:<p className="emptyStep">Add a step or celebrate—everything is complete.</p>}</section><section><h3>NEXT</h3>{steps.filter((s,i)=>!s.done&&i!==active).slice(0,1).map((s,i)=><StepCard key={i} step={s}/>)}</section><section><h3>LATER</h3>{steps.filter((s,i)=>!s.done&&i!==active).slice(1).map((s,i)=><StepCard key={i} step={s}/>)}</section></div><div className="plannerSupport"><article><h3>If I feel stuck</h3>{["Read the direction aloud","Ask: What does finished look like?","Circle the action word","Do only the first visible step","Use a model or worked example"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article><article><h3>If I feel overloaded</h3>{["Lower noise, light, and notifications","Use the five-minute planned break","Move, stretch, or practice a karate pattern","Say: I need clarification or a short pause","Return to one step—not the entire assignment"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</article><article><h3>End-of-task reflection</h3><textarea placeholder="What helped me begin, continue, or finish?"/><button onClick={()=>{save([]);setTask("");reset(15)}}>Finish and clear plan</button></article></div></section>
}
function StepCard({step,onDone}:{step:Step;onDone?:()=>void}){return <article className="stepCard"><span>○</span><b>{step.text}</b>{onDone&&<button onClick={onDone}>Mark finished</button>}</article>}
