"use client";
import {useState} from "react";
import {SmartResponse} from "./smart-response";
const subjects=["English & Literature","Mathematics","Science","History & Geography","Spanish","Coding & Cybersecurity","Tuttle Twins / Civics","Financial Literacy","Music & Production","Karate & Health","Safety & Independent Living","Art & Media","Community Service"];
type Entry={date:string;subject:string;title:string;minutes:number;completed:boolean;strength:string;support:string};
export function Portfolio(){
 const [entries,setEntries]=useState<Entry[]>(()=>{try{return JSON.parse(localStorage.getItem("jerome-portfolio")||"[]")}catch{return[]}}),[subject,setSubject]=useState(subjects[0]),[title,setTitle]=useState(""),[minutes,setMinutes]=useState(30),[strength,setStrength]=useState(""),[support,setSupport]=useState("");
 const save=(next:Entry[])=>{setEntries(next);localStorage.setItem("jerome-portfolio",JSON.stringify(next))},add=()=>{if(!title.trim())return;save([{date:new Date().toISOString().slice(0,10),subject,title:title.trim(),minutes,completed:true,strength,support},...entries]);setTitle("");setStrength("");setSupport("")};
 const total=entries.reduce((n,e)=>n+e.minutes,0),week=entries.filter(e=>Date.now()-new Date(`${e.date}T12:00:00`).getTime()<7*86400000),weekMinutes=week.reduce((n,e)=>n+e.minutes,0),active=[...new Set(week.map(e=>e.subject))];
 return <section className="page portfolio"><div className="title"><p className="eyebrow">PORTFOLIO & WEEKLY PROGRESS</p><h2>Turn completed work into visible progress</h2><p>Record assignments, instructional time, strengths, and supports. Entries save privately on this device.</p></div><div className="portfolioStats"><article><small>THIS WEEK</small><b>{weekMinutes}</b><span>instructional minutes</span></article><article><small>SUBJECTS PRACTICED</small><b>{active.length}</b><span>during the last 7 days</span></article><article><small>PORTFOLIO ITEMS</small><b>{entries.length}</b><span>{total} total minutes recorded</span></article></div><div className="portfolioGrid"><article className="addWork"><h3>Add completed work</h3><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Assignment, lesson, project, or activity<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Example: Spanish lesson with Roberto"/></label><label>Instructional minutes<input type="number" min="5" step="5" value={minutes} onChange={e=>setMinutes(+e.target.value)}/></label><label>What strength did I demonstrate?<SmartResponse value={strength} onChange={setStrength} mode="explain" placeholder="I demonstrated…"/></label><label>What support or next step would help?<SmartResponse value={support} onChange={setSupport} mode="analyze" placeholder="My next step is…"/></label><button className="saveWork" onClick={add}>Save to my portfolio</button></article><article className="weeklySummary"><div className="summaryHead"><div><p className="eyebrow">WEEKLY SUMMARY</p><h3>Jerome’s learning evidence</h3></div><button onClick={()=>window.print()}>Print summary</button></div><p><b>Subjects practiced:</b> {active.length?active.join(", "):"Add completed work to begin the summary."}</p><p><b>Work completed:</b> {week.length} recorded learning activities.</p><p><b>Instructional time:</b> {weekMinutes} minutes during the last seven days.</p><h4>Recent portfolio entries</h4>{entries.length?entries.slice(0,8).map((e,i)=><div className="portfolioEntry" key={`${e.date}-${i}`}><div><small>{e.date} · {e.subject}</small><b>{e.title}</b><span>{e.minutes} minutes</span>{e.strength&&<p><strong>Strength:</strong> {e.strength}</p>}{e.support&&<p><strong>Next support:</strong> {e.support}</p>}</div><button aria-label={`Remove ${e.title}`} onClick={()=>save(entries.filter((_,n)=>n!==i))}>×</button></div>):<p className="emptyPortfolio">No portfolio entries yet. Add Jerome’s first completed activity.</p>}</article></div></section>
}
