"use client";
import {useMemo,useState} from "react";
import {AssignedLabs} from "./assigned-labs";

type Trial={name:string,value:string};
const challenges=[
 {name:"Forces & Motion",question:"How does changing one feature affect distance, speed, force, or stability?",ideas:"Ramp, vehicle, bridge, tower, parachute, or protective structure"},
 {name:"Building Science",question:"Which material or design performs best under a controlled test?",ideas:"Insulation, load strength, water resistance, airflow, heat transfer, or structural stability"},
 {name:"Fire Science",question:"How do prevention, materials, building design, and emergency planning affect safety?",ideas:"Use research, models, and non-flame demonstrations unless a qualified adult directs otherwise"},
 {name:"MEL / Co-op Lab",question:"What does the experiment show, and does the evidence support the hypothesis?",ideas:"MEL Science, Earth & Environment, medical simulation, chemistry, physics, or co-op investigation"}
];

export function ScienceLab(){const[challenge,setChallenge]=useState(0),[question,setQuestion]=useState(""),[hypothesis,setHypothesis]=useState(""),[independent,setIndependent]=useState(""),[dependent,setDependent]=useState(""),[controls,setControls]=useState(""),[trials,setTrials]=useState<Trial[]>([{name:"Trial 1",value:""},{name:"Trial 2",value:""},{name:"Trial 3",value:""}]),[unit,setUnit]=useState("seconds"),[analysis,setAnalysis]=useState(""),[conclusion,setConclusion]=useState("");const values=trials.map(x=>Number(x.value)||0),max=Math.max(...values,1),average=values.some(Boolean)?values.reduce((a,b)=>a+b,0)/values.filter(Boolean).length:0;const update=(i:number,k:keyof Trial,v:string)=>setTrials(t=>t.map((x,n)=>n===i?{...x,[k]:v}:x));return <section className="scienceLab"><div className="scienceHero"><div><p className="eyebrow">SCIENCE, ENGINEERING & PROJECT LAB</p><h1>Build it. Test it. Improve it.</h1><p>Jerome can use MEL Science, co-op labs, CrunchLabs, LEGO, library materials, models, or supervised tools to investigate a real question and produce measurable evidence.</p></div><aside><b>Adult supervision required</b><p>Do not independently use heat, flame, electricity, chemicals, power tools, sharp tools, heavy materials, or construction equipment. Follow the kit, instructor, and safety-equipment directions.</p></aside></div><div className="scienceBody"><AssignedLabs/>
 <section><Heading n="01" title="Choose the investigation" text="Change one main factor at a time so the results can be compared."/><div className="challengeGrid">{challenges.map((x,i)=><button key={x.name} className={challenge===i?"active":""} onClick={()=>setChallenge(i)}><b>{x.name}</b><span>{x.question}</span><small>{x.ideas}</small></button>)}</div></section>
 <section><Heading n="02" title="Plan before building" text="A safe, fair test begins with a specific question and known variables."/><div className="scienceFields"><Field label="My testable question" value={question} set={setQuestion} hint={challenges[challenge].question}/><Field label="My hypothesis" value={hypothesis} set={setHypothesis} hint="If I change ___, then ___ will happen because…"/><Field label="Independent variable" value={independent} set={setIndependent} hint="The one factor I will intentionally change…"/><Field label="Dependent variable" value={dependent} set={setDependent} hint="What I will measure or observe…"/><Field label="Controlled factors" value={controls} set={setControls} hint="What must stay the same for every trial…"/></div><div className="safetyCheck">{["Adult approved the plan","Materials checked","Eye/hand protection ready if needed","Workspace is clear","Emergency or cleanup steps known","No unapproved heat, chemicals, electricity, or tools"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></section>
 <section><Heading n="03" title="Build, test, and collect data" text="Record what actually happened—even when it does not match the prediction."/><div className="dataControls"><label><b>Measurement unit</b><select value={unit} onChange={e=>setUnit(e.target.value)}>{["seconds","centimeters","meters","grams","degrees","items held","other units"].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>setTrials([...trials,{name:`Trial ${trials.length+1}`,value:""}])}>＋ Add trial</button></div><div className="dataTable">{trials.map((x,i)=><div key={i}><input value={x.name} onChange={e=>update(i,"name",e.target.value)} aria-label={`Trial ${i+1} name`}/><input type="number" value={x.value} onChange={e=>update(i,"value",e.target.value)} aria-label={`${x.name} result`}/><span>{unit}</span>{trials.length>3&&<button onClick={()=>setTrials(trials.filter((_,n)=>n!==i))}>×</button>}</div>)}</div><p className="average">Average of recorded results: <b>{average.toFixed(2)} {unit}</b></p><div className="scienceChart" aria-label="Bar graph of experiment results">{trials.map((x,i)=><div key={i}><span>{x.value||"0"}</span><i style={{height:`${Math.max(4,values[i]/max*150)}px`}}/><b>{x.name}</b></div>)}</div></section>
 <section><Heading n="04" title="Analyze, conclude, and improve" text="Explain patterns, limits, errors, and what the next design should change."/><div className="analysisGrid"><Field label="What pattern do the data show?" value={analysis} set={setAnalysis} hint="The strongest, fastest, safest, or most consistent result was…"/><Field label="Conclusion" value={conclusion} set={setConclusion} hint="The evidence did or did not support my hypothesis because…"/><Field label="Possible error or limitation" value="" set={()=>{}} hint="What may have affected the result?"/><Field label="Build-test-improve decision" value="" set={()=>{}} hint="The next version will change… because…"/></div></section>
 <section><Heading n="05" title="Prepare the display board or project presentation" text="Use this order for a science board, oral presentation, app demo, or portfolio record."/><div className="boardMap">{[["Question","What did I investigate?"],["Background","What science helped me plan?"],["Hypothesis","What did I predict and why?"],["Materials & safety","What did I use, and how was risk controlled?"],["Method","What steps made the test fair?"],["Data & graph","What measurements did I collect?"],["Analysis","What patterns or differences appeared?"],["Conclusion","Was the hypothesis supported?"],["Improve","What would I change next time?"]].map((x,i)=><article key={x[0]}><span>{i+1}</span><b>{x[0]}</b><p>{x[1]}</p></article>)}</div><div className="scienceActions"><button onClick={()=>window.print()}>Print / save project record</button><button onClick={()=>navigator.clipboard.writeText(`Question: ${question}\nHypothesis: ${hypothesis}\nIndependent variable: ${independent}\nDependent variable: ${dependent}\nControls: ${controls}\nAnalysis: ${analysis}\nConclusion: ${conclusion}`)}>Copy project summary</button></div></section>
 </div></section>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="scienceHeading"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Field({label,value,set,hint}:{label:string;value:string;set:(x:string)=>void;hint:string}){const[local,setLocal]=useState(value);return <label><b>{label}</b><small>{hint}</small><textarea value={local} onChange={e=>{setLocal(e.target.value);set(e.target.value)}}/></label>}
