"use client";
import {useEffect,useState} from "react";

const tracks=[
 {icon:"🎓",title:"MasterClass Enrichment",goal:"Complete one course and turn the learning into a usable product or presentation.",steps:["Choose a course connected to writing, film, business, leadership, or creativity","Complete assigned lessons and notes","Apply one technique in a project","Explain the most useful lesson","Save the completion record and final product"],proof:"Course record + notes + applied project + reflection"},
 {icon:"📱",title:"Luman & Newman Apps",goal:"Move from idea to wireframe, prototype, working function, testing, and demonstration.",steps:["Define the user and problem","Create Luman wireframes or a prototype","Build and test one Newman function","Record bugs and improvements","Demonstrate or pitch progress"],proof:"Wireframe + screenshot/code + test notes + demo or pitch"},
 {icon:"🔥",title:"Fire & Emergency Readiness",goal:"Build a firefighter foundation through prevention, preparedness, building science, response, and fitness.",steps:["Review fire prevention and home safety","Create or inspect an emergency plan","Study basic building science","Practice safe emergency communication","Complete firefighter-oriented fitness or a demonstration"],proof:"Safety plan + lesson notes + demonstration + fitness log"},
 {icon:"🛡",title:"Cybersecurity",goal:"Develop foundational knowledge and explain how people, devices, networks, and information are protected.",steps:["Complete an approved lesson or mentor session","Identify a real threat or vulnerability","Practice a safe protection strategy","Connect the skill to a career role","Teach back the concept"],proof:"Lesson record + project or scenario + mentor feedback"},
 {icon:"⚖",title:"Civil Law & Rights",goal:"Understand constitutional and civil rights, practice safe self-advocacy, and know when to involve a trusted adult or qualified lawyer.",steps:["Explain civil law, criminal law, rights, and responsibilities","Practice a calm police-encounter and search-consent script","Compare rights at school, work, home, and in public","Create a factual incident record without assumptions","Complete a mock case and trusted-help map"],proof:"Vocabulary check + scenario responses + incident record + mock-case portfolio"},
 {icon:"🛠",title:"Mechanics & Skilled Trades",goal:"Complete one hands-on unit involving tools, measurement, systems, repair, construction, or design.",steps:["Choose a safe supervised project","Identify tools and safety rules","Read a diagram, plan, or measurement","Complete or demonstrate the process","Evaluate the result and needed improvement"],proof:"Photos + measurements/plan + safety check + reflection"},
 {icon:"¡Hola!",title:"Spanish Communication",goal:"Use Spanish in increasingly independent listening, speaking, reading, and real-life communication.",steps:["Attend the assigned tutoring lesson","Practice target vocabulary","Complete a short listening or reading task","Use the language in a conversation","Record what to practice next"],proof:"Tutor feedback + vocabulary + speaking/reading sample"},
 {icon:"♫",title:"Piano Musicianship",goal:"Prepare and demonstrate a piece with consistent practice and musical understanding.",steps:["Choose the assigned piece or skill with Ms. Cindy","Break practice into sections","Track focused practice","Perform or record the piece","Use feedback to revise"],proof:"Practice record + performance + Ms. Cindy’s feedback"},
 {icon:"🥋",title:"Karate & Instruction",goal:"Demonstrate technique, discipline, safety, and emerging junior-instructor leadership.",steps:["Practice the assigned technique","Explain its safety purpose","Demonstrate with control","Support a warmup or supervised duty","Reflect with Master Pascal"],proof:"Demonstration + leadership log + Master Pascal’s feedback"}
];
export function SkillBadges(){const[progress,setProgress]=useState<Record<string,boolean[]>>({}),[selected,setSelected]=useState(0);useEffect(()=>{try{setProgress(JSON.parse(localStorage.getItem("jerome-skill-badges")||"{}"))}catch{}},[]);const t=tracks[selected],states=progress[t.title]||Array(5).fill(false);const toggle=(i:number)=>{const n=[...states];n[i]=!n[i];const all={...progress,[t.title]:n};setProgress(all);localStorage.setItem("jerome-skill-badges",JSON.stringify(all))};const earned=tracks.filter(x=>(progress[x.title]||[]).every(Boolean)&&(progress[x.title]||[]).length===5).length;return <section className="skillBadges"><div className="badgeHero"><div><p className="eyebrow">COURSES, CERTIFICATIONS & SKILL MILESTONES</p><h1>Attendance starts the work. Evidence completes it.</h1><p>Each pathway ends with something Jerome can demonstrate, explain, and save. These are progress badges—not official licenses or professional certifications unless an outside provider separately awards one.</p></div><aside><b>{earned}/{tracks.length}</b><span>skill pathways completed</span><i><em style={{width:`${earned/tracks.length*100}%`}}/></i></aside></div><div className="badgeBody"><section><div className="badgeTabs">{tracks.map((x,i)=>{const done=(progress[x.title]||[]).filter(Boolean).length;return <button key={x.title} className={selected===i?"active":""} onClick={()=>setSelected(i)}><span>{x.icon}</span><b>{x.title}</b><small>{done}/5 milestones</small></button>})}</div></section><section className="badgePath"><div className="badgeTitle"><span>{t.icon}</span><div><p className="eyebrow">CURRENT PATHWAY</p><h2>{t.title}</h2><p>{t.goal}</p></div></div><div className="badgeSteps">{t.steps.map((x,i)=><button key={x} className={states[i]?"done":""} onClick={()=>toggle(i)}><span>{states[i]?"✓":i+1}</span><b>{x}</b></button>)}</div><aside><b>Completion evidence</b><p>{t.proof}</p></aside>{states.every(Boolean)&&<div className="earnedBadge"><b>✓ PATHWAY COMPLETE</b><span>Jerome is ready to save the evidence and explain what he learned.</span></div>}</section><section><div className="badgeHeading"><h2>Evidence cover sheet</h2><p>Complete this when a pathway is ready for the Portfolio or quarterly review.</p></div><div className="coverSheet">{["Course, program, or pathway name","Provider, instructor, or mentor","Start and completion dates","Skills practiced","Product, demonstration, or assessment","Feedback received","What Jerome can now do more independently","Where the evidence is saved"].map(x=><label key={x}><b>{x}</b><textarea/></label>)}</div><button className="printBadge" onClick={()=>window.print()}>Print / save evidence cover sheet</button></section></div></section>}
