"use client";
import {useEffect,useMemo,useState} from "react";

const prompts=[
 {label:"Justice & history",question:"How did Black leaders use writing, organizing, and public action to challenge an unjust system?",lens:"Reconstruction, Jim Crow, civil rights, or a present-day justice movement"},
 {label:"Author study",question:"How does an author use personal experience to reveal a larger truth about society?",lens:"Maya Angelou, Malcolm X, Edgar Allan Poe, or another assigned author"},
 {label:"Media literacy",question:"How can the way a story is framed influence what an audience believes?",lens:"Compare a primary source, news report, documentary scene, or social post"},
 {label:"Debate & civics",question:"When should citizens challenge a law, policy, or public institution?",lens:"Use constitutional principles, history, and more than one perspective"}
];
type Draft={topic:number;position:string;reason1:string;reason2:string;evidence:string;source:string;explain:string;counter:string;response:string};
const blank:Draft={topic:0,position:"",reason1:"",reason2:"",evidence:"",source:"",explain:"",counter:"",response:""};

export function ThesisLab(){
 const[d,setD]=useState<Draft>(blank),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const p=localStorage.getItem("jerome-thesis-lab");if(p)setD({...blank,...JSON.parse(p)})}catch{}},[]);
 const set=(k:keyof Draft,v:string|number)=>{setD(x=>({...x,[k]:v}));setSaved(false)};
 const thesis=useMemo(()=>d.position&&d.reason1&&d.reason2?`${d.position.trim()} because ${d.reason1.trim()} and ${d.reason2.trim()}.`:"Complete the position and two reasons to build a working thesis.",[d]);
 const score=[d.position,d.reason1,d.reason2,d.evidence,d.source,d.explain,d.counter,d.response].filter(x=>x.trim()).length;
 const save=()=>{localStorage.setItem("jerome-thesis-lab",JSON.stringify(d));setSaved(true)};
 return <section className="thesisLab"><div className="thesisHero"><div><p className="eyebrow">THESIS WRITING & CRITICAL THINKING</p><h1>Make a claim. Test it. Prove it.</h1><p>Strong analysis is not about guessing the “right” answer. Study evidence, consider more than one perspective, and clearly explain your conclusion.</p></div><div className="thesisProgress"><b>{score}/8</b><span>thinking steps complete</span><i><em style={{width:`${score/8*100}%`}}/></i></div></div>
 <div className="thesisBody">
  <Lab n="01" title="Choose a question worth investigating" text="Select a prompt, then narrow it with the suggested lens."><div className="promptGrid">{prompts.map((p,i)=><button key={p.label} className={d.topic===i?"chosen":""} onClick={()=>set("topic",i)}><small>{p.label}</small><b>{p.question}</b><span>Suggested lens: {p.lens}</span></button>)}</div></Lab>
  <Lab n="02" title="Build a working thesis" text="A thesis answers the question and previews the reasoning."><div className="thesisBuilder"><Field label="My position" hint="What do I believe the evidence shows?" value={d.position} change={v=>set("position",v)} placeholder="The evidence shows that…"/><Field label="Reason one" hint="What is the first strong reason?" value={d.reason1} change={v=>set("reason1",v)} placeholder="One reason is…"/><Field label="Reason two" hint="What is another different reason?" value={d.reason2} change={v=>set("reason2",v)} placeholder="Another reason is…"/><article><small>WORKING THESIS</small><p>{thesis}</p></article></div></Lab>
  <Lab n="03" title="Move from evidence to analysis" text="A quotation or fact cannot speak for itself. Explain what it proves."><div className="evidenceChain"><Field num="1" label="Evidence" hint="Write a short fact, detail, or quotation." value={d.evidence} change={v=>set("evidence",v)} placeholder="The source states or shows…"/><Field num="2" label="Source" hint="Who created it, when, and why is it trustworthy?" value={d.source} change={v=>set("source",v)} placeholder="This comes from…"/><Field num="3" label="Reasoning" hint="How does this support the thesis?" value={d.explain} change={v=>set("explain",v)} placeholder="This matters because…"/></div><div className="sourceCheck"><b>Before using a source, ask:</b><span>Who created it?</span><span>What was the purpose?</span><span>What evidence is included?</span><span>Whose perspective is missing?</span></div></Lab>
  <Lab n="04" title="Consider another perspective" text="Fairly representing a different view makes an argument stronger—not weaker."><div className="counterGrid"><Field label="A thoughtful person might argue…" value={d.counter} change={v=>set("counter",v)} placeholder="Another perspective is…"/><Field label="My evidence-based response is…" value={d.response} change={v=>set("response",v)} placeholder="However, the stronger evidence shows…"/></div></Lab>
  <Lab n="05" title="Turn the thinking into an essay" text="Use this order for a draft, presentation, or debate response."><ol className="essayMap">{[["Introduction","Context + question + working thesis"],["Body 1","Reason one + evidence + explanation"],["Body 2","Reason two + evidence + explanation"],["Counterclaim","Another perspective + respectful response"],["Conclusion","Larger meaning and why it matters"]].map(x=><li key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></li>)}</ol><div className="revisionCheck">{["My thesis answers the question.","Each paragraph uses relevant evidence.","I explain how the evidence supports my claim.","I identify and evaluate my sources.","I consider another perspective respectfully.","My conclusion explains the larger meaning."].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></Lab>
  <div className="thesisActions"><button onClick={save}>Save my work</button><button className="outline" onClick={()=>window.print()}>Print / save as PDF</button><button className="clear" onClick={()=>{if(confirm("Clear this thesis draft and start over?")){setD(blank);localStorage.removeItem("jerome-thesis-lab")}}}>Start a new draft</button>{saved&&<p>✓ Draft saved on this device.</p>}</div>
 </div></section>
}
function Lab({n,title,text,children}:{n:string;title:string;text:string;children:React.ReactNode}){return <section><div className="labHeading"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Field({num,label,hint,value,change,placeholder}:{num?:string;label:string;hint?:string;value:string;change:(v:string)=>void;placeholder:string}){return <label>{num&&<span>{num}</span>}<b>{label}</b>{hint&&<small>{hint}</small>}<textarea value={value} onChange={e=>change(e.target.value)} placeholder={placeholder}/></label>}
