"use client";
import {useMemo,useState} from "react";

const feelings=["Calm","Focused","Tired","Frustrated","Anxious","Sad","Angry","Overloaded","Numb / shut down","Not sure"];
const needs=["Quiet space","Lower lights or noise","Movement","Water or food","Clearer instructions","One task at a time","More time","Someone to listen","Help getting started","Stop school for now"];
const tools=[
 {name:"Reduce input",detail:"Lower noise, light, conversation, and choices. Use headphones or a quieter room."},
 {name:"Move safely",detail:"Walk, stretch, do a short karate pattern, or push against a wall for two minutes."},
 {name:"Reset the task",detail:"Ask for one direction, one example, and one visible finish line."},
 {name:"Body basics",detail:"Drink water, eat something, use the bathroom, change clothes, or adjust temperature."},
 {name:"Take real space",detail:"Say where you will be, choose a check-back time, and pause the conversation until then."},
 {name:"Use a trusted person",detail:"Ask someone to sit nearby, listen without fixing, or help decide the next safe step."}
];

export function WellnessPlan(){const[feeling,setFeeling]=useState<string[]>([]),[level,setLevel]=useState(2),[selectedNeeds,setNeeds]=useState<string[]>([]),[tool,setTool]=useState(""),[words,setWords]=useState(""),[copied,setCopied]=useState(false);const toggle=(x:string,list:string[],set:(v:string[])=>void)=>set(list.includes(x)?list.filter(y=>y!==x):[...list,x]);const message=useMemo(()=>`I am feeling ${feeling.length?feeling.join(" and ").toLowerCase():"not like myself"}. My stress level is ${level} out of 5. I need ${selectedNeeds.length?selectedNeeds.join(", ").toLowerCase():"help choosing what I need"}.${tool?` I want to try: ${tool}.`:""}${words?` What I want you to understand: ${words}`:""}`,[feeling,level,selectedNeeds,tool,words]);const copy=async()=>{await navigator.clipboard.writeText(message);setCopied(true)};return <section className="wellnessPlan"><div className="wellnessHero"><div><p className="eyebrow">EMOTIONAL WELLNESS & SELF-ADVOCACY</p><h1>Your capacity is information—not a failure.</h1><p>This check-in is private, ungraded, and designed to help Jerome notice stress early, communicate clearly, and choose the safest next step.</p></div><aside><b>Important privacy note</b><p>This page does not automatically alert a parent, therapist, teacher, or emergency service. If you need help, show or send your support message, tell a trusted adult directly, or use the crisis options below.</p></aside></div>
 <div className="wellnessBody"><section><Heading n="01" title="Name what is happening" text="Choose any words that fit. “Not sure” is a valid answer."/><div className="feelingGrid">{feelings.map(x=><button key={x} className={feeling.includes(x)?"chosen":""} onClick={()=>toggle(x,feeling,setFeeling)}>{x}</button>)}</div><div className="levelScale"><b>How intense is it right now?</b>{[1,2,3,4,5].map(x=><button key={x} className={level===x?`level${x}`:""} onClick={()=>setLevel(x)}><b>{x}</b><span>{["Steady","Uncomfortable","Struggling","Need support now","Not safe alone"][x-1]}</span></button>)}</div></section>
 <section><Heading n="02" title="Choose what your system needs" text="The goal is not to force productivity. The goal is to become safe and regulated enough for the next decision."/><div className="needGrid">{needs.map(x=><button key={x} className={selectedNeeds.includes(x)?"chosen":""} onClick={()=>toggle(x,selectedNeeds,setNeeds)}><span>{selectedNeeds.includes(x)?"✓":"○"}</span>{x}</button>)}</div></section>
 <section><Heading n="03" title="Try one coping tool" text="Choose the smallest strategy that feels possible. More than one may be needed."/><div className="toolGrid">{tools.map(x=><button key={x.name} className={tool===x.name?"chosen":""} onClick={()=>setTool(x.name)}><b>{x.name}</b><span>{x.detail}</span></button>)}</div><div className="resetTimer"><div><b>Ten-minute reset agreement</b><p>“I need ten minutes without questions. I will be in a safe place, and we can check back at the agreed time.”</p></div><button onClick={()=>setTool("Ten-minute reset agreement")}>Use this plan</button></div></section>
 <section><Heading n="04" title="Say what you need without having to find every word" text="Build a message, copy it, and show or send it to a trusted adult."/><textarea className="understand" value={words} onChange={e=>setWords(e.target.value)} placeholder="What I want you to understand is…"/><blockquote>{message}</blockquote><button className="copySupport" onClick={copy}>{copied?"✓ Copied":"Copy my support message"}</button></section>
 <section className="safetySection"><Heading n="05" title="Know when to bring in more help" text="Coping tools are for regulation. They do not replace adult, clinical, or emergency support when safety is at risk."/><div className="safetyLevels"><article><span>SUPPORT</span><h3>I am upset but safe</h3><p>Use a coping tool, reduce the task, and tell a trusted adult what support would help.</p></article><article><span>URGENT</span><h3>I might hurt myself or someone else</h3><p>Do not stay alone. Tell a trusted adult now, move away from anything that could be used for harm, and call or text 988 together.</p><div><a href="tel:988">Call 988</a><a href="sms:988">Text 988</a><a href="https://chat.988lifeline.org/" target="_blank" rel="noopener noreferrer">Chat with 988</a></div></article><article><span>EMERGENCY</span><h3>Someone is in immediate danger</h3><p>Call 911 now or go to the nearest emergency department. Stay with a safe adult and do not handle the emergency alone.</p><a href="tel:911">Call 911</a></article></div><p className="crisisNote">The 988 Suicide & Crisis Lifeline offers free, confidential, judgment-free support by call, text, or chat 24/7/365. This page is a planning tool, not medical care or active monitoring.</p></section>
 <section><Heading n="06" title="Build the trusted-person plan with an adult" text="Complete and review this with a parent, counselor, therapist, or IEP provider—not during a crisis."/><div className="planFields"><label><b>People I can tell</b><textarea placeholder="Names and how to reach them…"/></label><label><b>Places where I feel safer</b><textarea placeholder="Quiet room, trusted person’s space…"/></label><label><b>Things adults should do</b><textarea placeholder="Speak calmly, reduce questions, give space…"/></label><label><b>Things adults should avoid</b><textarea placeholder="Yelling, crowding, rapid instructions…"/></label><label><b>My early warning signs</b><textarea placeholder="Body, thoughts, behavior, sensory signs…"/></label><label><b>My professional supports</b><textarea placeholder="Counselor, OT, therapist, doctor…"/></label></div><button className="printPlan" onClick={()=>window.print()}>Print / save the plan as PDF</button></section></div></section>}
function Heading({n,title,text}:{n:string;title:string;text:string}){return <div className="wellnessHeading"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
