const quarters=[
 ["01","Foundation & Belonging","Routines, baseline skills, safety, confidence and communication."],
 ["02","Practice & Application","Books, online programs, labs, projects and practical use of growing skills."],
 ["03","Independence & Exploration","Self-advocacy, life skills, leadership and meaningful career exploration."],
 ["04","Mastery & Future Launch","Portfolio evidence, annual growth, community contribution and next-year goals."]
];
const tools=[
 ["🧪","Learning & Labs","Hands-on science, engineering, art and maker projects connected to academic themes."],
 ["📚","Resources","Books, hardcopy materials, trusted online programs, videos and instructor preparation."],
 ["🗓️","Quarterly Planning","A full year divided into four manageable journeys with weekly focus and review points."],
 ["✓","Assessments & Alerts","Evidence-based checks, assignment reminders and clear next steps without shame."],
 ["🌱","Affirmations & Regulation","Confidence-building language, emotional check-ins, movement and flexible access tools."],
 ["🧭","Life & Career Skills","Money, safety, independence, communication, technology, service and career pathways."]
];
export default function Tour(){return <main className="tourPage"><nav><a href="/"><img src="/branding/weems-rosenduft-academy-logo.jpg" alt="Weems-Rosenduft Academy"/><span>WEEMS-ROSENDUFT<small>Academy Tour</small></span></a><div><a href="#structure">Year structure</a><a href="#tools">Tools & resources</a><a href="#sample">Sample rhythm</a><a className="secureLink" href="/instructor">Secure login</a></div></nav><header><div><small>PUBLIC • READ-ONLY • NO STUDENT RECORDS</small><h1>See how we turn an individualized plan into a complete school year.</h1><p>This tour explains the Academy’s educational structure without opening any family dashboard, private schedule, saved progress, instructor notes or student records.</p><a href="#structure">Begin the tour ↓</a></div><img src="/branding/weems-rosenduft-academy-logo.jpg" alt="Weems-Rosenduft Academy crest"/></header><section className="tourStructure" id="structure"><div><small>THE YEARLY CURRICULUM</small><h2>The full year stays visible to the planner—and manageable for the learner.</h2><p>A 180-day framework is organized into four quarterly journeys. Weekly plans bring together required academics, accommodations, online and hardcopy resources, projects, life skills and evidence of progress.</p></div><ol>{quarters.map(q=><li key={q[0]}><b>{q[0]}</b><h3>{q[1]}</h3><p>{q[2]}</p></li>)}</ol></section><section className="tourTools" id="tools"><header><small>WHAT THE PLATFORM SUPPORTS</small><h2>Tools and resources with a reason.</h2><p>Each system helps instructors plan clearly and helps learners practice skills with confidence.</p></header><div>{tools.map(t=><article key={t[1]}><span>{t[0]}</span><h3>{t[1]}</h3><p>{t[2]}</p></article>)}</div></section><section className="tourSample" id="sample"><div><small>A SAMPLE LEARNING RHYTHM</small><h2>Short steps. Real application. Clear evidence.</h2></div><ol><li><b>1</b><span><strong>Connect</strong>Affirmation, emotional check-in and visual plan.</span></li><li><b>2</b><span><strong>Learn</strong>Short direct lesson with the right supports.</span></li><li><b>3</b><span><strong>Apply</strong>Build, discuss, write, move, cook, research or solve.</span></li><li><b>4</b><span><strong>Reflect</strong>Name the skill, save evidence and choose the next step.</span></li></ol></section><section className="tourPrivacy"><span>🔒</span><div><small>PUBLIC TOUR BOUNDARY</small><h2>Protected by design.</h2><p>This tour demonstrates how the Academy works. Student identities, personal schedules, grades, attendance, reports, instructor workspaces and uploaded materials remain behind authenticated access.</p></div><div><a href="/instructor">Instructor login</a><a href="/admin">Administrator login</a></div></section><footer><a href="/">← Return to the Academy homepage</a><span>Weems-Rosenduft Academy • Learning for Life</span></footer></main>}
