"use client";
import {useEffect,useState} from "react";
const weeks=[
["Strong Starts & Family Systems","Make a family routine map and goal card","Reading routines","Time + schedules","Home systems","🧭"],["Identity, Voice & Our Stories","Create an illustrated story and introduction","Story sequence","Addition review","Self and family","🎙️"],["Maps, Community & Belonging","Build a Brooklyn resource map","Labels + directions","Distance + shapes","Community geography","🗺️"],["Safety, Preparedness & First Response","Make a family safety binder","Safety words","Time + contacts","Home and fire safety","🚒"],["Living Things & Ecosystems","Keep a mini field journal","Nonfiction reading","Graph observations","Habitats + food webs","🌱"],["Forces, Motion & Building","Complete a build-test-improve challenge","How-to writing","Measurement","Motion + engineering","🧱"],["Money, Choices & Financial Literacy","Make a mini-budget and savings pitch","Persuasive words","Money math","Needs, wants, saving","💵"],["Media, Film & Digital Storytelling","Create a one-minute family documentary","Story structure","Time + sequencing","Camera, sound, media","🎬"],["Civics, Government & Our Rights","Hold a mock council and write an issue letter","Opinion writing","Voting graphs","Rules + citizenship","⚖️"],["Healthy Bodies, Minds & Emotions","Build a personal wellness plan","Feeling vocabulary","Health data","Body, hygiene, regulation","🧠"],["Food, Culture & Kitchen Science","Create a cookbook page and family meal","Procedural text","Fractions + measures","Food science + culture","🥣"],["Weather, Climate & Earth Systems","Present a five-day weather report","Weather words","Temperature graphs","Water + weather","🌦️"],["Black History, Justice & Changemakers","Present one changemaker","Biography","Timelines","History + justice","✊🏽"],["Technology, Coding & Cyber Safety","Build a prototype or cyber-safety lesson","Clear instructions","Patterns + logic","Coding + privacy","💻"],["Careers, Trades & Public Service","Make a career comparison portfolio","Question writing","Compare data","Jobs + public service","🛠️"],["Entrepreneurship & Creative Independence","Plan a family pop-up business","Product description","Prices + profit","Business + creativity","🚀"],["Leadership, Service & Community Impact","Complete one service action","Thank-you writing","Count impact","Leadership + service","🤝"],["Showcase, Reflection & Next-Quarter Launch","Host a 90-day learning showcase","Reflection writing","Growth graphs","Portfolio + goals","🏆"]];
export function Kameron90DayPlan({speak,record}:{speak:(x:string)=>void;record:(a:string,b:string,c:string,d?:string,e?:number)=>void}){
 const[open,setOpen]=useState(false),[week,setWeek]=useState(1),[done,setDone]=useState<string[]>([]);
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("kam90")||"[]"))}catch{}},[]);useEffect(()=>localStorage.setItem("kam90",JSON.stringify(done)),[done]);
 const w=weeks[week-1],tasks=[["📖","Read & Talk",w[2]],["🔢","Math Mission",w[3]],["🔬","Explore & Build",w[4]],["✍️","Show What You Know",w[1]]];
 const toggle=(id:string)=>{const next=done.includes(id)?done.filter(x=>x!==id):[...done,id];setDone(next);if(!done.includes(id))record("agenda_task","week_theme",`${w[0]}: ${id}`,"completed",30)};
 return <section className="kamAgenda"><div className="kamAgendaIntro"><div><small>WEEMS-ROSENDUFT ACADEMY • GRADE 3</small><h2>My 90-Day Learning Adventure</h2><p>Dodger turned the family agenda into 18 buildable adventures—small steps, movement breaks, read-aloud help, and a real project every week.</p><div className="agendaActions"><button onClick={()=>{setOpen(!open);setTimeout(()=>document.querySelector(".kamAgendaBoard")?.scrollIntoView({behavior:"smooth"}),20)}}>{open?"Close my map":"Open my adventure map →"}</button><button className="hear" onClick={()=>speak("Kameron, your ninety day learning adventure has eighteen weekly themes. Every week has reading, math, exploring, building, and a project you can share.")}>🔊 Hear from Dodger</button></div></div><strong>🗺️🐾</strong></div>{open&&<div className="kamAgendaBoard"><div className="weekPicker">{weeks.map((x,i)=><button className={week===i+1?"active":""} onClick={()=>{setWeek(i+1);speak(`Week ${i+1}. ${x[0]}. Your mission is ${x[1]}.`)}} key={x[0]}><span>{x[5]}</span><b>{i+1}</b></button>)}</div><div className="kamWeek"><div className="kamWeekHead"><span>{w[5]}</span><div><small>WEEK {week} • DAYS {(week-1)*5+1}–{week*5}</small><h3>{w[0]}</h3><p>Big finish: <b>{w[1]}</b></p></div><button onClick={()=>speak(`Week ${week}. ${w[0]}. Reading: ${w[2]}. Math: ${w[3]}. Explore: ${w[4]}. Big finish: ${w[1]}.`)}>🔊</button></div><div className="kamTasks">{tasks.map((t,i)=>{const id=`w${week}-${i}`;return <button className={done.includes(id)?"done":""} onClick={()=>toggle(id)} key={t[1]}><span>{done.includes(id)?"✓":t[0]}</span><div><small>{t[1]}</small><b>{t[2]}</b></div></button>})}</div><div className="kamDays">{["Monday: Meet it","Tuesday: Practice it","Wednesday: Team up","Thursday: Build it","Friday: Share it"].map((d,i)=><span key={d}><b>{i+1}</b>{d}</span>)}</div><a href="/workspace" target="_blank" rel="noreferrer">Parent & instructor plan ↗</a></div></div>}</section>
}
