"use client";import{useEffect,useState}from"react";
const games=[
 {icon:"📖",name:"Word Builder",skill:"Reading",q:"Which word rhymes with CAT?",choices:["Hat","Dog","Sun"],answer:0,why:"CAT and HAT end with the same sound: at."},
 {icon:"🔢",name:"Math Garage",skill:"Math",q:"Kameron has 12 wheels. Each car needs 4. How many cars can he build?",choices:["2","3","4"],answer:1,why:"12 divided into groups of 4 makes 3 cars."},
 {icon:"🔬",name:"Science Scout",skill:"Science",q:"Which one is a living thing?",choices:["Rock","Plant","Toy car"],answer:1,why:"A plant grows, needs water and responds to its environment."},
 {icon:"🧯",name:"Safety Captain",skill:"Safety",q:"You smell smoke at home. What is the safest first choice?",choices:["Hide","Get out and tell an adult","Look for the fire"],answer:1,why:"Get outside safely, tell an adult and follow the family emergency plan."},
 {icon:"💵",name:"Money Match",skill:"Money",q:"You have $5 and spend $2. How much remains?",choices:["$2","$3","$7"],answer:1,why:"Five minus two equals three dollars."},
 {icon:"🗺️",name:"Community Quest",skill:"Social Studies",q:"Who helps put out fires and respond to emergencies?",choices:["Firefighter","Chef","Musician"],answer:0,why:"Firefighters respond to fires, rescues and other emergencies."}
];
export function GameArcade({speak,record}:{speak:(x:string)=>void;record:(a:string,b:string,c:string,d?:string,e?:number)=>unknown}){const[pick,setPick]=useState(0),[choice,setChoice]=useState<number|null>(null),[stars,setStars]=useState(0),[played,setPlayed]=useState<string[]>([]);useEffect(()=>{try{setStars(Number(localStorage.getItem("dodger-game-stars")||0));setPlayed(JSON.parse(localStorage.getItem("dodger-games-played")||"[]"))}catch{}},[]);const g=games[pick];const answer=(i:number)=>{setChoice(i);if(i===g.answer){const n=stars+1,set=[...new Set([...played,g.name])];setStars(n);setPlayed(set);localStorage.setItem("dodger-game-stars",String(n));localStorage.setItem("dodger-games-played",JSON.stringify(set));record("game",g.skill,g.name,"correct",5);speak(`You got it! ${g.why}`)}else speak(`Good try. Let’s think again. ${g.why}`)};return <section className="gameArcade"><div className="arcadeHead"><div><small>DODGER’S LEARNING ARCADE</small><h2>Play it. Think it. Explain it.</h2><p>Choose a short game. Every try counts, and every answer teaches something.</p></div><strong>⭐ {stars}<span>learning stars</span></strong></div><div className="gameTabs">{games.map((x,i)=><button className={pick===i?"active":""} onClick={()=>{setPick(i);setChoice(null);speak(`${x.name}. ${x.q}`)}} key={x.name}><span>{x.icon}</span><b>{x.name}</b><small>{played.includes(x.name)?"✓ Played":x.skill}</small></button>)}</div><article className="gameBoard"><span>{g.icon}</span><div><small>{g.skill.toUpperCase()} CHALLENGE</small><h3>{g.q}</h3><button className="hearGame" onClick={()=>speak(g.q)}>🔊 Hear question</button><div className="gameChoices">{g.choices.map((x,i)=><button className={choice===i?(i===g.answer?"correct":"tryAgain"):""} onClick={()=>answer(i)} key={x}>{x}</button>)}</div>{choice!==null&&<p className={choice===g.answer?"gameMessage correct":"gameMessage"}>{choice===g.answer?"⭐ Great thinking!":"Keep growing—trying again builds your brain!"} {g.why}</p>}</div></article></section>}
