"use client";
import {useEffect,useState} from "react";

type Props={speak:(text:string,profile?:"dodger"|"hoot"|"larry"|"sam")=>void;record:(eventType:string,skill:string,activity:string,result?:string,minutes?:number)=>unknown};
const missions=[
 {week:"Week 5",icon:"🌊",title:"Build a Tiny Ecosystem",kit:"Felt Succulent Garden + Artificial Sea model",say:"I can find living and nonliving parts.",steps:["Point to or draw one living thing.","Point to or draw one nonliving thing.","Tell how water helps an ecosystem."],proof:"A labeled drawing or photo"},
 {week:"Week 6",icon:"🏗️",title:"Make It Move",kit:"Wooden Crane + Hand Pump + Boomerang Car",say:"I can test how a machine moves.",steps:["Make a prediction with words or a picture.","Help with three safe tests.","Circle which test moved farthest or worked best."],proof:"Prediction picture + three results"},
 {week:"Week 10",icon:"❤️",title:"Healthy Body Helper",kit:"No MEL Med chemicals—Kameron completes the safe companion activity",say:"I can name ways helpers care for our bodies.",steps:["Draw a doctor, dentist, therapist, or lab helper.","Name one tool the helper may use.","Practice saying: A grown-up helps me stay safe."],proof:"Career drawing + one spoken fact"},
 {week:"Week 11",icon:"🥣",title:"Measure, Mix & Notice",kit:"Magical & Munchable + Warm & Wonderful",say:"I can measure and notice changes.",steps:["Help count or measure ingredients.","Draw the food before and after heating.","Describe one color, smell, texture, or temperature change."],proof:"Recipe math + before/after drawing"},
 {week:"Week 12",icon:"💧",title:"Heat and Clean Water Detective",kit:"Heat Transfer + adult-led Pure Water demonstration",say:"I can observe heat and water safely.",steps:["Predict which item may warm or cool faster.","Watch the adult-led water demonstration—do not taste.","Draw arrows to show heat or water moving."],proof:"Prediction + observation drawing"},
 {week:"Week 16",icon:"🎨",title:"Junior Product Designer",kit:"Screen-Printed Canvas Bins",say:"I can help design something useful.",steps:["Choose colors and a customer.","Draw a simple pattern idea.","Tell one reason somebody may want the finished bin."],proof:"Design drawing + short sales sentence"}
];

export function KitMissions({speak,record}:Props){const[done,setDone]=useState<string[]>([]),[open,setOpen]=useState(0),[reflection,setReflection]=useState(""),[evidence,setEvidence]=useState(""),[notice,setNotice]=useState("");useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("kameron-kit-missions")||"[]"))}catch{}},[]);const finish=(title:string)=>{const next=done.includes(title)?done.filter(x=>x!==title):[...done,title];setDone(next);localStorage.setItem("kameron-kit-missions",JSON.stringify(next));if(!done.includes(title)){record("assignment","Science",title,"completed",30);speak("Great discovery, Kameron! Your project evidence is ready for your grown-up.","larry")}};const m=missions[open];const submit=async()=>{const code=JSON.stringify({student:"Kameron",week:m.week,title:m.title,reflection,evidence:evidence||m.proof,submittedAt:new Date().toLocaleDateString()});await navigator.clipboard.writeText(code);setNotice("Submission copied for Mom!");speak("Your submission is ready for Mom to review.","larry");setTimeout(()=>setNotice(""),3000)};return <section className="kitMissions"><div className="kitMissionHead"><div><small>🔬 LARRY’S KIT MISSIONS</small><h2>Build, notice, draw, and tell!</h2><p>Kameron’s science jobs are short, visual, and completed with a grown-up.</p></div><strong>{done.length}/6 ⭐</strong></div><div className="missionTabs">{missions.map((x,i)=><button className={open===i?"active":""} onClick={()=>{setOpen(i);setReflection("");setEvidence("");speak(`${x.week}. ${x.title}. ${x.say}`,"larry")}} key={x.title}><span>{x.icon}</span><b>{x.week}</b>{done.includes(x.title)&&<i>✓</i>}</button>)}</div><article className="kidMission"><div className="kidMissionTitle"><span>{m.icon}</span><div><small>{m.week} • WITH A GROWN-UP</small><h3>{m.title}</h3><p>{m.kit}</p></div><button onClick={()=>speak(`${m.title}. ${m.say}. Step one. ${m.steps[0]}. Step two. ${m.steps[1]}. Step three. ${m.steps[2]}.`,"larry")}>🔊 Listen</button></div><blockquote>“{m.say}”</blockquote><div className="kidSteps">{m.steps.map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><aside><b>Show your learning:</b> {m.proof}</aside><button className={done.includes(m.title)?"missionDone done":"missionDone"} onClick={()=>finish(m.title)}>{done.includes(m.title)?"✓ Mission complete!":"I finished my mission!"}</button>{done.includes(m.title)&&<div className="kidSubmit"><label>Tell what you learned<textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="A grown-up may type Kameron’s words."/></label><label>What are we showing Mom?<input value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder={m.proof}/></label><button onClick={submit}>Copy submission for Mom</button>{notice&&<b>{notice}</b>}</div>}</article><p className="grownupNote">Grown-up rule: Kameron does not independently handle MEL chemicals, heat, sharp tools, or electrical parts. Follow every kit’s age label and directions.</p></section>}
