"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

type Book={id:string;title:string;author:string;subject:string;level:string;reader:string;theme:string;format:string;status:string;notes:string};
const seed:Book[]=[
 {id:"seed-1",title:"Tuttle Twins collection",author:"Connor Boyack",subject:"Civics & Financial Literacy",level:"Family / Multi-age",reader:"Family",theme:"Money, Choices & Financial Literacy",format:"Owned",status:"Available",notes:"Use selected titles for history, civics and money discussions with Nana."},
 {id:"seed-2",title:"Go, Dog. Go!",author:"P. D. Eastman",subject:"Reading & Language Arts",level:"Early reader",reader:"Kameron",theme:"Identity, Voice & Our Stories",format:"Owned",status:"Available",notes:"Character, sequencing, phonics and read-aloud practice."},
 {id:"seed-3",title:"Mrs Wordsmith Storyteller’s Illustrated Dictionary",author:"Mrs Wordsmith",subject:"Writing & Vocabulary",level:"Elementary",reader:"Kameron",theme:"Identity, Voice & Our Stories",format:"Owned",status:"In progress",notes:"Use for stronger word choice and storytelling."},
 {id:"seed-4",title:"LEGO Minecraft Ideas",author:"DK",subject:"STEAM & Design",level:"Elementary",reader:"Kameron",theme:"Forces, Motion & Building",format:"Owned",status:"Available",notes:"Pair builds with measurement, written directions and reflection."},
 {id:"seed-5",title:"The Book of Perfectly Perilous Math",author:"Sean Connolly",subject:"Mathematics",level:"Middle grades",reader:"Family",theme:"Forces, Motion & Building",format:"Owned",status:"Available",notes:"Adapt challenge questions by learner level."},
 {id:"seed-6",title:"How to Talk with Friends",author:"Social skills resource",subject:"SEL & Communication",level:"Multi-age",reader:"Family",theme:"Strong Starts & Family Systems",format:"Owned",status:"Available",notes:"Use for respectful listening, help requests and collaboration."}
];
const subjects=["All subjects","Reading & Language Arts","Writing & Vocabulary","Mathematics","Science","STEAM & Design","History","Civics & Financial Literacy","Art & Media","SEL & Communication","Career Exploration","Faith & Character","Other"];
const readers=["All readers","Kameron","Jerome","Family"];
const themes=["Strong Starts & Family Systems","Identity, Voice & Our Stories","Maps, Community & Belonging","Safety, Preparedness & First Response","Living Things & Ecosystems","Forces, Motion & Building","Money, Choices & Financial Literacy","Media, Film & Digital Storytelling","Civics, Government & Our Rights","Healthy Bodies, Minds & Emotions","Food, Culture & Kitchen Science","Weather, Climate & Earth Systems","Black History, Justice & Changemakers","Technology, Coding & Cyber Safety","Careers, Trades & Public Service","Entrepreneurship & Creative Independence","Leadership, Service & Community Impact","Showcase, Reflection & Next-Quarter Launch","Flexible school-year resource"];
const blank={title:"",author:"",subject:"Reading & Language Arts",level:"",reader:"Family",theme:"Flexible school-year resource",format:"Owned",status:"Available",notes:""};

export function BookLibrary(){
 const[books,setBooks]=useState<Book[]>(seed),[search,setSearch]=useState(""),[subject,setSubject]=useState("All subjects"),[reader,setReader]=useState("All readers"),[form,setForm]=useState(blank),[adding,setAdding]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("weems-book-library")||"null");if(Array.isArray(saved))setBooks(saved)}catch{}},[]);
 const save=(next:Book[])=>{setBooks(next);localStorage.setItem("weems-book-library",JSON.stringify(next))};
 const filtered=useMemo(()=>books.filter(b=>{const hay=`${b.title} ${b.author} ${b.subject} ${b.theme} ${b.notes}`.toLowerCase();return hay.includes(search.toLowerCase())&&(subject==="All subjects"||b.subject===subject)&&(reader==="All readers"||b.reader===reader)}),[books,search,subject,reader]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!form.title.trim())return;save([{...form,id:`book-${Date.now()}`},...books]);setForm(blank);setAdding(false);setNotice("Book added to the Academy library.")};
 const update=(id:string,key:"status"|"reader",value:string)=>save(books.map(b=>b.id===id?{...b,[key]:value}:b));
 const remove=(id:string)=>{if(confirm("Remove this book from the inventory?")){save(books.filter(b=>b.id!==id));setNotice("Book removed from the inventory.")}};
 const counts={owned:books.filter(b=>b.format==="Owned").length,reading:books.filter(b=>b.status==="In progress").length,complete:books.filter(b=>b.status==="Completed").length,themes:new Set(books.map(b=>b.theme).filter(x=>x!=="Flexible school-year resource")).size};
 return <div className="page libraryPage">
  <section className="libraryHero"><div><small>HOME COLLECTION • SCHOOL RESOURCE</small><h2>Family Book Library</h2><p>Find the right book for the right child, lesson or season—without squeezing every resource into the first 90 days.</p><button onClick={()=>setAdding(true)}>＋ Add a book</button></div><strong>📚</strong></section>
  <div className="libraryStats"><article><b>{books.length}</b><span>Books & collections</span></article><article><b>{counts.owned}</b><span>Owned resources</span></article><article><b>{counts.reading}</b><span>In progress</span></article><article><b>{counts.complete}</b><span>Completed</span></article><article><b>{counts.themes}</b><span>Themes connected</span></article></div>
  <section className="libraryToolbar"><label>Search the shelves<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, author, topic or theme…"/></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label>Reader<select value={reader} onChange={e=>setReader(e.target.value)}>{readers.map(x=><option key={x}>{x}</option>)}</select></label></section>
  <div className="libraryHeading"><div><small>CURRICULUM MATCHES</small><h3>{filtered.length} resource{filtered.length===1?"":"s"} ready</h3></div><button onClick={()=>{setSearch("");setSubject("All subjects");setReader("All readers")}}>Clear filters</button></div>
  <div className="bookGrid">{filtered.map(b=><article className="bookCard" key={b.id}><div className="bookSpine"><span>{b.reader==="Kameron"?"K":b.reader==="Jerome"?"J":"WR"}</span></div><div className="bookInfo"><small>{b.subject}</small><h3>{b.title}</h3><p className="author">{b.author||"Author not entered"}</p><div className="bookTags"><span>{b.level||"Level flexible"}</span><span>{b.format}</span></div><p className="themeMatch"><b>Theme match:</b> {b.theme}</p>{b.notes&&<p className="bookNotes">{b.notes}</p>}<div className="bookActions"><label>Reader<select value={b.reader} onChange={e=>update(b.id,"reader",e.target.value)}>{readers.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label>Progress<select value={b.status} onChange={e=>update(b.id,"status",e.target.value)}>{["Available","Planned","In progress","Completed"].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>remove(b.id)} aria-label={`Remove ${b.title}`}>×</button></div></div></article>)}</div>
  {!filtered.length&&<div className="libraryEmpty"><b>📖</b><h3>No shelf matches yet</h3><p>Clear the filters or add the book you want to use.</p></div>}
  <section className="libraryGuide"><div><small>TURN ANY BOOK INTO A LESSON</small><h3>Read → Talk → Create → Save</h3></div><ol><li><b>Read or listen</b><span>Choose a section that fits attention and reading level.</span></li><li><b>Ask one strong question</b><span>What changed, mattered, surprised you or connects to real life?</span></li><li><b>Make something</b><span>Draw, build, debate, map, calculate, demonstrate or record.</span></li><li><b>Save one proof</b><span>Add a photo, response or reflection to the student portfolio.</span></li></ol></section>
  {notice&&<div className="libraryNotice" role="status">✓ {notice}<button onClick={()=>setNotice("")}>×</button></div>}
  {adding&&<div className="libraryBackdrop" onMouseDown={()=>setAdding(false)}><form className="libraryForm" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="formClose" onClick={()=>setAdding(false)}>×</button><small>NEW LIBRARY RESOURCE</small><h2>Add a book or collection</h2><div className="formGrid"><label>Title *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Author<input value={form.author} onChange={e=>setForm({...form,author:e.target.value})}/></label><label>Subject<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}>{subjects.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label>Reading level<input value={form.level} onChange={e=>setForm({...form,level:e.target.value})} placeholder="Early reader, Grade 10…"/></label><label>Best reader<select value={form.reader} onChange={e=>setForm({...form,reader:e.target.value})}>{readers.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label>Format<select value={form.format} onChange={e=>setForm({...form,format:e.target.value})}>{["Owned","Borrowed","Digital","Wishlist / Needed"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Curriculum theme<select value={form.theme} onChange={e=>setForm({...form,theme:e.target.value})}>{themes.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Lesson notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Discussion question, activity idea, instructor note…"/></label></div><div className="formButtons"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="saveBook" type="submit">Save to library</button></div></form></div>}
 </div>
}
