"use client";
import {useEffect,useState} from "react";
import "./career-rotation.css";

type Career={icon:string;name:string;why:string;days:string[]};
const plans:Record<"Kameron"|"Jerome",Career[]>={
 Kameron:[
  {icon:"🏗️",name:"Master Builder & Construction",why:"Building, measurement, design and teamwork",days:["Equipment tour: identify tape measure, level, hard hat, safety glasses and different fasteners.","Job task: read a picture plan and build a small structure with blocks or LEGO.","Safety tip: inspect the work area, protect eyes, carry tools correctly and ask before using adult tools.","Skill lab: measure two objects, compare lengths and test which shapes make a strong base.","Career challenge: photograph the build, explain one improvement and name a construction job involved."]},
  {icon:"🤖",name:"Robotics Technician",why:"Machines, coding, troubleshooting and careful testing",days:["Equipment tour: controller, sensor, motor, wheel, battery and charging cable.","Job task: follow a sequence to make a robot or toy complete one action.","Safety tip: power off before adjusting parts; keep fingers, hair and cords away from moving pieces.","Skill lab: predict, test and change one variable when the machine does not work.","Career challenge: draw a helpful robot and explain its input, action and result."]},
  {icon:"🚒",name:"Firefighter & Community Safety",why:"Helping people, physical readiness and emergency knowledge",days:["Equipment tour: turnout gear, helmet, air pack, hose, radio and thermal camera.","Job task: practice a calm address-and-emergency script with an adult.","Safety tip: crawl low under smoke, use two exits, meet outside and never return to a burning building.","Skill lab: map a safe home exit and time a calm practice drill.","Career challenge: sort firefighter duties into prevention, rescue, medical help and community education."]},
  {icon:"🎬",name:"Film Crew & Grip Department",why:"Cameras, lighting, teamwork and safe problem-solving",days:["Equipment tour: camera, tripod, light, stand, clamp, sandbag and slate.","Job task: help frame one safe shot and notice where the light comes from.","Safety tip: never touch hot lights or unsecured stands; keep walkways and cables clear.","Skill lab: compare front, side and back lighting using a safe household light with an adult.","Career challenge: make a three-shot story and credit every family crew member."]},
  {icon:"🛍️",name:"Young Entrepreneur",why:"Ideas, money, customers and responsible choices",days:["Equipment tour: product sample, price tag, calculator, order sheet and display.","Job task: identify a problem and draw one product or service that could help.","Safety tip: an adult handles private information, online sales, money accounts and customer contact.","Skill lab: count simple supply costs and choose a fair pretend price.","Career challenge: give a 30-second pitch: what it is, who it helps and why it matters."]}
 ],
 Jerome:[
  {icon:"🛡️",name:"Cybersecurity",why:"Protecting systems, analyzing risk and responding ethically",days:["Equipment tour: workstation, router, firewall, authenticator, log dashboard and authorized lab environment.","Job task: analyze a fictional security alert and list the facts still needed.","Safety tip: test only systems and accounts you own or have explicit permission to assess.","Skill lab: create a threat model for one app feature—asset, threat, weakness and protection.","Career challenge: write an incident summary with timeline, impact, evidence and next action."]},
  {icon:"📱",name:"App Developer",why:"Designing useful tools through code, testing and feedback",days:["Equipment tour: code editor, repository, issue tracker, terminal, browser tools and design mockup.","Job task: write one user story and acceptance criteria for the Newman app.","Safety tip: protect secrets, minimize collected data, test accessibility and review dependencies.","Skill lab: build or revise one small feature, then test the expected and failure paths.","Career challenge: demonstrate the feature and document the bug, fix or next sprint task."]},
  {icon:"👨🏽‍💻",name:"Coding Instructor",why:"Technical mastery, patience, communication and leadership",days:["Equipment tour: lesson outline, sample project, projector, student devices and debugging checklist.","Job task: explain one coding idea in plain language without touching the learner’s keyboard.","Safety tip: protect student accounts and privacy; use age-appropriate, authorized platforms.","Skill lab: create a 10-minute warm-up with objective, example, practice and quick check.","Career challenge: teach the mini-lesson, collect feedback and revise one direction."]},
  {icon:"🎥",name:"Key Grip & Film Production",why:"Rigging, shaping light, logistics and set safety",days:["Equipment tour: C-stand, flags, frames, clamps, dolly, track, apple boxes and sandbags.","Job task: read a simple lighting diagram and identify what the grip department must support or shape.","Safety tip: load stands correctly, keep the weight over the tall leg, secure overhead gear and maintain clear walkways.","Skill lab: make a safe tabletop lighting setup and compare hard light, diffusion and negative fill.","Career challenge: create a grip plan listing equipment, crew roles, hazards and setup order."]},
  {icon:"🚒",name:"Fire & Emergency Services",why:"Public service, incident command, prevention and medical response",days:["Equipment tour: PPE, SCBA, radio, forcible-entry tools, hose appliances and medical bag.","Job task: study how dispatch, engine, ladder, EMS and incident command coordinate.","Safety tip: scene size-up and accountability come before action; never imitate hazardous operations.","Skill lab: write a clear mock radio report using location, conditions, actions and needs.","Career challenge: compare firefighter training, EMT requirements, work conditions and next steps."]},
  {icon:"📚",name:"Library & Information Science",why:"Research, organization, public access and reliable information",days:["Equipment tour: catalog, call number, database, scanner, archive box and accessibility tools.","Job task: locate three sources using title, author, subject and keyword strategies.","Safety tip: protect patron privacy, handle archives carefully and evaluate links before sharing.","Skill lab: compare two sources for authority, evidence, date, purpose and missing perspective.","Career challenge: build a mini research guide with an introduction, five sources and annotations."]},
  {icon:"📐",name:"Construction, CAD & 3D Design",why:"Measurement, spatial reasoning, planning and trades",days:["Equipment tour: plans, scale ruler, level, PPE, CAD workspace and 3D printer or model tools.","Job task: read a floor-plan symbol key and calculate one real-world measurement from scale.","Safety tip: separate digital design from tool operation; follow PPE, ventilation and adult-supervision rules.","Skill lab: model one room, object or structural connection in Tinkercad or another approved tool.","Career challenge: present the design, constraints, materials, cost consideration and revision."]}
 ]
};
const labels=["Monday · Equipment","Tuesday · Job Task","Wednesday · Safety","Thursday · Skill Lab","Friday · Challenge"];
export function CareerRotation(){
 const[student,setStudent]=useState<"Kameron"|"Jerome">("Kameron"),[career,setCareer]=useState(0),[day,setDay]=useState(0),[done,setDone]=useState<string[]>([]);
 useEffect(()=>{const weekday=new Date().getDay();setDay(weekday>=1&&weekday<=5?weekday-1:0);try{setDone(JSON.parse(localStorage.getItem("academy-career-rotation")||"[]"))}catch{}},[]);
 const list=plans[student],item=list[career]||list[0],key=`${student}-${item.name}-${day}`;
 const switchStudent=(value:"Kameron"|"Jerome")=>{setStudent(value);setCareer(0)};
 const toggle=()=>setDone(current=>{const next=current.includes(key)?current.filter(x=>x!==key):[...current,key];localStorage.setItem("academy-career-rotation",JSON.stringify(next));return next});
 return <section className="careerRotation"><header><div><small>NEW LEARNING EVERY SCHOOL DAY</small><h2>Daily Career Discovery</h2><p>Each pathway rotates through equipment, real duties, safety, a practical skill and a Friday career challenge.</p></div><span>🧭</span></header><div className="careerControls"><div>{(["Kameron","Jerome"] as const).map(x=><button className={student===x?"active":""} onClick={()=>switchStudent(x)} key={x}>{x}</button>)}</div><select value={career} onChange={e=>setCareer(Number(e.target.value))} aria-label="Choose career">{list.map((x,i)=><option value={i} key={x.name}>{x.name}</option>)}</select></div><div className="careerDays">{labels.map((x,i)=><button className={day===i?"active":""} onClick={()=>setDay(i)} key={x}>{x}</button>)}</div><article className="careerLesson"><span>{item.icon}</span><div><small>{student.toUpperCase()} • {labels[day]}</small><h3>{item.name}</h3><p className="why">{item.why}</p><p>{item.days[day]}</p><button className={done.includes(key)?"done":""} onClick={toggle}>{done.includes(key)?"✓ Learned and recorded":"Mark today’s discovery complete"}</button></div></article><aside><b>Rotation rule:</b> Use one career for a full Monday–Friday cycle or switch pathways based on the weekly theme. Completion is saved on this device; a photo, diagram, voice explanation, checklist or short reflection can serve as evidence.</aside></section>
}
