export type WeekPlan={question:string;focus:string[];kam:string[];rome:string[]};
const daily=(a:string,b:string,c:string,d:string,e:string)=>[a,b,c,d,e];
const plans:Record<number,WeekPlan>={
3:{question:"How do maps show where we belong and how communities meet people’s needs?",focus:daily("Read maps and name community helpers","Use scale, direction and address skills","Take an optional guided VR geography field trip","Design an accessible neighborhood map","Present the map and explain one community need"),kam:daily("Build a compass rose","Model streets and map distance with blocks","In VR or video, find three features and sketch a map","Draw a safe route with landmarks","Record a tour of the map"),rome:daily("Compare political, physical and transit maps","Calculate distance, time and accessibility","Use VR or 360° media to compare place, access and scale; verify one fact","Create a sourced digital map","Propose one access improvement")},
4:{question:"How can preparation and trained responders reduce harm during emergencies?",focus:daily("Identify hazards and responder roles","Practice emergency communication","Compare fire, weather and medical plans","Conduct a family drill","Complete the safety binder"),kam:daily("Sort safe and unsafe choices","Practice address and 911 script","Draw two home exits","Time a calm drill","Create an emergency card"),rome:daily("Research fire and EMS roles","Evaluate home risks","Draft a precise emergency script","Lead and document a drill","Write an after-action report")},
5:{question:"How do living things depend on one another and their environment?",focus:daily("Observe ecosystem parts","Study food chains and life cycles","Explore a habitat through VR, video or field observation","Build a mini ecosystem","Explain balance and human impact"),kam:daily("Sort living and nonliving things","Build a picture food chain","Use VR or video to find habitat parts","Create a habitat model","Present one protection idea"),rome:daily("Analyze a food web","Research a local ecosystem","Use VR or 360° media to document interactions and limits of the model","Graph one variable","Write a claim-evidence-reasoning response")},
6:{question:"How do forces and motion help us design safer solutions?",focus:daily("Explore force and friction","Measure motion","Study structure strength","Build and improve","Defend the final design"),kam:daily("Test toy-car pushes","Measure ramp distance","Compare strong shapes","Complete a build challenge","Graph the test results"),rome:daily("Calculate speed","Control experiment variables","Analyze load distribution","Create an engineering sketch","Write a technical report")},
7:{question:"How do choices and planning help money serve our goals?",focus:daily("Separate needs and wants","Compare prices and tradeoffs","Build a realistic budget","Respond to an unexpected expense","Present a savings decision"),kam:daily("Sort needs and wants","Count money and make change","Build a picture budget","Use a surprise expense card","Pitch a savings goal"),rome:daily("Calculate take-home pay","Compare unit costs","Build an independent-living budget","Revise after an emergency cost","Explain credit risk and saving")},
8:{question:"How do filmmakers shape a true story ethically?",focus:daily("Analyze image, sound and audience","Write a visual story plan","Practice camera and interview skills","Edit for consent and access","Premiere a one-minute documentary"),kam:daily("Sequence five story pictures","Dictate a beginning, middle and end","Practice steady framing","Record narration with permission","Add a title and share"),rome:daily("Analyze point of view","Write a treatment and shot list","Conduct a consent-based interview","Edit with captions","Reflect on ethics and audience")},
9:{question:"How can people use civic processes to create change?",focus:daily("Distinguish rules, laws and rights","Study levels of government","Investigate a community issue","Prepare a mock council","Debate, vote and reflect"),kam:daily("Sort rights and responsibilities","Build a government chart","Name a neighborhood solution","Practice council speaking","Write a short issue letter"),rome:daily("Analyze a constitutional principle","Compare government responsibilities","Research stakeholders","Draft testimony","Lead a structured debate")},
10:{question:"How can routines and self-advocacy support health and learning?",focus:daily("Name body and brain signals","Track routines and focus","Practice regulation tools","Design a wellness plan","Evaluate without shame"),kam:daily("Use a body-signal chart","Build a balanced-day schedule","Practice three resets","Create a calm-tool menu","Share one routine goal"),rome:daily("Track energy and focus patterns","Research sleep hygiene","Practice self-advocacy","Design a teen wellness plan","Revise one variable")},
11:{question:"How do culture, measurement and chemical change meet in the kitchen?",focus:daily("Explore food stories and safety","Practice fractions and measurement","Observe kitchen changes","Cook and revise a recipe","Publish a cookbook page"),kam:daily("Sequence kitchen safety","Measure ingredients","Observe melting or rising","Help prepare a dish","Illustrate a recipe"),rome:daily("Research a dish’s history","Scale a recipe","Explain a chemical change","Budget ingredients","Design a cookbook page")},
12:{question:"How do air, water and energy create weather patterns?",focus:daily("Observe weather variables","Measure and graph a forecast","Model water and air movement","Produce a five-day report","Compare weather and climate"),kam:daily("Read weather symbols","Measure temperature","Build a water-cycle model","Record a forecast","Graph five days"),rome:daily("Interpret fronts and pressure","Compare forecasts with observations","Analyze a weather risk","Produce a cited report","Explain weather versus climate")},
13:{question:"How have Black changemakers pursued justice?",focus:daily("Build historical context","Study a changemaker through sources","Visit an age-appropriate museum or historic site through VR/360° media","Create a sourced presentation","Connect history to action"),kam:daily("Read a biography","Create a timeline","Use a virtual site visit to name problem, action and result","Make a portrait with caption","Present three facts"),rome:daily("Analyze primary sources","Develop a thesis","Use a virtual site visit as one source, identify its limits and verify with a primary source","Build a cited presentation","Connect history to civic responsibility")},
14:{question:"How can technology solve problems while protecting people?",focus:daily("Identify a user and safety need","Plan an app solution","Build and test","Review privacy and access","Teach or pitch the solution"),kam:daily("Sort private information","Practice safe passwords","Draw app screens","Test directions","Teach one cyber rule"),rome:daily("Complete an authorized lab","Write user stories","Build a Newman feature","Review security and accessibility","Document and present tests")},
15:{question:"What do careers require, offer and demand?",focus:daily("Inventory strengths and interests","Research duties, benefits and risks","Compare training routes","Complete a career mission","Present a career portfolio"),kam:daily("Match jobs and tools","Interview an adult","Practice a safe job skill","Create a career card","Share one career interest"),rome:daily("Complete two Career Lab lessons","Compare pay, training and risk","Research a professional pathway","Complete a practice mission","Rank paths with next steps")},
16:{question:"How do creators turn an idea into an ethical venture?",focus:daily("Identify problem and audience","Calculate costs and price","Create a sample","Test marketing","Run a pop-up pitch"),kam:daily("Brainstorm a helpful product","Count supply costs","Make a sample","Practice a short pitch","Reflect on sales-game results"),rome:daily("Define customer and value","Build pricing and break-even model","Create a minimum viable product","Test ethical marketing","Pitch with a financial plan")},
17:{question:"How can service respond to a real community need with dignity?",focus:daily("Identify needs respectfully","Choose an action and partners","Plan roles and safety","Complete the service action","Measure impact"),kam:daily("Name respectful ways to help","Choose one service job","Create a task checklist","Participate with support","Describe the impact"),rome:daily("Listen to community voices","Write a measurable service plan","Coordinate one responsibility","Document hours and outcomes","Write a leadership reflection")},
18:{question:"What evidence shows our growth and guides the next quarter?",focus:daily("Inventory evidence","Select strongest work","Complete skill checks","Rehearse the showcase","Present and set goals"),kam:daily("Choose five proud samples","Complete reading and math checks","Caption what was learned","Practice one presentation","Create a new goal card"),rome:daily("Audit Grade 10 objectives","Revise one major sample","Summarize growth","Lead the showcase","Set measurable objectives")}
};
export const getWeekPlan=(week:number)=>plans[week]||plans[18];
