"use client";
import {useEffect,useState} from "react";
import "./group-classroom.css";

const shared=[
 ["🙏","Morning Bible & affirmation","Read a short passage, pray, name one truth and one action.","Draw or say the main lesson.","Connect the passage to responsibility, justice or a current choice."],
 ["🪥","Hygiene & healthy habits","Practice teeth, bathing, deodorant, clean clothes, hands and shared-space care.","Follow a picture sequence and explain why each step matters.","Build an independent routine, supply list and private reminder system."],
 ["🏠","Know our information","Practice full names, address, caregiver number, emergency contacts and when to call 911.","Say it, build it with letters and point to a private practice card.","Give a clear location and emergency summary without sharing it publicly."],
 ["🎬","Media & family content","Plan, film, edit or discuss one safe piece of content with permission and purpose.","Choose the idea, draw three scenes and perform a short line.","Write the hook, frame shots, record sound, edit and add captions."],
 ["💬","Watch, question & discuss","Ask: What happened? What is the claim? What evidence supports it? What might another person say?","Retell the main idea and give one example.","Identify viewpoint, evidence, missing context and a source to verify."]
] as const;

const episodes=[
 ["When Laws Give You Lemons","Laws & fairness","Why rules exist and how laws affect daily choices.","Name a fair rule and why it helps.","Compare a rule, law and right; verify with a civics source."],
 ["War of the Worms","Golden Rule","Kindness, conflict resolution and treating others well.","Act out a kind response.","Separate empathy, ethics and legal responsibility."],
 ["Pencils, Pirates & Ice Cream People","Trade & cooperation","How workers and resources contribute to one product.","Name three people who help make one object.","Map a supply chain and identify benefits and risks."],
 ["Of Business and Benjamins","Entrepreneurship","Ideas, costs, customers, work and responsibility.","Create a pretend product and price.","Draft costs, revenue, risks and a customer plan."],
 ["The Inflation Monster","Money & prices","A starting point for purchasing power and inflation.","Compare what the same amount can buy.","Check current data and explain that inflation has multiple causes."],
 ["Dumpsters & Disobedience","Civil rights","Rosa Parks, unjust laws and principled civic action.","Explain why Rosa Parks is remembered.","Compare with primary sources; distinguish protest and civil disobedience."],
 ["Free Speech Freestyle","Speech & responsibility","Free speech, disagreement, truth and consequences.","Practice disagreeing without insulting.","Distinguish government restriction from school, family and platform consequences."],
 ["Homestead: A Tuttle Twins Adventure","Emergency readiness","Preparedness and family responsibility.","Choose three emergency-kit items.","Audit the family plan, contacts and supplies."],
 ["Young Washington: A Tuttle Twins Adventure","Resilience","Trying again when a project becomes difficult.","Name a time you tried again.","Turn a setback into a revised project plan."],
 ["Truth and Treason: A Tuttle Twins Adventure","Moral courage","Young people, conscience and speaking against wrongdoing.","Name a safe trusted adult.","Research the historical teens and verify the episode with additional evidence."]
] as const;

const tabs=["Together Today","Life Skills","Videos","Tuttle Twins","Content Studio"] as const;
export function GroupClassroom({onBack}:{onBack:()=>void}){
 const[tab,setTab]=useState<(typeof tabs)[number]>("Together Today"),[done,setDone]=useState<string[]>([]),[plan,setPlan]=useState({topic:"",purpose:"",roles:"",privacy:"",reflection:""});
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("academy-group-done")||"[]"));setPlan({...plan,...JSON.parse(localStorage.getItem("academy-group-plan")||"{}")})}catch{}},[]);
 const toggle=(id:string)=>setDone(current=>{const next=current.includes(id)?current.filter(x=>x!==id):[...current,id];localStorage.setItem("academy-group-done",JSON.stringify(next));return next});
 const field=(key:keyof typeof plan,value:string)=>setPlan({...plan,[key]:value});
 return <main className="groupClass"><header><button onClick={onBack}>← Academy dashboard</button><div><small>WEEMS-ROSENDUFT ACADEMY</small><h1>Our Family Classroom</h1><p>Shared lessons for Jerome and Kameron—one experience, two age-appropriate ways to learn and show understanding.</p></div><img src="/branding/weems-rosenduft-academy-logo.jpg" alt="Academy logo"/></header><nav>{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 {tab==="Together Today"&&<section className="groupPanel"><div className="intro"><small>CHOOSE 2–3 BLOCKS</small><h2>Connect first. Then learn.</h2><p>These lessons can happen at lunch, in the car, after dinner or during a family school block. Completion saves on this device.</p></div><div className="sharedGrid">{shared.map((x,i)=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><div><b>Kameron</b>{x[3]}</div><div><b>Jerome</b>{x[4]}</div><button className={done.includes(`s${i}`)?"done":""} onClick={()=>toggle(`s${i}`)}>{done.includes(`s${i}`)?"✓ Completed":"Mark complete"}</button></article>)}</div></section>}
 {tab==="Life Skills"&&<section className="groupPanel"><div className="intro"><small>TEACH • PRACTICE • CHECK • REPEAT</small><h2>Skills for health, safety and independence</h2></div><div className="skillsGrid">{[["Hygiene",["Brush teeth for two minutes, twice daily","Bathe thoroughly and use deodorant","Wear clean clothes","Wash hands at key times","Care for personal and shared spaces"]],["Identity & address",["Full legal name","Complete home address and apartment","Caregiver phone number","Two emergency contacts","When to call 911 and what to say"]],["Home & public safety",["Fire exit and meeting place","Recognize trusted helpers","Stay together in public","Know allergies and medicine information","Ask clearly for help"]],["Family responsibility",["Prepare learning materials","Help a younger sibling safely","Complete one household task","Disagree respectfully","Tell the truth and repair mistakes"]]].map(x=><article key={x[0] as string}><h3>{x[0] as string}</h3>{(x[1] as string[]).map((y,i)=><button className={done.includes(`${x[0]}${i}`)?"done":""} onClick={()=>toggle(`${x[0]}${i}`)} key={y}><i>{done.includes(`${x[0]}${i}`)?"✓":""}</i>{y}</button>)}</article>)}</div><aside><b>Privacy rule:</b> Practice addresses and phone numbers privately. Never show them in public videos, screenshots, portfolios or social posts.</aside></section>}
 {tab==="Videos"&&<section className="groupPanel"><div className="intro"><small>WATCH WITH A PURPOSE</small><h2>Age-adjusted family video library</h2></div><div className="videoGrid"><Resource title="Genesis 1" source="BibleProject" url="https://bibleproject.com/videos/genesis-1/" why="Human dignity, purpose, creativity and caring for creation." kam="Draw one good part of creation and say how we care for it." jerome="Connect being made in God’s image to dignity and responsibility."/><Resource title="Learning With Technology" source="Common Sense Media" url="https://www.commonsensemedia.org/videos/learning-with-technology" why="When technology supports learning and when it distracts." kam="Name one helpful app habit." jerome="Create three media-balance rules for school and content creation."/><Resource title="Digital Literacy & Well-Being" source="Common Sense Media" url="https://www.commonsensemedia.org/videos/digital-literacy-well-being-what-every-kid-should-know-in-the-age-of-ai" why="Critical thinking, creativity and human connection in an AI-filled world." kam="Watch selected parts with an adult and name what needs checking." jerome="Evaluate one claim, check its source and explain ethical AI use."/><Resource title="Healthy Teeth & Brushing" source="ADA MouthHealthy" url="https://www.mouthhealthy.org/all-topics-a-z/brushing-your-teeth" why="Reliable dental guidance for the family hygiene routine." kam="Demonstrate the two-minute brushing sequence." jerome="Check technique, timing, supplies and independence."/></div></section>}
 {tab==="Tuttle Twins"&&<section className="groupPanel"><div className="intro"><small>ANGEL STUDIOS CURRICULUM GUIDE</small><h2>Watch, question and verify</h2><p>Use each episode as a discussion starter—not the only source. Your Angel Studios access can be used for full episodes and newer seasons.</p><a href="https://www.angel.com/franchise/tuttle-twins" target="_blank" rel="noreferrer">Open Tuttle Twins in Angel Studios ↗</a></div><div className="episodeGrid">{episodes.map((x,i)=><article key={x[0]}><small>{x[1]}</small><h3>{x[0]}</h3><p>{x[2]}</p><div><b>Kameron</b>{x[3]}</div><div><b>Jerome</b>{x[4]}</div><button className={done.includes(`e${i}`)?"done":""} onClick={()=>toggle(`e${i}`)}>{done.includes(`e${i}`)?"✓ Watched + discussed":"Mark watched + discussed"}</button></article>)}</div><aside><b>Instructor balance:</b> Tuttle Twins presents a particular liberty and free-market viewpoint. Pair episodes with primary sources, New York civics expectations, public institutions, Black history resources and age-appropriate alternate perspectives.</aside></section>}
 {tab==="Content Studio"&&<section className="groupPanel"><div className="intro"><small>CREATE WITH PURPOSE</small><h2>Family Content Studio</h2><p>Both boys receive meaningful roles while consent, privacy and safety remain non-negotiable.</p></div><div className="planner">{([['topic','Topic or story'],['purpose','Purpose and audience'],['roles','Student roles'],['privacy','Privacy and permission check'],['reflection','What we learned']] as const).map(x=><label key={x[0]}><b>{x[1]}</b><textarea value={plan[x[0]]} onChange={e=>field(x[0],e.target.value)}/></label>)}<button onClick={()=>localStorage.setItem("academy-group-plan",JSON.stringify(plan))}>Save production plan</button></div><div className="steps">{["Choose one message","Storyboard beginning, middle and end","Assign age-appropriate roles","Check private information","Record short takes","Edit and caption","Adult reviews before sharing","Save work and reflection"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div></section>}
 </main>
}
function Resource({title,source,url,why,kam,jerome}:{title:string;source:string;url:string;why:string;kam:string;jerome:string}){return <article><small>{source}</small><h3>{title}</h3><p>{why}</p><div><b>Kameron</b>{kam}</div><div><b>Jerome</b>{jerome}</div><a href={url} target="_blank" rel="noreferrer">Open trusted resource ↗</a></article>}
