"use client";
import {useEffect,useState} from "react";
import {LabSubmissions} from "./lab-submissions";

type Lab={id:string;week:string;theme:string;title:string;student:string;subjects:string;objective:string;prep:string[];safety:string;steps:string[];evidence:string};
type RecordState={status?:string;date?:string;checks?:boolean[];safe?:boolean;prediction?:string;observations?:string;reflection?:string;evidence?:string;grade?:string;feedback?:string};

const labs:Lab[]=[
 {id:"ecosystem",week:"Week 5",theme:"Living Things & Ecosystems",title:"Artificial Sea + Felt Succulent Garden",student:"Shared • Kameron leads the model; Jerome leads analysis",subjects:"Science • Earth Science • Art",objective:"Model living and nonliving parts of an ecosystem and explain how minerals, water, plants, and environmental limits interact.",prep:["Artificial Sea and Felt Succulent Garden kits","Tray, notebook, pencil, camera","Table covering and labeled evidence folder"],safety:"Adult handles kit chemicals and reviews every label. Gloves and eye protection are used when the MEL directions require them.",steps:["Predict what each model will demonstrate.","Build each model following its kit directions.","Label living, nonliving, mineral, water, and plant features.","Compare what the models show well and what they cannot show.","Photograph both models and write a shared conclusion."],evidence:"Two model photos, Kameron’s labeled ecosystem page, and Jerome’s comparison paragraph."},
 {id:"motion",week:"Week 6",theme:"Forces, Motion & Building",title:"Wooden Crane + Hand Pump + Boomerang Car",student:"Shared • Jerome supports Kameron",subjects:"Physics • Engineering • Math",objective:"Investigate pulleys, pressure, stored energy, force, motion, and redesign through build-test-improve cycles.",prep:["Three kits with instruction booklets","Tape measure, stopwatch, masking tape","Clear testing area and data table"],safety:"Adult checks parts and supervises assembly. Keep fingers clear of moving parts and test the car only on a clear floor.",steps:["Predict how each machine will move or transfer force.","Build and inspect one mechanism at a time.","Complete three fair trials and record distance, time, or load.","Change one variable and repeat the test.","Explain which design was most effective and why."],evidence:"Build photos, three-trial data table, redesign note, and oral or written explanation."},
 {id:"health",week:"Week 10",theme:"Healthy Bodies, Minds & Emotions",title:"Therapy or Laboratory Diagnostics: Urinalysis",student:"Jerome • Grade 10 supervised medical-career lab",subjects:"Health • Biology • Medical Careers",objective:"Practice careful observation, measurement, privacy, and evidence-based reasoning in a simulated clinical investigation.",prep:["Choose one unopened/complete MEL Med kit","Lab notebook, timer, PPE listed by kit","Create a fictional patient case—never use private family data"],safety:"Direct adult supervision. Simulation only. Follow the manufacturer’s age label and directions; do not diagnose anyone or test a real person unless the kit explicitly allows it and the adult approves.",steps:["Review the medical career and vocabulary.","Write a hypothesis from the fictional case.","Complete the simulation exactly as directed.","Record measurements without changing or guessing results.","Explain limitations and when a licensed professional is needed."],evidence:"Completed lab record, vocabulary, results table, career reflection, and adult safety sign-off."},
 {id:"kitchen",week:"Week 11",theme:"Food, Culture & Kitchen Science",title:"Magical & Munchable + Warm & Wonderful",student:"Shared • Kameron leads measurement",subjects:"Chemistry • Nutrition • Math • Culture",objective:"Use recipe reading and measurement to observe heat transfer, color-changing chemistry, nutrition, and family food traditions.",prep:["Both KiwiCo Yummy kits and recipes","Measuring tools, ingredients, oven mitts","Allergy check, clean workspace, camera"],safety:"Adult manages knives, heat, stove, and oven. Check allergies and food expiration dates before beginning; wash hands and surfaces.",steps:["Read the full recipes and identify measurements.","Predict changes in color, texture, and temperature.","Prepare food with assigned adult and student jobs.","Record observations before and after heating.","Taste only when the adult confirms it is safe, then connect the recipe to culture or family."],evidence:"Recipe math, before/after photos, science observations, and a family rating or cookbook page."},
 {id:"earth",week:"Week 12",theme:"Weather, Climate & Earth Systems",title:"Heat Transfer + Pure Water",student:"Shared • differentiated written work",subjects:"Physics • Chemistry • Environmental Science",objective:"Connect thermal energy and water filtration to weather, homes, clean-water systems, and environmental problem solving.",prep:["Heat Transfer and Pure Water kits","PPE listed by MEL, notebook, timer","Two labeled data tables and protected workspace"],safety:"Adult supervises all MEL procedures and heat sources. Wear required PPE; no tasting lab water or materials.",steps:["Predict heat movement and filtration results.","Run the heat-transfer investigation and record temperatures/times.","Build or test the water-treatment models as directed.","Graph or describe results for both investigations.","Design one improvement for a home or community system."],evidence:"Two data tables, one graph, photos, and an environmental-design recommendation."},
 {id:"business",week:"Week 16",theme:"Entrepreneurship & Creative Independence",title:"Screen-Printed Canvas Bins",student:"Jerome • Kameron may help choose colors or audience",subjects:"Art • Math • Business • Writing",objective:"Move a designed product from concept to quality control, pricing, branding, and a short sales pitch.",prep:["Screen-Printed Canvas Bins kit","Sketch paper, calculator, table covering","Simple cost sheet and phone/camera"],safety:"Adult reviews ink and tool directions, protects the workspace, and supervises cleanup. Wear old clothing or an apron.",steps:["Identify a customer and useful design theme.","Sketch and revise the print before using ink.","Produce the item and complete a quality check.","Calculate materials, labor estimate, price, and possible profit.","Photograph the product and deliver a 30-second pitch."],evidence:"Design sketch, finished-product photos, cost sheet, quality checklist, and recorded or written pitch."}
];

const empty:RecordState={status:"Not started",date:"",checks:[],safe:false,prediction:"",observations:"",reflection:"",evidence:"",grade:"",feedback:""};

export function LabCenter(){
 const[records,setRecords]=useState<Record<string,RecordState>>({});
 const[open,setOpen]=useState("ecosystem");
 const[notice,setNotice]=useState("");
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem("weems-lab-records")||"{}"))}catch{}},[]);
 const update=(id:string,patch:Partial<RecordState>)=>{const next={...records,[id]:{...empty,...records[id],...patch}};setRecords(next);localStorage.setItem("weems-lab-records",JSON.stringify(next));};
 const completed=labs.filter(l=>records[l.id]?.status==="Completed").length;
 const copySummary=async(l:Lab)=>{const r={...empty,...records[l.id]};const text=`${l.week}: ${l.title} — ${l.student}. Status: ${r.status}. Date: ${r.date||"not entered"}. Subjects: ${l.subjects}. Objective: ${l.objective} Evidence: ${r.evidence||l.evidence}. Student reflection: ${r.reflection||"not entered"}. Parent grade: ${r.grade||"not entered"}. Instructor feedback: ${r.feedback||"not entered"}.`;try{await navigator.clipboard.writeText(text);setNotice("Quarterly-report summary copied")}catch{setNotice("Select the text fields to copy the record")};setTimeout(()=>setNotice(""),2200)};
 return <div className="page labCenter">
  <div className="pagehead"><div><small>TEACH • DOCUMENT • BUILD THE PORTFOLIO</small><h2>Lab & Project Center</h2><p>Six assigned projects with safety, student work, assessment, and report-ready evidence.</p></div><button className="primary" onClick={()=>window.print()}>Print records</button></div>
  <LabSubmissions/><div className="labStats"><article><b>{completed}/6</b><span>labs completed</span></article><article><b>{labs.filter(l=>records[l.id]?.status==="In progress").length}</b><span>currently in progress</span></article><article><b>{labs.reduce((n,l)=>n+(records[l.id]?.evidence?1:0),0)}</b><span>evidence notes saved</span></article></div>
  <div className="labLayout"><aside>{labs.map(l=><button key={l.id} className={open===l.id?"active":""} onClick={()=>setOpen(l.id)}><span>{l.week}</span><b>{l.title}</b><small>{records[l.id]?.status||"Not started"}</small></button>)}</aside>
  <main>{labs.filter(l=>l.id===open).map(l=>{const r={...empty,...records[l.id]};return <article className="labSheet" key={l.id}>
   <header><div><small>{l.week} • {l.theme}</small><h2>{l.title}</h2><p>{l.student}</p></div><label>Status<select value={r.status} onChange={e=>update(l.id,{status:e.target.value})}><option>Not started</option><option>Planned</option><option>In progress</option><option>Completed</option><option>Needs follow-up</option></select></label><label>Lab date<input type="date" value={r.date} onChange={e=>update(l.id,{date:e.target.value})}/></label></header>
   <section className="objective"><b>Learning objective</b><p>{l.objective}</p><span>{l.subjects}</span></section>
   <div className="labTwo"><section><h3>Preparation checklist</h3>{l.prep.map((x,i)=><label className="labCheck" key={x}><input type="checkbox" checked={!!r.checks?.[i]} onChange={e=>{const checks=[...(r.checks||[])];checks[i]=e.target.checked;update(l.id,{checks})}}/><span>{x}</span></label>)}</section><section className="safety"><h3>Safety sign-off</h3><p>{l.safety}</p><label className="labCheck"><input type="checkbox" checked={!!r.safe} onChange={e=>update(l.id,{safe:e.target.checked})}/><span>Adult reviewed directions and approved this lab.</span></label></section></div>
   <section><h3>Investigation steps</h3><ol>{l.steps.map(x=><li key={x}>{x}</li>)}</ol></section>
   <div className="labFields"><label>Before-lab prediction<textarea value={r.prediction} onChange={e=>update(l.id,{prediction:e.target.value})} placeholder="What do we think will happen—and why?"/></label><label>Observations and data<textarea value={r.observations} onChange={e=>update(l.id,{observations:e.target.value})} placeholder="Record measurements, changes, trials, and results."/></label><label>Student reflection<textarea value={r.reflection} onChange={e=>update(l.id,{reflection:e.target.value})} placeholder="What did I learn? What would I change?"/></label><label>Evidence saved<textarea value={r.evidence} onChange={e=>update(l.id,{evidence:e.target.value})} placeholder={l.evidence}/></label></div>
   <section className="assessment"><label>Parent grade / score<input value={r.grade} onChange={e=>update(l.id,{grade:e.target.value})} placeholder="Example: 88%, B+, or Meets objective"/></label><label>Instructor feedback<textarea value={r.feedback} onChange={e=>update(l.id,{feedback:e.target.value})} placeholder="Strength, evidence, and one next step."/></label></section>
   <footer><span>Saved automatically on this device</span><button onClick={()=>copySummary(l)}>Copy quarterly-report summary</button></footer>
  </article>})}</main></div>{notice&&<div className="labNotice">{notice}</div>}
 </div>
}
