"use client";
import {useEffect,useState} from "react";
type Slot={id:string;quarter:string;window:string;theme:string;kits:string;students:string;lead:string;prep:string};
const slots:Slot[]=[
 {id:"q1a",quarter:"Quarter 1",window:"Weeks 1–4",theme:"Maker readiness & safety",kits:"Maker Station • 2-in-1 Lantern • Spectrum Goggles",students:"Shared",lead:"Jestina + David",prep:"Check tools, batteries and eye-safety directions"},
 {id:"q1b",quarter:"Quarter 1",window:"Weeks 5–6",theme:"Ecosystems, forces & motion",kits:"Artificial Sea • Felt Succulent Garden • Wooden Crane • Hand Pump • Boomerang Car",students:"Shared",lead:"Mona + David",prep:"Protect workspace; check MEL PPE and all moving parts"},
 {id:"q1c",quarter:"Quarter 1",window:"Weeks 7–9",theme:"Light, color & media",kits:"Green Flashlight • Cyanotype • Motorized Spin Art • Planetarium Projector",students:"Kameron + shared",lead:"Mona + Ethan",prep:"Batteries, dark room, paper and eye-safety review"},
 {id:"q1d",quarter:"Quarter 1",window:"Weeks 10–12",theme:"Health, kitchen & Earth systems",kits:"Therapy or Urinalysis • Magical & Munchable • Warm & Wonderful • Heat Transfer • Pure Water",students:"Differentiated",lead:"Jestina",prep:"Medical simulation privacy; allergy and heat checks; MEL PPE"},
 {id:"q1e",quarter:"Quarter 1",window:"Weeks 13–18",theme:"Art, business & showcase",kits:"Marbled Paper • Screen-Printed Canvas Bins • Watercolor Clock",students:"Jerome + shared",lead:"Mona + Ethan",prep:"Ink, paper, table covering, clock parts and pricing sheet"},
 {id:"q2a",quarter:"Quarter 2",window:"October–November",theme:"Chemistry foundations",kits:"Elements • Colorful Chemistry • Luminescence • Egyptian Night",students:"Jerome + shared demonstrations",lead:"Jestina / co-op",prep:"Inventory chemicals, expiration dates, gloves and goggles"},
 {id:"q2b",quarter:"Quarter 2",window:"November–December",theme:"Textiles, culture & functional art",kits:"Sashiko Lamp • Shibori Messenger Bag • Rope Coil Baskets • Crochet Market Bag",students:"Shared",lead:"Mona",prep:"Needles, thread, dye protection, lamp parts and hand-rest plan"},
 {id:"q2c",quarter:"Quarter 2",window:"Flex / make-up week",theme:"Interest-led or unfinished work",kits:"Any incomplete Quarter 1–2 project",students:"Student choice",lead:"Jestina",prep:"Use for travel, missing parts, portfolio completion or co-op"},
 {id:"q3a",quarter:"Quarter 3",window:"January",theme:"Materials & manufacturing",kits:"Corrosion • Etching and Plating • Alchemy • Rivet Press",students:"Jerome",lead:"David + Jestina",prep:"Inspect chemicals and tools; PPE; adult-only setup"},
 {id:"q3b",quarter:"Quarter 3",window:"February",theme:"Medical science & careers",kits:"Dentistry: Orthodontics • Dentistry: Caries • Pharmacy",students:"Jerome",lead:"Jestina / mentor",prep:"Simulation only; verify kit completeness and age labels"},
 {id:"q3c",quarter:"Quarter 3",window:"March",theme:"Product design studio",kits:"Inlaid Wood Bookends • Hand-Dipped Planters • Mini Clay Succulents • Translucent Clay Candleholder",students:"Jerome + shared design",lead:"Mona + David",prep:"Dust/plaster protection, tool check and LED candle only"},
 {id:"q4a",quarter:"Quarter 4",window:"April",theme:"Mechanisms & practical design",kits:"Articulated Desk Lamp • Mirror Bank • Stitched Faux-Leather Accessories",students:"Jerome + shared",lead:"David + Mona",prep:"Check springs, reflective edges, needles and electrical parts"},
 {id:"q4b",quarter:"Quarter 4",window:"May",theme:"Light investigation & advanced chemistry",kits:"A Study in Ultraviolet • But Will It Burn?",students:"Jerome",lead:"Jestina + David",prep:"Direct supervision; eye protection; combustion lab only with qualified adult"},
 {id:"q4c",quarter:"Quarter 4",window:"May–June",theme:"Creative finish & exhibition",kits:"Handmade Soap • Hand-Dipped Planters or student-selected unfinished kit",students:"Shared",lead:"Mona + Jestina",prep:"Ingredient safety, display labels, photos and final portfolio records"},
 {id:"hold",quarter:"Hold",window:"Before scheduling",theme:"Identification required",kits:"One title-obscured MEL Science box",students:"Do not assign",lead:"Jestina",prep:"Photograph the full label and verify age, contents and safety first"}
];
type S={status:string;parts:string;date:string};
export function LabCalendar(){const[filter,setFilter]=useState("All"),[state,setState]=useState<Record<string,S>>({});useEffect(()=>{try{setState(JSON.parse(localStorage.getItem("full-year-lab-plan")||"{}"))}catch{}},[]);const update=(id:string,p:Partial<S>)=>{const current=state[id];const n={...state,[id]:{status:current?.status??"Planned",parts:current?.parts??"",date:current?.date??"",...p}};setState(n);localStorage.setItem("full-year-lab-plan",JSON.stringify(n))};const shown=filter==="All"?slots:slots.filter(x=>x.quarter===filter);return <div className="page labCalendar"><div className="pagehead"><div><small>FULL SCHOOL YEAR • FLEXIBLE RESOURCE MAP</small><h2>Lab Calendar & Supply Planner</h2><p>One organized place to decide what to use, who leads it, and what must be ready first.</p></div><button className="primary" onClick={()=>window.print()}>Print year plan</button></div><div className="calendarSummary"><b>{slots.length-1}</b><span>planned lab windows</span><b>{slots.filter(x=>(state[x.id]?.status||"Planned")==="Completed").length}</b><span>completed</span><b>{slots.filter(x=>state[x.id]?.parts).length}</b><span>supply notes entered</span></div><div className="calendarFilters">{["All","Quarter 1","Quarter 2","Quarter 3","Quarter 4","Hold"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="yearSlots">{shown.map(x=>{const current=state[x.id];const s={status:current?.status??"Planned",parts:current?.parts??"",date:current?.date??""};return <article key={x.id}><header><span>{x.quarter}</span><b>{x.window}</b><select value={s.status} onChange={e=>update(x.id,{status:e.target.value})}><option>Planned</option><option>Prep this week</option><option>Ready</option><option>In progress</option><option>Completed</option><option>Moved to flex week</option><option>Missing parts</option><option>Hold</option></select></header><h3>{x.theme}</h3><p className="kitLine">{x.kits}</p><div className="slotMeta"><p><b>Students</b>{x.students}</p><p><b>Lead</b>{x.lead}</p><p><b>Prep focus</b>{x.prep}</p></div><div className="slotInputs"><label>Target date<input type="date" value={s.date} onChange={e=>update(x.id,{date:e.target.value})}/></label><label>Missing parts / replacements<textarea value={s.parts} onChange={e=>update(x.id,{parts:e.target.value})} placeholder="Batteries, gloves, ingredient, broken part, expiration date…"/></label></div></article>})}</div><section className="prepRhythm"><h3>One-week preparation rhythm</h3><div><p><b>7 days before</b>Open box, read directions and confirm age/safety fit.</p><p><b>5 days before</b>List missing or replaceable materials.</p><p><b>3 days before</b>Assign adult lead, workspace and student roles.</p><p><b>Lab day</b>Safety sign-off, build/test and collect evidence.</p><p><b>Within 48 hours</b>Review, grade and approve portfolio evidence.</p></div></section></div>}
