export type MaterialMatch={books:string[];kits:string[];games:string[];why:string;how:string};
export const materialGuide:Record<number,MaterialMatch>={
1:{books:["How to Talk with Friends","Spectrum Writing"],kits:["Maker Station","Watercolor Clock"],games:["Rummikub"],why:"Visible routines, organized tools and turn-taking make the new school rhythm concrete.",how:"Read one social-skills section, organize and label the station, practice transitions with the clock, then play a short round focused on waiting and flexible thinking."},
2:{books:["Go, Dog. Go!","Mrs. Wordsmith Illustrated Dictionary"],kits:["Cyanotype","Marbled Paper Designs"],games:["Guess in 10 Marvel"],why:"Character stories, descriptive vocabulary and visual art support identity and voice without relying only on handwriting.",how:"Identify traits, play a description round, select stronger words, then create a print or paper design as the story cover."},
3:{books:["Daily Geography Practice","America’s History, 1215–1776"],kits:["Planetarium Projector"],games:["Guess in 10 Marvel"],why:"Maps, models and clues strengthen direction, symbols, categories and evidence.",how:"Compare physical and transit maps, locate resources, discuss orientation with the model, then justify a safe route."},
4:{books:["The 12 Rules Boot Camp","Black Firefighters and the FDNY"],kits:["2-in-1 Lantern","But Will It Burn? — Jerome only"],games:["Elmo’s Good Manners Game"],why:"Safety sticks when rules connect to real equipment, careers and a practiced family plan.",how:"Read a firefighter excerpt, inspect exits and alarms, build the lantern, practice an announced drill, and use the fire-science kit only with David’s direct supervision."},
5:{books:["The Very Hungry Caterpillar","Skill Sharpeners Science","Black Men in Science"],kits:["Artificial Sea","Felt Succulent Garden"],games:["Guess in 10 habitat clues"],why:"Models and sorting make life cycles, habitats and ecosystem relationships visible.",how:"Read for sequence, sort living/nonliving examples, build the models, label food-chain roles, and compare the model with a real ecosystem."},
6:{books:["LEGO Minecraft Ideas","The Book of Perfectly Perilous Math"],kits:["Wooden Crane","Hand Pump","Boomerang Car"],games:["Number Ninja"],why:"Engineering builds turn forces, measurement and design tradeoffs into observable evidence.",how:"Choose one main build, predict, change one variable, measure three trials and record one evidence-based redesign."},
7:{books:["The Messed Up Market","The Creature from Jekyll Island","The Miraculous Pencil"],kits:["Watercolor Clock"],games:["Rummikub","Number Ninja"],why:"Concrete numbers, choices and tradeoffs make budgeting meaningful.",how:"Use fictional income and prices, sort needs/wants, play a number round, balance a budget and explain one tradeoff."},
8:{books:["Dog Man: Twenty Thousand Fleas","Harry Potter and the Cursed Child"],kits:["Cyanotype","Green Flashlight","Articulated Desk Lamp"],games:["Guess in 10 story clues"],why:"Narrative books plus light and image tools connect storytelling to camera and design choices.",how:"Analyze structure, storyboard six shots, test safe lighting, record with permission, and add captions or a transcript."},
9:{books:["The Tuttle Twins Learn About the Law","The Case of the Broken Window","Why We Can’t Wait"],kits:["No kit needed this week"],games:["Rummikub for rules and fairness"],why:"Civics becomes real through rules, competing claims, evidence and respectful decisions.",how:"Read age-matched excerpts, distinguish rights and responsibilities, run a mock council, cite evidence and write an issue letter."},
10:{books:["How to Talk with Friends","The Golden Rule"],kits:["MEL Med Therapy","Urinalysis — Jerome simulation only"],games:["Elmo’s Good Manners Game"],why:"Social skills and supervised simulations build body awareness, self-advocacy and health-care career knowledge.",how:"Protect private health details, practice one regulation tool and let Jerome complete only simulated kit procedures with adult supervision."},
11:{books:["The Book of Perilous Dishes","Spectrum Writing"],kits:["Magical & Munchable","Warm & Wonderful"],games:["Number Ninja"],why:"Cooking integrates sequence, fractions, measurement, chemistry, culture and safety.",how:"Check allergies, read the recipe, assign safe roles, measure, record before/after observations and publish a science recipe page."},
12:{books:["Daily Geography Practice","Skill Sharpeners Science","Space and Beyond"],kits:["Heat Transfer","Pure Water","Planetarium Projector"],games:["Number Ninja graphing warm-up"],why:"Repeated observations, heat movement and water models clarify weather and Earth systems.",how:"Track five days at the same time, complete one investigation, graph results, compare with NOAA and distinguish weather from climate."},
13:{books:["Heroes in Black History","Who Was Sojourner Truth?","Why We Can’t Wait","Black Ghost of Empire"],kits:["Cyanotype"],games:["Guess in 10 changemakers"],why:"Biography, primary sources and visual artifacts connect action to historical context.",how:"Build a problem-action-result timeline, verify a claim, create a portrait print and present with citations."},
14:{books:["Guide to Logical Fallacies","Guide to True Conspiracies"],kits:["Mirror Bank"],games:["Guess in 10 question quality"],why:"Logic games and system builds reinforce careful questioning, privacy, testing and evidence.",how:"Use fictional passphrase examples, identify private data, analyze one fallacy, build/test a model or app and document fixes—never probe real accounts."},
15:{books:["Black Firefighters and the FDNY","Black Men in Science","Guide to Inspiring Entrepreneurs"],kits:["Maker Station","Articulated Desk Lamp","Rivet Press"],games:["Career Guess in 10"],why:"Career texts and equipment make duties, training, safety, benefits and risks concrete.",how:"Compare two careers, identify tools and safety rules, use official career data and rank pathways with evidence."},
16:{books:["Guide to Inspiring Entrepreneurs","The Food Truck Fiasco","Spectacular Snow Business"],kits:["Screen-Printed Canvas Bins","Handmade Soap","Crochet Market Bag"],games:["Rummikub pricing practice"],why:"A real product connects design, cost, quality, ethical marketing and customer needs.",how:"Select one kit, identify a customer, calculate fictional costs, build safely, quality-check and deliver a truthful pitch."},
17:{books:["The Medals of Merit","The Golden Rule","Heroes in Black History"],kits:["2-in-1 Lantern or Maker Station if needed"],games:["Elmo’s Good Manners Game"],why:"Service should connect respectful communication with a genuine community need.",how:"Ask what is needed, obtain permission, assign safe roles, record hours/outcomes and reflect on partnership."},
18:{books:["Student-selected portfolio books","Webster’s Dictionary and Thesaurus"],kits:["Display completed kits; do not start a complex new kit"],games:["Student-choice mastery game"],why:"The final week should reveal growth and decision-making instead of adding unnecessary work.",how:"Choose five samples, match each to a skill, prepare a game or kit demonstration, celebrate growth and write the next goal."}
};
export function WeeklyMaterialsGuide({week}:{week:number}){const m=materialGuide[week];if(!m)return null;return <section className="weeklyMaterialsGuide"><header><div><small>USE WHAT WE ALREADY OWN</small><h3>Week {week} books, kits & learning games</h3></div><span>Physical copies at home</span></header><div className="materialMatchGrid"><article><b>📚 Books</b>{m.books.map(x=><p key={x}>{x}</p>)}</article><article><b>🧪 Kits / tools</b>{m.kits.map(x=><p key={x}>{x}</p>)}</article><article><b>🎲 Games</b>{m.games.map(x=><p key={x}>{x}</p>)}</article></div><div className="materialHow"><p><b>Why these fit:</b> {m.why}</p><p><b>How the instructor uses them:</b> {m.how}</p></div><footer><a href="#library">Open Book Library</a><a href="#inventory">Open Kit Inventory</a></footer></section>}
