export type MaterialMatch={books:string[];kits:string[];games:string[];why:string;how:string;vr?:string};
export const materialGuide:Record<number,MaterialMatch>={
1:{books:["How to Talk with Friends","Spectrum Writing"],kits:["Maker Station","Shape/color sorting clock","Small whiteboards","Educational posters"],games:["52 Essential Coping Skills for Kids","52 Essential Conversations","Rummikub"],why:"Visible routines, regulation tools and turn-taking make the new school rhythm concrete.",how:"Choose one coping card, organize and label the station, rehearse the schedule on a whiteboard and end with a short game focused on waiting and flexible thinking."},
2:{books:["Go, Dog. Go!","Mrs. Wordsmith Storyteller’s Kit / Illustrated Dictionary","Hooked on Phonics"],kits:["Cyanotype","Marbled Paper Designs","1405-piece art-and-crafts set","Paint, silicone painting mat and palettes","Japanese girl and Ghanaian boy puppets","Alphabet pocket chart and educational posters"],games:["Osmo Little Genius learning kit","Centersolutions Language Arts games","Sight Word Swat","Snap It Up","Alphabet Marks the Spot","Coogam wooden letter/number construction","Coogam magnetic letters & numbers","Coogam short-vowel spelling game","Wooden CVC spelling game","Magnet alphabet maze","Sight-word and phonics flash cards","Spanish Vocabulary Bingo","52 Essential Conversations","Guess in 10 Marvel"],why:"Character stories, phonics tools, vocabulary games, puppets and visual art support identity and voice without relying only on handwriting.",how:"Select only one literacy station per lesson: hear/build the word, read it in context and use it in a sentence or puppet story. Create an artwork or print as the story cover; avoid using the puppets as cultural stereotypes."},
3:{books:["Daily Geography Practice","America’s History, 1215–1776","Geography Busy Book"],kits:["World map","State and capital flash cards","Planetarium Projector"],games:["State-and-capital challenge","Guess in 10 clues"],why:"Maps, models and clues strengthen direction, symbols, categories and evidence.",how:"Compare physical and political maps, locate five states and capitals, build a route with a map key and justify it with directional language.",vr:"BRINK Traveler or an instructor-previewed 360° place visit; save a labeled field sketch."},
4:{books:["The 12 Rules Boot Camp","Black Firefighters and the FDNY"],kits:["2-in-1 Lantern","Makes cardboard toolset","But Will It Burn? — Jerome only"],games:["52 Essential Social Dilemmas","Elmo’s Good Manners Game"],why:"Safety sticks when rules connect to equipment, careers and rehearsed decisions.",how:"Role-play safe tool choices, inspect exits and alarms, build the lantern, practice an announced drill, and use the fire-science kit only with direct adult supervision."},
5:{books:["The Very Hungry Caterpillar","Skill Sharpeners Science","Black Men in Science","Human Body Busy Book for Kids"],kits:["Artificial Sea","Coral kit","Life Cycle Learning set","Felt Succulent Garden"],games:["Living/nonliving sorting challenge","Guess in 10 habitat clues"],why:"Models and sorting make life cycles, habitats and ecosystem relationships visible.",how:"Sequence a life cycle, build coral/ocean and plant models, label food-chain roles and compare each model with a credible image of the real system.",vr:"VictoryXR/VXRLabs ecosystem or cell experience; save a food chain or model-limits note."},
6:{books:["LEGO Minecraft Ideas","The Book of Perfectly Perilous Math"],kits:["Wooden Crane","Hand Pump","Boomerang Car","Gobidex Magnetic Tiles Cars and Magnetic Blocks","Flexible straws","Popsicle sticks and clothes pins"],games:["Multiplication dominoes","Math-cube activity cards","Number Ninja"],why:"Engineering builds and math tools turn forces, measurement and design tradeoffs into observable evidence.",how:"Choose one main build, predict, change one variable, measure three trials, use dominoes or cubes for the calculation and record one evidence-based redesign."},
7:{books:["The Messed Up Market","The Creature from Jekyll Island","The Miraculous Pencil"],kits:["Play money","Play Learn & Earn money kit","Jumbo double-sided magnetic money"],games:["Money Bags","Fraction dominoes","Rummikub","Number Ninja"],why:"Concrete money and fraction models make budgeting, change and tradeoffs meaningful.",how:"Give each learner fictional income and prices, sort needs/wants, make change with two representations, balance a budget and explain one tradeoff."},
8:{books:["Dog Man: Twenty Thousand Fleas","Harry Potter and the Cursed Child"],kits:["Cyanotype","Green Flashlight","Articulated Desk Lamp"],games:["Guess in 10 story clues"],why:"Narrative books plus light and image tools connect storytelling to camera and design choices.",how:"Analyze structure, storyboard six shots, test safe lighting, record with permission, and add captions or a transcript."},
9:{books:["The Tuttle Twins Learn About the Law","The Case of the Broken Window","Why We Can’t Wait"],kits:["U.S. President flash cards","Black History cards"],games:["Election Night board game","52 Essential Social Dilemmas"],why:"Civics becomes real through office, elections, competing claims, evidence and respectful decisions.",how:"Preview cards for accuracy, distinguish rights and responsibilities, run Election Night as a simulation, verify one claim with a primary source and write an issue letter."},
10:{books:["How to Talk with Friends","The Golden Rule","Human Body Busy Book for Kids"],kits:["Science to the Max Interactive Human Body","MEL Med Therapy","Urinalysis — Jerome simulation only"],games:["52 Essential Coping Skills","52 Essential Social Dilemmas"],why:"Body models, social skills and supervised simulations build body awareness, self-advocacy and health-care career knowledge.",how:"Protect private health details, match model parts to functions, practice one regulation tool and let Jerome complete only simulated kit procedures with adult supervision.",vr:"VictoryXR/VXRLabs human-body lab; name model limits and verify two facts off-headset."},
11:{books:["The Book of Perilous Dishes","Spectrum Writing"],kits:["Magical & Munchable","Warm & Wonderful"],games:["Number Ninja"],why:"Cooking integrates sequence, fractions, measurement, chemistry, culture and safety.",how:"Check allergies, read the recipe, assign safe roles, measure, record before/after observations and publish a science recipe page."},
12:{books:["Daily Geography Practice","Skill Sharpeners Science","Space and Beyond","Geography Busy Book"],kits:["Heat Transfer","Pure Water","Earth Science Minerals","Planetarium Projector","Make Your Own Squishies: Space Exploration"],games:["State-and-capital weather map","Number Ninja graphing warm-up"],why:"Repeated observations, minerals, heat movement, water and space models clarify Earth systems.",how:"Track five days at the same time, complete one investigation, graph results, compare with NOAA and label what each physical model can and cannot show.",vr:"BRINK Traveler for landforms or VictoryXR for Earth/space; save observations and a verified comparison."},
13:{books:["Heroes in Black History","Who Was Sojourner Truth?","Why We Can’t Wait","Black Ghost of Empire"],kits:["Black History cards","Cyanotype"],games:["Changemaker clue game"],why:"Biography, primary sources and visual artifacts connect action to historical context.",how:"Preview cards for age and accuracy, build a problem-action-result timeline, verify a claim, create a portrait print and present with citations.",vr:"Anne Frank House VR is Jerome-only after instructor preview; compare persecution, resistance and source perspective without equating distinct histories."},
14:{books:["Guide to Logical Fallacies","Guide to True Conspiracies"],kits:["Mirror Bank"],games:["Guess in 10 question quality"],why:"Logic games and system builds reinforce careful questioning, privacy, testing and evidence.",how:"Use fictional passphrase examples, identify private data, analyze one fallacy, build/test a model or app and document fixes—never probe real accounts."},
15:{books:["Black Firefighters and the FDNY","Black Men in Science","Guide to Inspiring Entrepreneurs"],kits:["Maker Station","Articulated Desk Lamp","Rivet Press","Cardboard toolset"],games:["52 Essential Interview Skills","Word Teasers SAT/ACT Vocabulary","Career Guess in 10"],why:"Career texts, interview prompts and equipment make duties, training, communication, safety, benefits and risks concrete.",how:"Compare two careers, practice a 60-second interview answer, identify tools and safety rules, use official career data and rank pathways with evidence.",vr:"VictoryXR career simulation or Gravity Sketch design task; save a career reflection or prototype screenshot."},
16:{books:["Guide to Inspiring Entrepreneurs","The Food Truck Fiasco","Spectacular Snow Business"],kits:["Screen-Printed Canvas Bins","Handmade Soap","Crochet Market Bag","Craft supplies and display materials"],games:["Play money","Money Bags","Fraction dominoes for pricing","Rummikub pricing practice"],why:"A real product connects design, cost, quality, ethical marketing and customer needs.",how:"Select one product, identify a customer, calculate fictional costs and change, build safely, quality-check and deliver a truthful pitch.",vr:"Gravity Sketch for a Jerome product prototype or Open Brush for both learners’ package/advertising concept."},
17:{books:["The Medals of Merit","The Golden Rule","Heroes in Black History"],kits:["2-in-1 Lantern or Maker Station if needed"],games:["Elmo’s Good Manners Game"],why:"Service should connect respectful communication with a genuine community need.",how:"Ask what is needed, obtain permission, assign safe roles, record hours/outcomes and reflect on partnership."},
18:{books:["Student-selected portfolio books","Webster’s Dictionary and Thesaurus"],kits:["Display completed kits; use Learn the Dough Mats, number/wooden matching cards, whiteboards, posters and craft supplies for labels"],games:["Student-choice mastery game","Addition and subtraction flash cards / easy-erase cards","Counting Cows/Cars multiplication cards","Math-cube activity cards","Sight Word Swat or Snap It Up"],why:"The final week should reveal growth and decision-making instead of adding unnecessary work.",how:"Choose five samples, match each to a skill, prepare a game or kit demonstration, celebrate growth and write the next goal."}
};
export function WeeklyMaterialsGuide({week}:{week:number}){const m=materialGuide[week];if(!m)return null;return <section className="weeklyMaterialsGuide"><header><div><small>USE WHAT WE ALREADY OWN</small><h3>Week {week} books, kits & learning games</h3></div><span>Checked against school inventory</span></header><div className="materialMatchGrid"><article><b>📚 Books</b>{m.books.map(x=><p key={x}>{x}</p>)}</article><article><b>🧪 Kits / tools</b>{m.kits.map(x=><p key={x}>{x}</p>)}</article><article><b>🎲 Games</b>{m.games.map(x=><p key={x}>{x}</p>)}</article></div><div className="materialHow"><p><b>Why these fit:</b> {m.why}</p><p><b>How the instructor uses them:</b> {m.how}</p>{m.vr&&<p><b>Optional VR connection:</b> {m.vr} <a href="#vr-learning-lab">Open the VR program guide.</a></p>}</div><footer><a href="#library">Open Book Library</a><a href="#inventory">Open Kit Inventory</a></footer></section>}
