"use client";
import {useEffect,useState} from "react";
import {getWeekPlan} from "./curriculum-data";
import {StemInventory} from "./stem-inventory";
import {LabCenter} from "./lab-center";
import {LabCalendar} from "./lab-calendar";
import {StandardsTracker} from "./standards-tracker";
import {AttendanceCenter} from "./attendance-center";
import {weekSupport} from "./week-support";
import {ReminderCenter} from "./reminder-center";
import {QuarterlyGenerator} from "./quarterly-generator";
import {BackupCenter} from "./backup-center";
import {BookLibrary} from "./book-library";
import {RecordsCenter} from "./records-center";
import {SchoolYear} from "./school-year";
import {GroupClassroom} from "./group-classroom";
import {ParentDashboard} from "./parent-dashboard";
import {VrLearningLab} from "./vr-learning-lab";
import {CareerRotation} from "./career-rotation";
import {WeeklyMaterialsGuide} from "./material-guide";

const themes=[
["Strong Starts & Family Systems","Family routine map + goal cards","🧭"],["Identity, Voice & Our Stories","Illustrated story + recorded introduction","🎙️"],["Maps, Community & Belonging","Brooklyn community resource map","🗺️"],["Safety, Preparedness & First Response","Family safety binder + drill","🚒"],["Living Things & Ecosystems","Mini ecosystem + field journal","🌱"],["Forces, Motion & Building","Build-test-improve challenge","🧱"],["Money, Choices & Financial Literacy","Mini-budget + savings pitch","💵"],["Media, Film & Digital Storytelling","One-minute family documentary","🎬"],["Civics, Government & Our Rights","Mock council + issue letter","⚖️"],["Healthy Bodies, Minds & Emotions","Personal wellness plan","🧠"],["Food, Culture & Kitchen Science","Cookbook page + family meal","🥣"],["Weather, Climate & Earth Systems","Five-day weather report","🌦️"],["Black History, Justice & Changemakers","Changemaker presentation","✊🏽"],["Technology, Coding & Cyber Safety","App prototype or safety lesson","💻"],["Careers, Trades & Public Service","Career comparison portfolio","🛠️"],["Entrepreneurship & Creative Independence","Pop-up business + pitch","🚀"],["Leadership, Service & Community Impact","Documented service action","🤝"],["Showcase, Reflection & Next-Quarter Launch","90-day family showcase","🏆"]];
const quickNav=[["home","⌂","Home"],["parent","♛","Parent Dashboard"],["today","✓","Today"]];
const navGroups=[
 {label:"Daily School",icon:"▦",items:[["group","♥","Family Classroom"],["schoolyear","▣","Full School Year"],["plan","▦","Current 90-Day View"],["week1","★","Current Week"],["students","☺","Students"],["reminders","◴","Assignments & Alerts"]]},
 {label:"Learning & Labs",icon:"⚗",items:[["resources","◇","Resources"],["library","▥","Book Library"],["inventory","▤","Kit Inventory"],["labs","⚗","Lab Center"],["labcalendar","▣","Lab Calendar"]]},
 {label:"Team & Records",icon:"✎",items:[["team","✎","Instructor Hub"],["standards","◎","Standards & Credits"],["attendance","◷","Attendance & Hours"],["reports","▧","Quarterly Reports"],["official-records","▥","Reports & Transcript"]]},
 {label:"School Tools",icon:"☁",items:[["backup","☁","Backup & Transfer"]]}
];
const roles=["Jestina (Administrator)","Denise","Mona","David","Ms. Cindy","Ethan","Tutor / Co-op","GoCoding"];
const blocks=[["12:00–12:30","Family opening, lunch & visual plan","family"],["12:30–1:00","Kameron: Miacademy reading • Jerome: Marilyn learning play","kam"],["1:00–1:30","Kameron: 30-minute math block","kam"],["1:30–2:15","Theme mini-lesson + hands-on exploration","kam"],["2:15–3:00","Writing, practical life & work sample","kam"],["3:00–3:30","Snack, handoff, movement & check-in","family"],["3:30–4:15","Jerome: English, thesis or primary sources","rome"],["4:15–5:00","Jerome: math or financial literacy","rome"],["5:00–6:00","Coding, robotics, Spanish, tutoring or mentor time","enrich"],["6:00–7:00","Karate / movement + dinner rotation","family"],["7:00–8:00","Instructor lesson or family theme project","enrich"],["8:00–9:00","Read, reflect, save work & prepare tomorrow","family"]];
const people=[["Jestina","Lead instruction, planning & assessment","JW"],["Denise","History, geography, finance & media","DG"],["Mona","Art, STEAM & CrunchLabs","MR"],["David","Safety, robotics & practical life","DR"],["Ms. Cindy","Piano & music","MC"],["Ethan","Lighting, filming & editing","ER"],["Tutor / Co-op","Reading, science & collaboration","TC"],["GoCoding","Coding, robotics & mentoring","GO"]];
const resources=[["Miacademy","Core math & language arts","MA"],["Reading.com","Phonics and fluency","RE"],["Tuttle Twins","History, civics & finance","TT"],["GoCoding","Coding and robotics","GO"],["3D Design Studio","Tinkercad, Blender and web-based 3D coding","3D"],["VR Learning Lab","Guided science, history, geography and design field trips","VR"],["MEL Science","Hands-on science labs","MS"],["CrunchLabs","Engineering builds","CL"],["Google Classroom","Assignments and materials","GC"],["Family Book Library","Our complete book inventory","BK"]];
const weekTabs=["Overview","Monday","Tuesday","Wednesday","Thursday","Friday","Family Project","Instructor Desk"];
const weekDays:{[key:string]:{question:string;mission:string;kam:string[];rome:string[];team:string;proof:string;materials:string[]}}={
 Monday:{question:"What helps our family learn well together?",mission:"Meet the new routine, name personal strengths and build a calm starting rhythm.",kam:["Reading.com or Miacademy phonics — 30 minutes","Read a short family/routine story and tell beginning, middle and end","Math: addition/subtraction warm-up and create a 12–3 picture timeline","Write: “I learn best when…” with one illustrated sentence","Practice full name, address and emergency contact"],rome:["Read and annotate a short text on habits and systems","Write a one-page learning autobiography: strengths, needs and ambitions","Math diagnostic or current course baseline — 45 minutes","Create a 3–9 PM executive-function checklist","Lead Marilyn in one planned educational-play activity"],team:"Jestina leads the launch. Denise may post a welcome video or family-history connection. Home/online rotation only follows the full evening plan.",proof:"One goal statement, baseline result and photo of each student’s schedule.",materials:["Visual timer","Markers","Index cards","Miacademy","Reading.com"]},
 Tuesday:{question:"How can time, sound and movement help us stay organized?",mission:"Practice the schedule through music, time math and predictable transitions.",kam:["Phonics/fluency practice — 30 minutes","Math: tell time to the hour/half-hour using today’s schedule","Piano with Ms. Cindy at 1 or 2 PM","Build a LEGO model of the best learning space","Draw and label three tools that help focus"],rome:["Math: elapsed-time problems using the 3–9 PM schedule","Revise learning autobiography for organization and voice","Research one focus strategy and test it for 20 minutes","Coding after 5 PM: design a simple routine-flow screen","Practice transition support with Marilyn"],team:"Ms. Cindy records the piano focus and practice note. GoCoding may connect the routine to a beginner interface or sequence.",proof:"Piano note, LEGO-space photo, elapsed-time work and focus-strategy rating.",materials:["Clock or clock app","LEGO","Piano notebook","Headphones","Coding device"]},
 Wednesday:{question:"How does a strong team communicate?",mission:"Use co-op and tutoring time to practice listening, asking for help and sharing responsibility.",kam:["Reading tutor: fluency, phonics and one comprehension retell","Co-op: complete a partner science or geography task","Math game: take turns, follow rules and explain one answer","Make a “Help Please” and “I Did It” communication card","Choose one co-op success for the portfolio"],rome:["Co-op grade-level discussion or independent theme analysis","English: draft a respectful help-request email","Debate practice: claim, reason and listening response","Coding after 5 PM: collaborative task or instructor-assistant practice","SEL reflection: notice one regulation tool that worked"],team:"Tutor/co-op instructor adds one strength, one observation and one next step. Jestina records service or therapy notes when applicable.",proof:"Tutor/co-op feedback, communication card, email draft and one collaboration reflection.",materials:["Co-op supplies","Reading text","Communication-card template","Portfolio folder"]},
 Thursday:{question:"How can we design a space and system that works for everybody?",mission:"Test the routine, improve the learning area and make the family plan visible.",kam:["Read a short how-to text and identify the steps","Math: measure the desk, shelf or learning-zone area","Create labels for supplies and clean-up stations","Write three rules for caring for the learning space","Independent 10-minute routine practice"],rome:["Measure and sketch a functional learning-space layout","Financial literacy: price three organization items and compare value","English/thesis: write a paragraph defending one design choice","Mona STEAM/art: turn the routine into a clear visual design","Coding/technology after 5 PM or update the digital routine"],team:"Mona guides visual design/STEAM. David may review practical organization and safety. Keep accommodations visible and shame-free.",proof:"Measurements, before/after photo, cost comparison and final layout sketch.",materials:["Tape measure","Labels","Poster paper","Calculator","Art supplies"]},
 Friday:{question:"What did we learn about ourselves, and what will we improve next week?",mission:"Finish, share and celebrate the new system with evidence—not pressure.",kam:["Reading fluency check or short recording","Math mastery check using time and routine problems","Complete personal goal card with picture and one sentence","Present one part of the family routine map","Choose one work sample and name one proud moment"],rome:["Complete weekly English revision and math corrections","Finalize Grade 10 goal card with measurable 30-day target","Present the 3–9 PM plan and explain one accommodation","Complete executive-function self-rating","Choose portfolio evidence and write the next step"],team:"Jestina completes the Friday review. On Mona/David travel Friday, use oral reflection and safe travel learning; upload evidence when settled.",proof:"Two goal cards, final family routine map, weekly review, platform reports and attendance.",materials:["Goal cards","Portfolio folders","Phone/camera","Platform reports","Celebration stickers"]}
};

export default function Home({workspace=false}:{workspace?:boolean}){
 const[tab,setTab]=useState(workspace?"home":"welcome"),[week,setWeek]=useState(1),[weekTab,setWeekTab]=useState("Overview"),[weekDone,setWeekDone]=useState<string[]>([]),[role,setRole]=useState(roles[0]),[done,setDone]=useState<number[]>([]),[notes,setNotes]=useState<{title:string;body:string;by:string}[]>([]),[modal,setModal]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[toast,setToast]=useState(""),[menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("weemsDone")||"[]"));setNotes(JSON.parse(localStorage.getItem("weemsNotes")||"[]"));setWeekDone(JSON.parse(localStorage.getItem("weemsWeek1")||"[]"))}catch{}},[]);
 useEffect(()=>localStorage.setItem("weemsDone",JSON.stringify(done)),[done]);useEffect(()=>localStorage.setItem("weemsNotes",JSON.stringify(notes)),[notes]);useEffect(()=>localStorage.setItem("weemsWeek1",JSON.stringify(weekDone)),[weekDone]);
 const theme=themes[week-1],percent=Math.round(done.length/blocks.length*100),day=(week-1)*5+1;
 const flash=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),1800)};
 const save=()=>{if(!title.trim())return;setNotes([{title,body,by:role},...notes]);setTitle("");setBody("");setModal(false);flash("Lesson note saved!")};
 const go=(next:string)=>{setTab(next);setMenuOpen(false)};
 if(workspace&&tab==="group")return <GroupClassroom onBack={()=>setTab("home")}/>;
 if(workspace&&tab==="parent")return <main className="shell"><aside><button className="logo" onClick={()=>go("home")}><b>WR</b><span>WEEMS-ROSENDUFT<small>Academy</small></span></button><nav><div className="quickNav">{quickNav.map(n=><button className={tab===n[0]?"on":""} onClick={()=>go(n[0])} key={n[0]}><i>{n[1]}</i>{n[2]}</button>)}</div></nav><div className="user"><b>{role[0]}</b><span>{role.split(" (")[0]}<small>Administrator</small></span></div></aside><section className="stage"><header><div><small>WEEMS-ROSENDUFT ACADEMY</small><h1>Parent Command Center</h1></div></header><ParentDashboard week={week} onNavigate={go} isAdmin={role.startsWith("Jestina")}/></section></main>;
 if(!workspace||tab==="welcome")return <main className="publicHome">
  <nav><button className="publicBrand" onClick={()=>setTab("welcome")}><img src="/branding/weems-rosenduft-academy-logo.jpg" alt="Weems-Rosenduft Academy"/><span>WEEMS-ROSENDUFT<small>Academy</small></span></button><div><a href="#approach">Our approach</a><a href="#creator">Creator</a><a href="#pathways">Pathways</a><details className="portalMenu"><summary>Portal Login⌄</summary><div><a href="/student"><b>Student</b><small>Individual learning dashboards</small></a><a href="/instructor"><b>Instructor</b><small>Teaching plans and tools</small></a><a href="/doe"><b>DOE Viewer</b><small>Read-only plans and reports</small></a><a href="/admin"><b>Administrator</b><small>Private records and controls</small></a></div></details><a className="tourNavButton" href="/tour">Explore the Academy</a></div></nav>
  <section className="publicHero"><div><small>FULL-YEAR PERSONALIZED HOMESCHOOLING • BROOKLYN, NEW YORK</small><h1>Different minds deserve learning built <em>with them</em> in mind.</h1><p>Weems-Rosenduft Academy is a complete, individualized school-year program for children on the autism spectrum and with ADHD. Four quarterly learning journeys connect New York learning standards with trusted online programs, hardcopy materials, hands-on projects, real-life skills, career exploration and confidence-building activities. Students see manageable next steps while instructors receive the plans, tools, resources and evidence systems needed to support the entire year.</p><div><a className="heroTourButton" href="/tour">Tour our full-year platform →</a><a href="#journey">See the four-quarter journey</a></div></div><aside className="academyCrest"><img src="/branding/weems-rosenduft-academy-logo.jpg" alt="Weems-Rosenduft Academy — Learning for Life"/></aside></section>
  <section className="publicProof"><article><b>180</b><span>instructional-day framework</span></article><article><b>4</b><span>quarterly learning journeys</span></article><article><b>NY</b><span>standards and IHIP alignment</span></article><article><b>∞</b><span>individualized ways to grow</span></article></section>
  <section className="publicJourney" id="journey"><header><small>ONE FULL YEAR • FOUR MANAGEABLE JOURNEYS</small><h2>A curriculum that grows with both students and instructors.</h2><p>Each quarter builds academic progress, independence and confidence without placing the weight of the entire school year on the screen at once.</p></header><div><article><b>01</b><h3>Foundation & belonging</h3><p>Build routines, learning confidence, communication, safety and strong academic starting points.</p><span>Students: know the rhythm</span><span>Instructors: establish goals and evidence</span></article><article><b>02</b><h3>Practice & application</h3><p>Use books, online programs, labs, art, building and family projects to apply growing skills.</p><span>Students: make learning real</span><span>Instructors: guide, record and adjust</span></article><article><b>03</b><h3>Independence & exploration</h3><p>Deepen required subjects while developing life skills, self-advocacy and meaningful career interests.</p><span>Students: make confident choices</span><span>Instructors: coach increasing independence</span></article><article><b>04</b><h3>Mastery & future launch</h3><p>Complete portfolios, demonstrate growth, serve the community and prepare next-year objectives.</p><span>Students: celebrate evidence of growth</span><span>Instructors: complete reports and plan forward</span></article></div></section>
  <section className="publicSection" id="approach"><header><small>THE ACADEMY MODEL</small><h2>A complete education, connected to real life.</h2><p>Every subject has a purpose, every accommodation protects access, and every project creates evidence of growth.</p></header><div className="modelGrid"><article><span>📚</span><h3>Strong academics</h3><p>Reading, writing, mathematics, science, social studies, arts and physical education mapped to New York learning expectations.</p></article><article><span>🌱</span><h3>Neurodivergent support</h3><p>Visual schedules, predictable steps, movement, sensory breaks, flexible response options and strengths-based goals.</p></article><article><span>🧪</span><h3>Hands-on learning</h3><p>Family books, hardcopy curriculum, MEL Science, KiwiCo, CrunchLabs, art, cooking, building and community experiences.</p></article><article><span>🧭</span><h3>Life beyond school</h3><p>Safety, money, communication, independence, technology, leadership, public service and career exploration woven into school.</p></article></div></section>
  <section className="creatorShowcase" id="creator"><div className="creatorPortrait"><img src="/branding/jestina-weems-rosenduft.jpg" alt="Jestina Weems-Rosenduft, creator of Weems-Rosenduft Academy"/></div><article><small>MEET THE CREATOR</small><h2>Created by Jestina Weems-Rosenduft</h2><p>As a homeschooling mother, creative educator and parent who understands neurodivergence personally, Jestina built the Academy around the truth that education has to fit real family life—not fight against it.</p><p>The platform integrates academics with changing schedules, appointments, travel, family responsibilities, online learning, physical materials, creative work and each learner’s individual needs. It turns a complete school year into clear quarterly journeys that build skills, independence and confidence without overwhelming students or instructors.</p><blockquote>“The goal is not simply to finish assignments. It is to help each child understand how they learn, believe in what they can do, and use those skills in real life.”</blockquote></article></section>
  <section className="publicSection pathways" id="pathways"><header><small>CAREER & INDEPENDENCE</small><h2>School should point toward a future.</h2><p>Learners investigate the work, benefits, risks, training, education and practical steps behind possible careers.</p></header><div>{["Cybersecurity & IT","Fire & emergency services","Construction & CAD","App development","Film & digital media","Entrepreneurship","Technical teaching","Leadership & service"].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</span>)}</div></section>
  <section className="publicCta"><small>A SCHOOL AS INDIVIDUAL AS ITS LEARNERS</small><h2>Welcome to Weems-Rosenduft Academy.</h2><p>Explore a public, read-only presentation of our full-year curriculum, quarterly journeys, instructor tools, resources, labs, practical-life learning, assessments, affirmations and confidence-building model.</p><a className="ctaTourButton" href="/tour">Open the public Academy tour →</a><div><a href="/student">Student portal</a><a href="/instructor">Instructor portal</a><a href="/admin">Private administrator records</a></div></section>
  <footer><b>Weems-Rosenduft Academy</b><span>Personalized at home. Connected to the world.</span><small>Student records and private family information require authenticated access.</small></footer>
 </main>;
 return <main className="shell"><aside className={menuOpen?"menuOpen":""}><button className="logo" onClick={()=>go("home")}><b>WR</b><span>WEEMS-ROSENDUFT<small>Academy</small></span></button><nav><div className="quickNav">{quickNav.map(n=><button className={tab===n[0]?"on":""} onClick={()=>go(n[0])} key={n[0]}><i>{n[1]}</i>{n[2]}</button>)}</div><div className="navGroups">{navGroups.map(g=><details key={g.label} open={g.items.some(x=>x[0]===tab)}><summary><i>{g.icon}</i><span>{g.label}</span><b>⌄</b></summary>{g.items.map(n=><button className={tab===n[0]?"on":""} onClick={()=>go(n[0])} key={n[0]}><i>{n[1]}</i>{n[2]}</button>)}</details>)}</div><button className="mobileMenuToggle" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><i>{menuOpen?"×":"☰"}</i>{menuOpen?"Close":"Menu"}</button></nav><div className="journey">✨<b>90-Day Journey</b><small>Week {week} of 18</small><em><i style={{width:`${week/18*100}%`}}/></em></div><div className="user"><b>{role[0]}</b><span>{role.split(" (")[0]}<small>{role.includes("Administrator")?"Administrator":"Instructor"}</small></span></div></aside><section className="stage"><header><div><small>WEEMS-ROSENDUFT ACADEMY</small><h1>{role.startsWith("Jestina")?"Good afternoon, Jes!":`Welcome, ${role}!`}</h1></div><label>Viewing as<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label></header>
 {tab==="home"&&<div className="page"><section className="hero"><div><span>WEEK {week} • DAYS {day}–{day+4}</span><h2>{theme[0]}</h2><p>One big idea connects every subject. Learn it, build it, talk about it—and make something worth sharing.</p><button onClick={()=>setTab("today")}>Start today’s plan →</button><button className="light" onClick={()=>setTab("plan")}>View all 90 days</button></div><strong>{theme[2]}</strong></section><Title over="TODAY • MONDAY" title="Our learning rhythm"/><div className="rhythm"><Card time="12–3 PM" icon="K" title="Kameron + Mom" text="Reading • Math • Theme activity" color="yellow"/><Card time="3–6 PM" icon="J" title="Jerome + Mom" text="English • Math • Career pathway" color="blue"/><Card time="6–9 PM" icon="♥" title="Move, Make & Reflect" text="Karate • Dinner • Theme project" color="coral"/></div><div className="columns"><section className="panel"><small>WEEKLY MISSION</small><h3>Make it real {theme[2]}</h3><p>Create: <b>{theme[1]}</b></p><div className="meter"><span>Today’s progress</span><b>{percent}%</b></div><em><i style={{width:`${percent}%`}}/></em></section><section className="panel"><div className="panel-title"><div><small>INSTRUCTOR CORNER</small><h3>Quick update</h3></div><button onClick={()=>setModal(true)}>＋ Add note</button></div>{notes.length?<article className="note"><b>{notes[0].title}</b><p>{notes[0].body}</p><small>Added by {notes[0].by}</small></article>:<Empty text="No notes yet. Add the first team update."/>}</section></div></div>}
 {tab==="today"&&<div className="page"><div className="pagehead"><div><small>MONDAY • DAY {day}</small><h2>Today’s 12–9 Plan</h2><p>Tap each circle when a block is complete. Progress saves on this device.</p></div><div className="circle">{percent}%</div></div><div className="alert"><b>🏡 Rotation reminder</b><span>Home/online Monday: follow the full plan. In-person Mona & David weekend: pickup around 3 PM, dinner, then home—<b>no Monday-night school.</b></span></div><div className="tasks">{blocks.map((b,i)=><button className={done.includes(i)?"done":""} key={i} onClick={()=>setDone(done.includes(i)?done.filter(x=>x!==i):[...done,i])}><i>{done.includes(i)?"✓":""}</i><time>{b[0]}</time><em className={b[2]}/><b>{b[1]}</b></button>)}</div></div>}
 {tab==="plan"&&<div className="page"><Title over="18 THEMES • 90 INSTRUCTIONAL DAYS" title="The Whole Adventure" text="Choose any week to open its complete Monday–Friday learning workspace."/><div className="themes">{themes.map((t,i)=><button className={week===i+1?"selected":""} key={i} onClick={()=>{setWeek(i+1);setDone([]);setWeekDone([]);setTab("week1");setWeekTab("Overview")}}><sup>{i+1}</sup><strong>{t[2]}</strong><h3>{t[0]}</h3><p>{t[1]}</p><small>Open Week {i+1} • Days {i*5+1}–{i*5+5} →</small></button>)}</div></div>}
 {tab==="week1"&&<WeekOne week={week} theme={theme} active={weekTab} setActive={setWeekTab} complete={weekDone} setComplete={setWeekDone} notes={notes} addNote={()=>setModal(true)}/>} 
 {tab==="students"&&<div className="page"><Title over="LEARNING PROFILES" title="Meet the Students" text="Strengths first. Clear goals. Progress we can actually see."/><div className="studentgrid"><Student name="Kameron" grade="Grade 3" initial="K" color="yellow" percent="64" strengths="Building • LEGO • Hands-on learning" focus="Reading confidence, phonics, math, independence, safety and practical life" tags={["Miacademy","Reading.com","Robotics","Karate"]}/><Student name="Jerome" grade="Grade 10" initial="J" color="blue" percent="58" strengths="Technology • Helping others • Deep discussion" focus="Thesis writing, math, financial literacy, coding, 3D design, careers and executive function" tags={["Coding","3D Design","Spanish","Debate","Career Pathways"]}/><Student name="Marilyn" grade="Early Learning" initial="M" color="coral" percent="35" strengths="Music • Dance • Stories • Family connection" focus="Language, early math, movement, sensory art, routines and joyful participation" tags={["Music & Dance","Story Time","Early Math","Life Skills"]}/></div><CareerRotation/><section className="panel checkpoints"><small>MARILYN’S PLAN</small><h3>Short, playful learning invitations 🎵</h3><p>Marilyn’s plan uses 10–15 minute adult-guided activities, a gentle weekly rhythm, and learning through movement, music, stories, sensory play and daily routines.</p><a href="/student/marilyn">Open Marilyn’s full learning plan →</a></section><section className="panel checkpoints"><small>ASSESSMENT RHYTHM</small><h3>Evidence, not pressure 📂</h3><p><b>Every Friday:</b> one work sample per child, platform reports, one strength and one next step.</p><p><b>Weeks 6, 12 & 18:</b> portfolio, services, attendance and objectives review.</p></section></div>}
 {tab==="team"&&<div className="page"><div className="pagehead"><Title over="ONE TEAM • MANY GIFTS" title="Instructor Hub" text="See your lane, leave a note, and keep the family updated."/><button className="primary" onClick={()=>setModal(true)}>＋ Add lesson note</button></div><div className="people">{people.map(p=><article key={p[0]}><span>{p[2]}</span><div><h3>{p[0]}</h3><p>{p[1]}</p></div><button onClick={()=>{setRole(p[0]);setModal(true)}}>Add note</button></article>)}</div><h2 className="feedtitle">Team notes</h2><div className="feed">{notes.length?notes.map((n,i)=><article key={i}><span>{n.by[0]}</span><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.by} • saved on this device</small></div></article>):<Empty text="Your team’s lesson updates will appear here."/>}</div></div>}
 {tab==="resources"&&<div className="page"><Title over="OUR LEARNING TOOLBOX" title="Resources" text="Everything instructors need, organized in one cheerful place."/><div className="resources">{resources.map(r=><button key={r[0]} onClick={()=>r[0]==="Family Book Library"?go("library"):r[0]==="VR Learning Lab"?document.getElementById("vr-learning-lab")?.scrollIntoView({behavior:"smooth"}):flash(r[0]==="Google Classroom"?"Classroom connection is ready for the next setup":"Resource selected")}><span>{r[2]}</span><div><h3>{r[0]}</h3><p>{r[1]}</p></div><b>↗</b></button>)}</div><section className="book"><b>📚</b><div><small>FAMILY RESOURCE INVENTORY</small><h3>Books belong in the lessons, too.</h3><p>Search books by subject, learner and curriculum theme, then track reading progress.</p></div><button onClick={()=>go("library")}>Explore library →</button></section><div id="vr-learning-lab"><VrLearningLab/></div></div>}
 {tab==="schoolyear"&&<SchoolYear/>}
 {tab==="library"&&<BookLibrary/>}
 {tab==="inventory"&&<StemInventory/>}
 {tab==="labs"&&<LabCenter/>}
 {tab==="labcalendar"&&<LabCalendar/>}
 {tab==="standards"&&<StandardsTracker/>}
 {tab==="attendance"&&<AttendanceCenter/>}
 {tab==="reminders"&&<ReminderCenter/>}
 {tab==="reports"&&<QuarterlyGenerator/>}
 {tab==="official-records"&&<RecordsCenter/>}
 {tab==="backup"&&<BackupCenter/>}
 </section>{modal&&<div className="backdrop" onMouseDown={()=>setModal(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(false)}>×</button><small>INSTRUCTOR UPDATE</small><h2>Add a lesson note</h2><p>Share what you covered, what went well, and what should happen next.</p><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Kameron’s reading breakthrough" autoFocus/></label><label>Note<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Observations, assignments, links or next steps…"/></label><div><button onClick={()=>setModal(false)}>Cancel</button><button className="primary" onClick={save}>Save note</button></div></section></div>}{toast&&<div className="toast">✓ {toast}</div>}</main>
}
function WeekOne({week,theme,active,setActive,complete,setComplete,notes,addNote}:{week:number;theme:string[];active:string;setActive:(x:string)=>void;complete:string[];setComplete:(x:string[])=>void;notes:{title:string;body:string;by:string}[];addNote:()=>void}){
 if(week===2)return <WeekTwo active={active} setActive={setActive} complete={complete} setComplete={setComplete} notes={notes} addNote={addNote}/>;
 if(week>1)return <ExtendedWeek week={week} theme={theme} active={active} setActive={setActive} complete={complete} setComplete={setComplete} notes={notes} addNote={addNote}/>;
 const toggle=(id:string)=>setComplete(complete.includes(id)?complete.filter(x=>x!==id):[...complete,id]);
 const total=Object.values(weekDays).reduce((n,d)=>n+d.kam.length+d.rome.length,0),pct=Math.round(complete.length/total*100);
 const day=weekDays[active];
 return <div className="page weekpage"><section className="weekhero"><div><small>WEEK 1 • DAYS 1–5</small><h2>Strong Starts & Family Systems</h2><p>We’re building a rhythm that works for the whole family—clear enough to guide us, flexible enough for real life.</p><div className="weekmeter"><em><i style={{width:`${pct}%`}}/></em><b>{pct}% complete</b></div></div><strong>🧭</strong></section><div className="weektabs" role="tablist">{weekTabs.map(t=><button role="tab" aria-selected={active===t} className={active===t?"active":""} onClick={()=>setActive(t)} key={t}>{t}</button>)}</div>
 {active==="Overview"&&<div className="weekcontent"><div className="weeklead"><section><small>ESSENTIAL QUESTION</small><h3>How can we build routines that help every person in our family learn, grow and feel supported?</h3></section><section><small>FRIDAY FINISH LINE</small><h3>Family routine map + one personal goal card for Kameron and Jerome</h3></section></div><div className="weekstats"><article><b>5</b><span>Connected learning days</span></article><article><b>2</b><span>Individual goal cards</span></article><article><b>1</b><span>Family routine map</span></article><article><b>∞</b><span>Room for flexibility</span></article></div><div className="weekoverview"><section className="panel"><small>LEARNING TARGETS</small><h3>By Friday, we can…</h3>{["Follow the opening, transition and closing routines","Name tools and accommodations that support focus","Use time, measurement, reading and writing in a real family system","Ask for help and communicate a next step","Save clear evidence for both student portfolios"].map(x=><p className="tick" key={x}>✓ {x}</p>)}</section><section className="panel"><small>FAMILY PROMISE</small><h3>Structure without shame</h3><p>We will use routines as supports—not punishments. Breaks, therapy, travel, regulation and changing needs are part of the plan.</p><div className="quote">“The schedule serves the family. The family does not serve the schedule.”</div></section></div><h2 className="sectiontitle">The week at a glance</h2><div className="daycards">{Object.entries(weekDays).map(([name,d],i)=><button key={name} onClick={()=>setActive(name)}><span>DAY {i+1}</span><b>{name}</b><p>{d.question}</p><i>Open plan →</i></button>)}</div></div>}
 {day&&<div className="weekcontent"><div className="daybanner"><div><small>{active.toUpperCase()} • DAY {Object.keys(weekDays).indexOf(active)+1}</small><h2>{day.question}</h2><p>{day.mission}</p></div><span>{["🌞","🎵","🤝","📐","🎉"][Object.keys(weekDays).indexOf(active)]}</span></div><div className="learnercols"><AssignmentList name="Kameron" grade="Grade 3 • 12–3 PM Focus" color="yellow" items={day.kam} prefix={`${active}-K`} complete={complete} toggle={toggle}/><AssignmentList name="Jerome" grade="Grade 10 • 3–6 PM Focus" color="blue" items={day.rome} prefix={`${active}-J`} complete={complete} toggle={toggle}/></div><div className="daydetails"><section className="panel"><small>INSTRUCTOR & FAMILY LANE</small><h3>Who does what</h3><p>{day.team}</p></section><section className="panel"><small>EVIDENCE TO SAVE</small><h3>Proof of learning</h3><p>{day.proof}</p></section></div><section className="materials panel"><div><small>READY BASKET</small><h3>Materials</h3></div>{day.materials.map(x=><span key={x}>{x}</span>)}</section><WeeklyMaterialsGuide week={1}/><div className="daynav"><button disabled={active==="Monday"} onClick={()=>setActive(Object.keys(weekDays)[Object.keys(weekDays).indexOf(active)-1])}>← Previous day</button><button disabled={active==="Friday"} onClick={()=>setActive(Object.keys(weekDays)[Object.keys(weekDays).indexOf(active)+1])}>Next day →</button></div></div>}
 {active==="Family Project"&&<div className="weekcontent"><div className="projecthero"><span>🗺️</span><div><small>WEEK 1 CULMINATING PROJECT</small><h2>Our Family Learning Map</h2><p>A living, visual plan for who needs what, when learning happens, how we help one another and what success feels like.</p></div></div><div className="projectsteps">{[["1","Monday","Dream","Each person names strengths, needs and one hope."],["2","Tuesday","Design","Sketch time blocks and the best learning spaces."],["3","Wednesday","Connect","Add help signals, instructor roles and communication rules."],["4","Thursday","Build","Create the full poster or digital map and test the routine."],["5","Friday","Share","Present, revise, sign and place goal cards beside the map."]].map(s=><article key={s[0]}><b>{s[0]}</b><div><small>{s[1]} • {s[2]}</small><p>{s[3]}</p></div></article>)}</div><div className="learnercols"><section className="panel"><small>KAMERON’S GOAL CARD</small><h3>One clear 30-day goal</h3><p><b>Sentence frame:</b> “I am working on ___ . I will practice by ___ . I will know I grew when ___.”</p><p>Include a picture, an adult-support choice and a celebration idea.</p></section><section className="panel"><small>JEROME’S GOAL CARD</small><h3>One measurable 30-day goal</h3><p>Connect the goal to writing, coding, financial literacy, executive function or a career pathway.</p><p>Include the action, frequency, evidence and support person.</p></section></div><section className="panel rubric"><small>QUICK PROJECT CHECK</small><h3>Ready to celebrate when…</h3>{["Both students contributed their own ideas","The 12–3 and 3–9 rhythms are easy to understand","Marilyn’s care and learning play are included","Instructor and support roles are visible","Travel/online rotation and no Monday-night school rule are included","Each student chose one portfolio item"].map((x,i)=><button className={complete.includes(`project-${i}`)?"checked":""} onClick={()=>toggle(`project-${i}`)} key={x}><i>{complete.includes(`project-${i}`)?"✓":""}</i>{x}</button>)}</section></div>}
 {active==="Instructor Desk"&&<div className="weekcontent"><div className="instructortop"><div><small>WEEK 1 TEAM DESK</small><h2>Teach your lane. Leave the bridge.</h2><p>Each instructor records what happened, evidence, and the clearest next step for the next adult.</p></div><button className="primary" onClick={addNote}>＋ Add Week 1 note</button></div><div className="instructorlanes">{[["Jestina","Daily flow, core instruction, assessment and portfolios"],["Denise","Family history, geography, finance or welcome connection"],["Mona","Visual routine map, art and learning-space design"],["David","Safety, organization, practical-life and system check"],["Ms. Cindy","Piano routine, practice cue and music transition"],["Ethan","Photo/video documentation and visual storytelling"],["Tutor / Co-op","Reading data, collaboration and one next step"],["GoCoding","Sequence, digital routine or interface-thinking connection"]].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div><section className="panel"><div className="panel-title"><div><small>WEEK 1 NOTES</small><h3>Shared updates</h3></div><button onClick={addNote}>＋ Add note</button></div>{notes.length?<div className="feed compact">{notes.map((n,i)=><article key={i}><span>{n.by[0]}</span><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.by}</small></div></article>)}</div>:<Empty text="No Week 1 notes yet. Add the first instructor bridge."/>}</section></div>}
 </div>
}
function WeekTwo({active,setActive,complete,setComplete,notes,addNote}:{active:string;setActive:(x:string)=>void;complete:string[];setComplete:(x:string[])=>void;notes:{title:string;body:string;by:string}[];addNote:()=>void}){
 const names=["Monday","Tuesday","Wednesday","Thursday","Friday"], toggle=(id:string)=>setComplete(complete.includes(id)?complete.filter(x=>x!==id):[...complete,id]);
 const days:{[key:string]:{q:string;mission:string;kam:string[];rome:string[];lane:string;proof:string;books:string[]}}={
 Monday:{q:"What makes my story uniquely mine?",mission:"Identify the people, places, interests and experiences that shape identity.",kam:["Dodger mini-lesson: identity means the things that help make you YOU","Read a family-library picture book; identify the character’s name, traits and favorite thing","Practice spelling and saying full name; build the letters with bricks","Create a four-part identity shield: family, favorites, strengths and dreams","Record or dictate: “My name is Kameron, and three things about me are…”"],rome:["Read a short age-appropriate personal narrative and annotate identity details","Create an identity web: family, culture, interests, strengths, needs and goals","Draft a 200-word learning-and-life introduction","Math/data: turn five personal facts into a simple chart or timeline","Emotion check: choose privacy boundaries—what is public, school-only or personal"],lane:"Jestina introduces the project and models a short story. Denise can contribute a family-history memory. Keep student choice and privacy central.",proof:"Identity shield, identity web, name practice and first recorded/drafted introduction.",books:["Go, Dog. Go! or another character-centered picture book","Dictionary/thesaurus","Family photographs (optional)"]},
 Tuesday:{q:"How does voice change the way a story feels?",mission:"Explore tone, volume, pacing, word choice, music and confident communication.",kam:["Read the same two sentences in happy, curious and proud voices","Phonics: practice five story words and tap each sound","Use speech-to-text to answer: “Something I am proud of is…”","Piano/music connection: choose a sound that matches the story mood","Draw a three-panel beginning, middle and end for “A Day With Kameron”"],rome:["Compare tone in two short speeches, interviews or personal narratives","Revise the introduction using precise verbs and sensory detail","Spanish: write and practice three identity sentences—name, interest and goal","Record a 30–60 second voice test; review pacing and clarity","Coding/media: storyboard a simple digital profile screen"],lane:"Ms. Cindy supports mood, tempo and performance confidence. Jerome’s Spanish instructor may review the three identity sentences.",proof:"Kameron’s speech-to-text response and storyboard; Jerome’s revision, Spanish lines and voice test.",books:["Mrs. Wordsmith Storyteller’s Illustrated Dictionary","Webster’s Thesaurus","Piano notebook"]},
 Wednesday:{q:"How do we listen to and honor someone else’s story?",mission:"Practice interviewing, active listening, retelling and respectful questions.",kam:["Mini-lesson: eyes ready, body calm, wait, listen and ask one question","Choose three interview questions for Mom, Jerome, Nana or an instructor","Use tally marks to record three favorite things from interview answers","Retell one answer using first, next and last","Add one family or community detail to the illustrated story"],rome:["Study open and closed interview questions","Write five respectful interview questions about family, work or creativity","Conduct and record a five-minute interview with permission","Create a transcript excerpt or structured notes","Write a 150-word reflection separating the speaker’s words from personal interpretation"],lane:"Tutor/co-op reinforces listening and retelling. Denise is an ideal family-history interview guest; Ethan can model interview framing or sound.",proof:"Question lists, interview notes/recording, tally chart and reflection.",books:["How to Talk with Friends: Social Skills Curriculum","Tuttle Twins history title for oral-history connection","Notebook or recording device"]},
 Thursday:{q:"How can pictures, sound and design strengthen our message?",mission:"Build and revise the visual and audio pieces of each student’s story.",kam:["Choose the strongest drawing and add labels with correct capitalization","Math: order four story cards and number them 1–4","Build a LEGO or block model of one important story setting","Record each story page with read-aloud support; retry only when Kameron chooses","Complete a kind self-check: clear, complete and proud"],rome:["Turn the narrative into a six-panel storyboard or slide outline","Apply media literacy: choose images/music that support rather than distract","Revise thesis, organization, transitions and conclusion","Create a 60–90 second recorded introduction or narrated slide draft","Add captions or a transcript for accessibility"],lane:"Mona guides visual design; Ethan supports composition, lighting, recording and editing. Adults offer choices without taking over student voice.",proof:"Labeled artwork/build, ordered story sequence, revised narrative, storyboard and accessible media draft.",books:["LEGO Minecraft Ideas","The Book of Perfectly Perilous Math for design/problem-solving inspiration","Art and media supplies"]},
 Friday:{q:"How can I share my story with confidence and care?",mission:"Present, celebrate, reflect and choose what belongs in the portfolio.",kam:["Warm-up wiggles and Dodger confidence affirmation","Read, play or show “This Is Me: Kameron” with adult support","Answer one friendly audience question by talking, typing or pointing","Complete a five-word spelling check from the week","Choose a proud page/recording and say what improved"],rome:["Present the identity narrative or recorded introduction","Answer two audience questions using complete evidence-based responses","Complete peer/self rubric: voice, organization, detail, accessibility and privacy","Write next-step feedback and one 30-day communication goal","Save final narrative, media link and reflection to the portfolio"],lane:"Jestina hosts a brief Academy Story Showcase. Instructors may leave one strength and one next step; celebration replaces perfection.",proof:"Two final student stories, spelling sample, presentation rubrics, reflections and portfolio links.",books:["Student-selected favorite book","Rubric and portfolio folders","Celebration certificates"]}
 };
 const day=days[active], pct=Math.round(complete.length/50*100);
 return <div className="page weekpage"><section className="weekhero"><div><small>WEEK 2 • DAYS 6–10</small><h2>Identity, Voice & Our Stories</h2><p>Students explore who they are, practice communicating with confidence, and create stories that honor choice, culture, strengths and privacy.</p><div className="weekmeter"><em><i style={{width:`${pct}%`}}/></em><b>{pct}% complete</b></div></div><strong>🎙️</strong></section><div className="weektabs">{weekTabs.map(t=><button className={active===t?"active":""} onClick={()=>setActive(t)} key={t}>{t}</button>)}</div>
 {active==="Overview"&&<div className="weekcontent"><div className="weeklead"><section><small>ESSENTIAL QUESTION</small><h3>How can we use words, pictures, sound and technology to tell our stories with confidence?</h3></section><section><small>FRIDAY FINISH LINE</small><h3>Kameron: illustrated/recorded “This Is Me” story • Jerome: polished identity narrative and media introduction</h3></section></div><div className="weekstats"><article><b>5</b><span>Story-building days</span></article><article><b>2</b><span>Student voices centered</span></article><article><b>1</b><span>Family interview</span></article><article><b>2</b><span>Portfolio-ready projects</span></article></div><div className="weekoverview"><section className="panel"><small>CONNECTED SUBJECTS</small><h3>One story, many skills</h3>{["Reading, phonics, spelling and vocabulary","Narrative writing, thesis and revision","Sequencing, timelines, tallying and data","Music, art, media, coding and Spanish","Social skills, privacy, confidence and reflection"].map(x=><p className="tick" key={x}>✓ {x}</p>)}</section><section className="panel"><small>ACCESS PROMISE</small><h3>Voice is bigger than handwriting</h3><p>Kameron may speak, point, draw, build or type. Jerome receives clear steps, choice over personal disclosure, captions and sensory breaks.</p><div className="quote">The student owns the story. Adults provide the tools.</div></section></div><h2 className="sectiontitle">The week at a glance</h2><div className="daycards">{names.map((n,i)=><button key={n} onClick={()=>setActive(n)}><span>DAY {i+6}</span><b>{n}</b><p>{days[n].mission}</p><i>Open plan →</i></button>)}</div></div>}
 {day&&<div className="weekcontent"><div className="daybanner"><div><small>{active.toUpperCase()} • DAY {names.indexOf(active)+6}</small><h2>{day.q}</h2><p>{day.mission}</p></div><span>🎙️</span></div><div className="learnercols"><AssignmentList name="Kameron" grade="Grade 3 • 12–3 PM Focus" color="yellow" items={day.kam} prefix={`W2-${active}-K`} complete={complete} toggle={toggle}/><AssignmentList name="Jerome" grade="Grade 10 • 3–6 PM Focus" color="blue" items={day.rome} prefix={`W2-${active}-J`} complete={complete} toggle={toggle}/></div><div className="daydetails"><section className="panel"><small>INSTRUCTOR & FAMILY LANE</small><h3>Who does what</h3><p>{day.lane}</p></section><section className="panel"><small>EVIDENCE TO SAVE</small><h3>Proof of learning</h3><p>{day.proof}</p></section></div><section className="materials panel"><div><small>BOOKS & MATERIALS</small><h3>Pull from our shelves</h3></div>{day.books.map(x=><span key={x}>{x}</span>)}</section><WeeklyMaterialsGuide week={2}/><div className="daynav"><button disabled={active==="Monday"} onClick={()=>setActive(names[names.indexOf(active)-1])}>← Previous day</button><button disabled={active==="Friday"} onClick={()=>setActive(names[names.indexOf(active)+1])}>Next day →</button></div></div>}
 {active==="Family Project"&&<div className="weekcontent"><div className="projecthero"><span>🎬</span><div><small>WEEK 2 FAMILY PROJECT</small><h2>Weems-Rosenduft Academy Story Showcase</h2><p>Share Kameron’s illustrated/recorded “This Is Me” story and Jerome’s identity narrative/media introduction in a short, supportive family premiere.</p></div></div><div className="projectsteps">{[["1","Choose","Students decide what they want to share and what stays private."],["2","Create","Combine words, images, drawings, builds, music or narration."],["3","Caption","Add readable text or a transcript so the story is accessible."],["4","Practice","Use warm-up wiggles, breathing and one low-pressure rehearsal."],["5","Celebrate","Audience gives one strength, one question and one encouraging next step."]].map(s=><article key={s[0]}><b>{s[0]}</b><div><small>{s[1]}</small><p>{s[2]}</p></div></article>)}</div></div>}
 {active==="Instructor Desk"&&<div className="weekcontent"><div className="instructortop"><div><small>WEEK 2 TEAM DESK</small><h2>Protect the voice. Support the storyteller.</h2><p>Post lesson links, interview availability, media notes, accommodations and feedback for the next adult.</p></div><button className="primary" onClick={addNote}>＋ Add Week 2 note</button></div><div className="instructorlanes">{people.map(p=><article key={p[0]}><b>{p[0]}</b><p>{p[1]}</p></article>)}</div><section className="panel"><small>SHARED UPDATES</small><h3>Instructor notes</h3>{notes.length?<div className="feed compact">{notes.map((n,i)=><article key={i}><span>{n.by[0]}</span><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.by}</small></div></article>)}</div>:<Empty text="No Week 2 notes yet."/>}</section></div>}
 </div>
}
function ExtendedWeek({week,theme,active,setActive,complete,setComplete,notes,addNote}:{week:number;theme:string[];active:string;setActive:(x:string)=>void;complete:string[];setComplete:(x:string[])=>void;notes:{title:string;body:string;by:string}[];addNote:()=>void}){
 const names=["Monday","Tuesday","Wednesday","Thursday","Friday"], start=(week-1)*5+1,plan=getWeekPlan(week);
 const support=weekSupport[week];
 const focus=plan.focus;
 const books=["Choose a matching physical book from Books We Own","Use a family-library reference and record the title","Connect the lesson to a book, article or approved video","Use the dictionary, thesaurus or subject workbook","Complete a book recap and recommend the next resource"];
 const toggle=(id:string)=>setComplete(complete.includes(id)?complete.filter(x=>x!==id):[...complete,id]);
 const dayIndex=names.indexOf(active), total=50, pct=Math.round(complete.length/total*100);
 const kam=(i:number)=>[
  `Read-aloud/phonics: ${theme[0]} — 30 minutes with speech or read-to-me support`,
  `${books[i]}; tell the beginning, main idea and one new word`,
  `Visual math mission using dots, blocks, shapes or Hot Wheels connected to ${theme[0]}`,
  `Dodger challenge: build, draw or act out one idea from today’s lesson`,
  plan.kam[i],
  `Answer by typing, talking or drawing; save one Grade 3 work sample`
 ];
 const rome=(i:number)=>[
  `Read and annotate a grade-level source about ${theme[0]}`,
  `${books[i]}; write or dictate a structured source recap`,
  `Math/financial-literacy connection: solve and explain one real-world problem`,
  `Career, coding, Spanish, thesis or debate connection to the weekly theme`,
  plan.rome[i],
  `Complete a regulation check, revise the work and save Grade 10 evidence`
 ];
 return <div className="page weekpage"><section className="weekhero"><div><small>WEEK {week} • DAYS {start}–{start+4}</small><h2>{theme[0]}</h2><p>{focus[0]}. The week ends with: <b>{theme[1]}</b>.</p><div className="weekmeter"><em><i style={{width:`${pct}%`}}/></em><b>{pct}% complete</b></div></div><strong>{theme[2]}</strong></section><div className="weektabs">{weekTabs.map(t=><button className={active===t?"active":""} onClick={()=>setActive(t)} key={t}>{t}</button>)}</div>
 {active==="Overview"&&<div className="weekcontent"><div className="weeklead"><section><small>ESSENTIAL QUESTION</small><h3>How can {theme[0].toLowerCase()} help us understand ourselves, our community and the real world?</h3></section><section><small>FRIDAY FINISH LINE</small><h3>{theme[1]}</h3></section></div><div className="weekstats"><article><b>5</b><span>Connected days</span></article><article><b>10</b><span>Core learning blocks</span></article><article><b>2</b><span>Portfolio samples</span></article><article><b>1</b><span>Family project</span></article></div><div className="weekoverview"><section className="panel"><small>WEEKLY TARGETS</small><h3>Learn it. Use it. Explain it.</h3><p className="tick">✓ Read and discuss sources at each student’s level</p><p className="tick">✓ Apply math, writing and practical-life skills</p><p className="tick">✓ Use a physical book from the family library</p><p className="tick">✓ Create one game-based challenge</p><p className="tick">✓ Save evidence and instructor feedback</p></section><section className="panel"><small>ACCESS & REGULATION</small><h3>Choice creates access</h3><p>Kameron may listen, speak, type, draw, build and use math visuals. Jerome receives clear sections, teen-level choices, sensory breaks and predictable expectations.</p><div className="quote">Short lesson first. Activity second. Reflection last.</div></section></div><h2 className="sectiontitle">Open a day</h2><div className="daycards">{names.map((n,i)=><button key={n} onClick={()=>setActive(n)}><span>DAY {start+i}</span><b>{n}</b><p>{focus[i]}</p><i>Open plan →</i></button>)}</div></div>}
 {dayIndex>=0&&<div className="weekcontent"><div className="daybanner"><div><small>{active.toUpperCase()} • DAY {start+dayIndex}</small><h2>{focus[dayIndex]}</h2><p>Today’s work connects reading, writing, math, books and hands-on learning to {theme[0]}.</p></div><span>{theme[2]}</span></div><div className="learnercols"><AssignmentList name="Kameron" grade="Grade 3 • 12–3 PM Focus" color="yellow" items={kam(dayIndex)} prefix={`W${week}-${active}-K`} complete={complete} toggle={toggle}/><AssignmentList name="Jerome" grade="Grade 10 • 3–6 PM Focus" color="blue" items={rome(dayIndex)} prefix={`W${week}-${active}-J`} complete={complete} toggle={toggle}/></div><div className="daydetails"><section className="panel"><small>5–9 PM ENRICHMENT</small><h3>Flexible family lane</h3><p>Coding, Spanish, piano, karate, tutoring, co-op or an instructor lesson can become today’s theme connection. Dinner, movement and regulation remain part of the plan.</p></section><section className="panel"><small>EVIDENCE TO SAVE</small><h3>One clear learning trail</h3><p>Save the title of the book/resource used, one student response, the game or activity result, and one instructor observation or next step.</p></section></div><div className="teacherGuide"><section><small>INSTRUCTOR PREP</small><h3>Before today begins</h3>{support.prep.map(x=><p key={x}>□ {x}</p>)}</section><section><small>ANSWER & MASTERY GUIDE</small><h3>What a strong response shows</h3>{support.check.map(x=><p key={x}>✓ {x}</p>)}</section></div><section className="materials panel"><div><small>READY BASKET</small><h3>Books & materials</h3></div>{support.materials.map(x=><span key={x}>{x}</span>)}</section><section className="lessonLinks"><div><small>TRUSTED LESSON RESOURCES</small><h3>Open from the lesson</h3></div>{support.resources.map(x=><a key={x.label} href={x.url} target={x.url.startsWith("http")?"_blank":undefined} rel="noreferrer"><b>{x.label} ↗</b><span>{x.note}</span></a>)}<a href="/resources/drive"><b>Academy Drive Resources ↗</b><span>Instructor files, templates and classroom materials</span></a></section><WeeklyMaterialsGuide week={week}/><div className="daynav"><button disabled={dayIndex===0} onClick={()=>setActive(names[dayIndex-1])}>← Previous day</button><button disabled={dayIndex===4} onClick={()=>setActive(names[dayIndex+1])}>Next day →</button></div></div>}
 {active==="Family Project"&&<div className="weekcontent"><div className="projecthero"><span>{theme[2]}</span><div><small>WEEK {week} CULMINATING PROJECT</small><h2>{theme[1]}</h2><p>Both students contribute at their own level, use at least one family-library resource, and share a finished product or demonstration.</p></div></div><div className="projectsteps">{names.map((n,i)=><article key={n}><b>{i+1}</b><div><small>{n} • {focus[i]}</small><p>{["Choose the question, books and roles.","Research, read and collect evidence.","Practice skills and build the first version.","Test, revise and prepare the presentation.","Share, celebrate and save portfolio evidence."][i]}</p></div></article>)}</div></div>}
 {active==="Instructor Desk"&&<div className="weekcontent"><div className="instructortop"><div><small>WEEK {week} TEAM DESK</small><h2>{theme[0]}</h2><p>Post resources, assignments, accommodations, observations and the bridge to the next instructor.</p></div><button className="primary" onClick={addNote}>＋ Add Week {week} note</button></div><div className="instructorlanes">{people.map(p=><article key={p[0]}><b>{p[0]}</b><p>{p[1]}</p></article>)}</div><section className="panel"><small>SHARED UPDATES</small><h3>Instructor notes</h3>{notes.length?<div className="feed compact">{notes.map((n,i)=><article key={i}><span>{n.by[0]}</span><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.by}</small></div></article>)}</div>:<Empty text={`No Week ${week} notes yet.`}/>}</section></div>}
 </div>
}
function AssignmentList({name,grade,color,items,prefix,complete,toggle}:{name:string;grade:string;color:string;items:string[];prefix:string;complete:string[];toggle:(x:string)=>void}){return <section className="assignment"><header className={color}><span>{name[0]}</span><div><small>{grade}</small><h3>{name}</h3></div><b>{items.filter((_,i)=>complete.includes(`${prefix}-${i}`)).length}/{items.length}</b></header>{items.map((x,i)=><button className={complete.includes(`${prefix}-${i}`)?"checked":""} onClick={()=>toggle(`${prefix}-${i}`)} key={x}><i>{complete.includes(`${prefix}-${i}`)?"✓":""}</i><span>{x}</span></button>)}</section>}
function Title({over,title,text}:{over:string;title:string;text?:string}){return <div className="title"><small>{over}</small><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Card({time,icon,title,text,color}:{time:string;icon:string;title:string;text:string;color:string}){return <article className="card"><time>{time}</time><span className={color}>{icon}</span><div><small>FOCUS WINDOW</small><h3>{title}</h3><p>{text}</p></div></article>}
function Empty({text}:{text:string}){return <div className="empty"><b>📝</b><p>{text}</p></div>}
function Student({name,grade,initial,color,percent,strengths,focus,tags}:{name:string;grade:string;initial:string;color:string;percent:string;strengths:string;focus:string;tags:string[]}){
 const[photo,setPhoto]=useState("");
 useEffect(()=>{setPhoto(localStorage.getItem(`student-photo-${name}`)||"")},[name]);
 const choosePhoto=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{const value=String(reader.result||"");setPhoto(value);localStorage.setItem(`student-photo-${name}`,value)};reader.readAsDataURL(file)};
 return <article className="student"><header className={color}><span className={photo?"hasPhoto":""}>{photo?<img src={photo} alt={`${name} profile`}/>:initial}</span><div><small>{grade}</small><h2>{name}</h2><label className="photoPicker">{photo?"Change private photo":"Add private photo"}<input type="file" accept="image/*" onChange={e=>choosePhoto(e.target.files?.[0])}/></label></div><b>{percent}% term progress</b></header><section><small>SUPERPOWERS</small><p>{strengths}</p><small>CURRENT FOCUS</small><p>{focus}</p><div>{tags.map(t=><i key={t}>{t}</i>)}</div><em><i style={{width:`${percent}%`}}/></em><small className="photoPrivacy">Photo stays on this device and is not shown on the public homepage.</small></section></article>
}
