"use client";

import {useEffect,useMemo,useState} from "react";

type Subject={name:string;grade:string;hours:string;progress:string};
type Draft={student:string;quarter:string;year:string;subjects:Subject[];strengths:string;goals:string;services:string;attendance:string;status:string;updated:string};
type Course={name:string;year:string;credit:string;grade:string;status:string;notes:string};
type Compliance={id:string;item:string;student:string;due:string;status:string;notes:string};
const subjectNames={Kameron:["English Language Arts","Mathematics","Science","Social Studies","Spanish","Technology / Robotics","Fine Arts / Music","Physical Education / Health"],Jerome:["English Language Arts","Mathematics","Science","Social Studies","Spanish","Coding / Technology","Financial Literacy / Careers","Fine Arts / Music","Physical Education / Health"]};
const courseSeed:Course[]=[{name:"English 10",year:"2026–27",credit:"1.0",grade:"IP",status:"In progress",notes:"Literature, thesis writing, research and communication"},{name:"Mathematics",year:"2026–27",credit:"1.0",grade:"IP",status:"In progress",notes:"Individualized high-school mathematics"},{name:"Science with Laboratory",year:"2026–27",credit:"1.0",grade:"IP",status:"In progress",notes:"MEL Science, co-op and standards-connected labs"},{name:"Global History / Civics",year:"2026–27",credit:"1.0",grade:"IP",status:"In progress",notes:"Tuttle Twins, primary sources, geography and civics"},{name:"Spanish",year:"2026–27",credit:"1.0",grade:"IP",status:"In progress",notes:"Online tutoring, speaking, listening, reading and writing"},{name:"Technology & Career Development",year:"2026–27",credit:"1.0",grade:"IP",status:"In progress",notes:"Coding, app development, cyber safety and career exploration"},{name:"Physical Education / Health",year:"2026–27",credit:"0.5",grade:"IP",status:"In progress",notes:"Karate, wellness, safety and practical health"},{name:"Fine Arts / Media",year:"2026–27",credit:"0.5",grade:"IP",status:"In progress",notes:"Piano, film, editing, design and visual arts"}];
const complianceSeed:Compliance[]=[{id:"loi",item:"Letter of Intent",student:"Both",due:"District annual requirement",status:"Filed",notes:"2026–27 submitted"},{id:"ihip-k",item:"Kameron IHIP",student:"Kameron",due:"District deadline",status:"Filed",notes:"Keep accepted copy and amendments"},{id:"ihip-j",item:"Jerome IHIP",student:"Jerome",due:"District deadline",status:"Filed",notes:"Keep accepted copy and amendments"},{id:"q1",item:"First quarterly report",student:"Both",due:"Per IHIP schedule",status:"Not started",notes:"Confirm dates listed on each IHIP"},{id:"q2",item:"Second quarterly report",student:"Both",due:"Per IHIP schedule",status:"Not started",notes:"Confirm dates listed on each IHIP"},{id:"q3",item:"Third quarterly report",student:"Both",due:"Per IHIP schedule",status:"Not started",notes:"Confirm dates listed on each IHIP"},{id:"q4",item:"Fourth quarterly report",student:"Both",due:"Per IHIP schedule",status:"Not started",notes:"Confirm dates listed on each IHIP"},{id:"annual",item:"Annual assessment / narrative",student:"Both",due:"End of school year",status:"Not started",notes:"Select permitted assessment method for each student"},{id:"services",item:"IEP and service records",student:"Both",due:"Ongoing",status:"In progress",notes:"Save meeting notices, provider notes and progress records"},{id:"attendance",item:"Attendance and instructional hours",student:"Both",due:"Ongoing",status:"In progress",notes:"Review monthly and before each quarterly report"}];
const blankSubjects=(student:string):Subject[]=>(subjectNames[student as keyof typeof subjectNames]||subjectNames.Kameron).map(name=>({name,grade:"Progressing",hours:"",progress:""}));

export function RecordsCenter(){
 const[view,setView]=useState("Report Cards"),[student,setStudent]=useState("Kameron"),[quarter,setQuarter]=useState("Quarter 1"),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[courses,setCourses]=useState<Course[]>(courseSeed),[checks,setChecks]=useState<Compliance[]>(complianceSeed),[message,setMessage]=useState("");
 const key=`${student}-${quarter}`;
 useEffect(()=>{try{setDrafts(JSON.parse(localStorage.getItem("academy-report-card-drafts")||"{}"));setCourses(JSON.parse(localStorage.getItem("academy-transcript-courses")||JSON.stringify(courseSeed)));setChecks(JSON.parse(localStorage.getItem("academy-compliance-checklist")||JSON.stringify(complianceSeed)))}catch{}},[]);
 const attendance=useMemo(()=>{try{const all=JSON.parse(localStorage.getItem("weems-attendance-hours")||"[]");return Array.isArray(all)?all.filter((x:{student?:string})=>x.student===student).reduce((n:number,x:{hours?:number})=>n+Number(x.hours||0),0):0}catch{return 0}},[student,drafts]);
 const current=drafts[key]||{student,quarter,year:"2026–2027",subjects:blankSubjects(student),strengths:"",goals:"",services:"Flexible pacing, visual directions, movement or sensory breaks, speech-to-text, read-aloud support and multiple ways to demonstrate learning were available according to student need.",attendance:`${attendance.toFixed(1)} documented hours currently available on this device.`,status:"Draft",updated:""};
 const persistDraft=(next:Draft)=>{const all={...drafts,[key]:{...next,updated:new Date().toISOString()}};setDrafts(all);localStorage.setItem("academy-report-card-drafts",JSON.stringify(all))};
 const patch=(part:Partial<Draft>)=>persistDraft({...current,...part});
 const subjectPatch=(i:number,part:Partial<Subject>)=>patch({subjects:current.subjects.map((s,n)=>n===i?{...s,...part}:s)});
 const newStudent=(name:string)=>{setStudent(name);setMessage("")};
 const saveCourses=(next:Course[])=>{setCourses(next);localStorage.setItem("academy-transcript-courses",JSON.stringify(next))};
 const saveChecks=(next:Compliance[])=>{setChecks(next);localStorage.setItem("academy-compliance-checklist",JSON.stringify(next))};
 const complete=current.subjects.filter(x=>x.progress.trim()).length;
 return <div className="page recordsPage">
  <section className="recordsHero"><div><small>ACADEMY RECORDKEEPING</small><h2>Reports, Transcript & Compliance</h2><p>Bring progress, instructional hours, credits and required records into one reviewable school-year file.</p></div><strong>WR</strong></section>
  <div className="recordsTabs" role="tablist">{["Report Cards","Jerome Transcript","Compliance Checklist"].map(x=><button role="tab" aria-selected={view===x} className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x}</button>)}</div>
  {view==="Report Cards"&&<><div className="recordsControls"><label>Student<select value={student} onChange={e=>newStudent(e.target.value)}><option>Kameron</option><option>Jerome</option></select></label><label>Reporting period<select value={quarter} onChange={e=>setQuarter(e.target.value)}>{[1,2,3,4].map(x=><option key={x}>Quarter {x}</option>)}</select></label><button onClick={()=>window.print()}>Print / Save PDF</button></div><section className="reportSheet"><header><div><small>WEEMS-ROSENDUFT ACADEMY</small><h2>{student} • {student==="Kameron"?"Grade 3":"Grade 10"}</h2><p>{quarter} Report Card • School Year {current.year}</p></div><span className={`recordStatus ${current.status.toLowerCase()}`}>{current.status}</span></header><div className="reportMeta"><label>Report status<select value={current.status} onChange={e=>patch({status:e.target.value})}><option>Draft</option><option>Ready for review</option><option>Finalized</option></select></label><label>Attendance / instructional-time summary<textarea value={current.attendance} onChange={e=>patch({attendance:e.target.value})}/></label></div><div className="subjectReport"><div className="subjectHead"><b>Subject</b><b>Evaluation</b><b>Hours</b><b>Progress and evidence</b></div>{current.subjects.map((s,i)=><div className="subjectRow" key={s.name}><b>{s.name}</b><select value={s.grade} onChange={e=>subjectPatch(i,{grade:e.target.value})}>{["Exceeds expectations","Meets expectations","Progressing","Needs continued support","Incomplete","A","B","C","D","P","IP"].map(x=><option key={x}>{x}</option>)}</select><input value={s.hours} onChange={e=>subjectPatch(i,{hours:e.target.value})} placeholder="hrs"/><textarea value={s.progress} onChange={e=>subjectPatch(i,{progress:e.target.value})} placeholder="Skills, assignments, assessments, labs or work samples…"/></div>)}</div><div className="narrativeGrid"><label>Strengths and growth<textarea value={current.strengths} onChange={e=>patch({strengths:e.target.value})} placeholder="What improved? What made the student proud?"/></label><label>Next-quarter objectives<textarea value={current.goals} onChange={e=>patch({goals:e.target.value})} placeholder="Specific, measurable goals for the next quarter…"/></label><label className="wide">Services, accommodations and instructional supports<textarea value={current.services} onChange={e=>patch({services:e.target.value})}/></label></div><footer><div><b>Parent/Administrator</b><span>Jestina Weems-Rosenduft</span></div><div><b>Draft readiness</b><span>{complete}/{current.subjects.length} subject narratives entered</span></div><div><b>Last saved</b><span>{current.updated?new Date(current.updated).toLocaleString():"Not saved yet"}</span></div></footer></section></>}
  {view==="Jerome Transcript"&&<><div className="recordNotice"><b>Working transcript</b><span>Credits remain editable until the homeschool administrator verifies completed coursework, attendance, assessments and final grades.</span><button onClick={()=>window.print()}>Print transcript</button></div><section className="transcriptSheet"><header><div><small>WEEMS-ROSENDUFT ACADEMY</small><h2>Jerome Weems-Rosenduft</h2><p>High School Transcript • Grade 10 • 2026–2027</p></div><strong>Unofficial Working Copy</strong></header><div className="courseTable"><div><b>Course</b><b>Year</b><b>Credit</b><b>Grade</b><b>Status</b><b>Notes</b></div>{courses.map((c,i)=><div key={`${c.name}-${i}`}><input value={c.name} onChange={e=>saveCourses(courses.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/><input value={c.year} onChange={e=>saveCourses(courses.map((x,n)=>n===i?{...x,year:e.target.value}:x))}/><input value={c.credit} onChange={e=>saveCourses(courses.map((x,n)=>n===i?{...x,credit:e.target.value}:x))}/><input value={c.grade} onChange={e=>saveCourses(courses.map((x,n)=>n===i?{...x,grade:e.target.value}:x))}/><select value={c.status} onChange={e=>saveCourses(courses.map((x,n)=>n===i?{...x,status:e.target.value}:x))}><option>Planned</option><option>In progress</option><option>Completed</option></select><textarea value={c.notes} onChange={e=>saveCourses(courses.map((x,n)=>n===i?{...x,notes:e.target.value}:x))}/></div>)}</div><button className="addCourse" onClick={()=>saveCourses([...courses,{name:"New course",year:"2026–27",credit:"0.5",grade:"IP",status:"Planned",notes:""}])}>＋ Add course</button><div className="transcriptTotals"><p><span>Credits planned</span><b>{courses.reduce((n,c)=>n+Number(c.credit||0),0).toFixed(1)}</b></p><p><span>Credits completed</span><b>{courses.filter(c=>c.status==="Completed").reduce((n,c)=>n+Number(c.credit||0),0).toFixed(1)}</b></p><p><span>GPA</span><b>Calculate after final grades</b></p></div><footer><p>Administrator signature: ______________________________</p><p>Date: __________________</p></footer></section></>}
  {view==="Compliance Checklist"&&<><div className="complianceSummary"><article><b>{checks.filter(x=>x.status==="Filed"||x.status==="Completed").length}</b><span>filed or completed</span></article><article><b>{checks.filter(x=>x.status==="In progress").length}</b><span>in progress</span></article><article><b>{checks.filter(x=>x.status==="Not started").length}</b><span>not started</span></article><article><b>{checks.length}</b><span>records tracked</span></article></div><div className="recordNotice"><b>Compliance safeguard</b><span>Use the dates stated by your district and each student’s accepted IHIP. This checklist organizes your records but does not replace official district instructions.</span><button onClick={()=>window.print()}>Print checklist</button></div><div className="complianceList">{checks.map((c,i)=><article key={c.id}><span className={c.status.replaceAll(" ","-").toLowerCase()}>{c.status==="Filed"||c.status==="Completed"?"✓":"○"}</span><div><small>{c.student}</small><h3>{c.item}</h3><label>Timing<input value={c.due} onChange={e=>saveChecks(checks.map((x,n)=>n===i?{...x,due:e.target.value}:x))}/></label><label>Record note<textarea value={c.notes} onChange={e=>saveChecks(checks.map((x,n)=>n===i?{...x,notes:e.target.value}:x))}/></label></div><select value={c.status} onChange={e=>saveChecks(checks.map((x,n)=>n===i?{...x,status:e.target.value}:x))}><option>Not started</option><option>In progress</option><option>Ready for review</option><option>Filed</option><option>Completed</option></select></article>)}</div></>}
  {message&&<div className="recordsMessage">{message}</div>}
 </div>
}
