"use client";
import {useEffect,useMemo,useState} from "react";

type Quarter={name:string;start:string;end:string;report:string;focus:string};
const defaults:Quarter[]=[
 {name:"Quarter 1",start:"2026-09-08",end:"2026-11-06",report:"2026-11-13",focus:"Foundations, routines and baseline growth"},
 {name:"Quarter 2",start:"2026-11-09",end:"2027-01-29",report:"2027-02-05",focus:"Application, confidence and first-semester evidence"},
 {name:"Quarter 3",start:"2027-02-01",end:"2027-04-09",report:"2027-04-16",focus:"Deepen skills, independence and real-world application"},
 {name:"Quarter 4",start:"2027-04-12",end:"2027-06-25",report:"2027-06-30",focus:"Mastery, portfolio, annual evaluation and next-year launch"}
];
const themes=["Strong Starts & Family Systems","Identity, Voice & Our Stories","Maps, Community & Belonging","Safety, Preparedness & First Response","Living Things & Ecosystems","Forces, Motion & Building","Money, Choices & Financial Literacy","Media, Film & Digital Storytelling","Civics, Government & Our Rights","Healthy Bodies, Minds & Emotions","Food, Culture & Kitchen Science","Weather, Climate & Earth Systems","Black History, Justice & Changemakers","Technology, Coding & Cyber Safety","Careers, Trades & Public Service","Entrepreneurship & Creative Independence","Leadership, Service & Community Impact","Showcase, Reflection & Next-Quarter Launch"];
const fmt=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Set date";
const addWeekdays=(start:string,count:number)=>{const d=new Date(`${start}T12:00:00`);let added=0;while(added<count){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)added++}return d.toISOString().slice(0,10)};

export function SchoolYear(){
 const[quarters,setQuarters]=useState(defaults),[selected,setSelected]=useState(0),[message,setMessage]=useState("");
 useEffect(()=>{try{const saved=localStorage.getItem("wr-ihip-calendar");if(saved)setQuarters(JSON.parse(saved))}catch{}},[]);
 const save=(next=quarters)=>{setQuarters(next);localStorage.setItem("wr-ihip-calendar",JSON.stringify(next));setMessage("✓ IHIP calendar saved on this device")};
 const change=(index:number,field:keyof Quarter,value:string)=>{const next=quarters.map((q,i)=>i===index?{...q,[field]:value}:q);setQuarters(next);setMessage("")};
 const weeks=useMemo(()=>Array.from({length:9},(_,i)=>{const absolute=selected*9+i,base=themes[absolute%18],phase=absolute<18?"Build":"Deepen & apply";return{week:absolute+1,start:addWeekdays(quarters[selected].start,i*5),end:addWeekdays(quarters[selected].start,i*5+4),theme:base,phase}}),[quarters,selected]);
 return <div className="page schoolYear"><div className="yearHero"><div><small>2026–27 • COMPLETE ACADEMY PROGRAM</small><h2>Four quarters. One connected school year.</h2><p>The student view stays focused on what comes next. This full-year view protects the larger IHIP plan: 180 instructional days, four quarterly reports, ongoing objectives and an annual evaluation.</p></div><strong>180<small>instructional days</small></strong></div>
  <div className="yearStats"><article><b>4</b><span>IHIP quarters</span></article><article><b>45</b><span>instructional days each</span></article><article><b>900</b><span>Kameron annual hours</span></article><article><b>990</b><span>Jerome annual hours</span></article></div>
  <section className="ihipNotice"><b>Use the dates on the accepted IHIP</b><p>The starting dates below are editable planning defaults. Replace them with the exact reporting periods and submission dates filed for each child, then save.</p></section>
  <div className="quarterTabs">{quarters.map((q,i)=><button className={selected===i?"active":""} onClick={()=>setSelected(i)} key={q.name}><small>CYCLE {i+1}</small><b>{q.name}</b><span>Days {i*45+1}–{i*45+45}</span></button>)}</div>
  <section className="quarterEditor"><header><div><small>IHIP REPORTING PERIOD</small><h3>{quarters[selected].name}</h3><p>{quarters[selected].focus}</p></div><span>45 school days • Weeks {selected*9+1}–{selected*9+9}</span></header><div><label>Instruction begins<input type="date" value={quarters[selected].start} onChange={e=>change(selected,"start",e.target.value)}/></label><label>Period ends<input type="date" value={quarters[selected].end} onChange={e=>change(selected,"end",e.target.value)}/></label><label>Quarterly report due<input type="date" value={quarters[selected].report} onChange={e=>change(selected,"report",e.target.value)}/></label><label>Quarter focus<input value={quarters[selected].focus} onChange={e=>change(selected,"focus",e.target.value)}/></label></div><button onClick={()=>save()}>Save IHIP dates</button>{message&&<p className="yearMessage">{message}</p>}</section>
  <div className="yearProgress"><div><small>FULL-YEAR GENERATOR</small><h3>{quarters[selected].name} calendar</h3><p>{fmt(quarters[selected].start)}–{fmt(quarters[selected].end)} • Report due {fmt(quarters[selected].report)}</p></div><b>{selected*45+1}–{selected*45+45}<small>of 180 days</small></b></div>
  <div className="generatedWeeks">{weeks.map(w=><article key={w.week}><header><span>WEEK {w.week}</span><b>{fmt(w.start)}–{fmt(w.end)}</b></header><h3>{w.theme}</h3><p>{w.phase}: reading, writing, mathematics, required subjects, hands-on work, life skills and portfolio evidence.</p><footer><span>5 instructional days</span><span>Friday evidence check</span></footer></article>)}</div>
  <section className="cycleFlow"><article><b>1</b><h3>Teach the current week</h3><p>Students see only the manageable lessons and schedule in front of them.</p></article><article><b>2</b><h3>Save evidence and hours</h3><p>Attendance, work samples, assessments, labs and instructor observations build the record.</p></article><article><b>3</b><h3>Generate the quarter</h3><p>The report generator uses the matching dates and saved evidence for each child.</p></article><article><b>4</b><h3>Continue automatically</h3><p>The next quarter opens with new objectives while the prior quarter remains available.</p></article></section>
  <section className="complianceFooter"><b>Important calendar note</b><p>Weekday dates are generated as a planning sequence. Mark holidays, travel, illness and flexible learning accurately in Attendance & Hours. The accepted IHIP and actual instruction records remain the official source.</p></section>
 </div>
}
