"use client";
import {useEffect,useState} from "react";
import "./vr-learning-lab.css";

const trips=[
 {icon:"🗺️",theme:"Maps & Geography",experience:"Explore a city, landmark, landform or world region in 360°.",kameron:"Find three physical or human features and draw a simple map with a compass rose.",jerome:"Compare the virtual location with a political or physical map; record scale, access, culture and one reliable fact to verify.",evidence:"Labeled map + three-sentence field note"},
 {icon:"🌊",theme:"Ecosystems & Ocean Science",experience:"Enter a forest, wetland, reef, ocean or other habitat.",kameron:"Name living/nonliving parts and build a three-link food chain.",jerome:"Identify producers, consumers, limiting factors and one human impact; write a claim-evidence-reasoning response.",evidence:"Food chain + ecosystem CER"},
 {icon:"🌎",theme:"Earth, Weather & Space",experience:"Observe Earth systems, weather, the Moon, planets or a virtual space mission.",kameron:"Describe one pattern, draw what was observed and ask one science question.",jerome:"Explain the scale or system shown, distinguish model from evidence and verify two facts after removing the headset.",evidence:"Observation sketch + verified fact check"},
 {icon:"🏛️",theme:"History & Museums",experience:"Visit a museum gallery, historic place, monument or reconstructed environment.",kameron:"Choose one object and tell who used it, what it did and what it teaches us.",jerome:"Analyze one artifact or place as a source: creator, context, perspective, limits and a second source needed.",evidence:"Artifact card + source analysis"},
 {icon:"✊🏽",theme:"Black History & Civil Rights",experience:"Explore an age-appropriate museum, memorial or historic location connected to Black life and the struggle for justice.",kameron:"Name the person, problem, action and result.",jerome:"Connect the location to a primary source, compare strategies and explain whose voice may be missing.",evidence:"Timeline card + cited reflection"},
 {icon:"⚙️",theme:"Engineering & Design",experience:"Inspect machines, structures, spatial models or a safe virtual build environment.",kameron:"Name shapes and forces, then build a matching model with blocks or a kit.",jerome:"Sketch the system, label forces or components and propose one measurable improvement.",evidence:"Physical model + design sketch"},
 {icon:"🫀",theme:"Life Science & the Human Body",experience:"Explore an age-appropriate model of a cell, organ, body system, plant or animal.",kameron:"Name three parts and match each part to one job.",jerome:"Trace how parts interact, explain limits of the model and connect the lesson to a lab or credible source.",evidence:"Part/function chart + systems explanation"},
 {icon:"🎨",theme:"Art, Architecture & Storytelling",experience:"Walk through an art space or create in a three-dimensional studio.",kameron:"Choose colors, shapes and a feeling; make a drawing inspired by the visit.",jerome:"Analyze design choices, spatial composition and audience; create a 3D scene or narrated critique.",evidence:"Artwork + artist statement"}
];

export function VrLearningLab(){
 const[done,setDone]=useState<string[]>([]);
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("academy-vr-trips")||"[]"))}catch{}},[]);
 const toggle=(theme:string)=>setDone(current=>{const next=current.includes(theme)?current.filter(x=>x!==theme):[...current,theme];localStorage.setItem("academy-vr-trips",JSON.stringify(next));return next});
 return <section className="vrLab"><header><div><small>GUIDED IMMERSIVE FIELD TRIPS</small><h2>VR Learning Lab</h2><p>Use the boys’ headsets for one curriculum-connected experience—not open-ended game time. Every trip begins with a question and ends off-screen with evidence.</p></div><span>🥽</span></header><div className="vrRoutine"><article><b>1</b><h3>Preview</h3><p>Adult checks the experience, comfort setting, space and lesson question.</p></article><article><b>2</b><h3>Explore</h3><p>10–20 minutes seated or inside a clear boundary, with an adult nearby.</p></article><article><b>3</b><h3>Explain</h3><p>Remove headset, hydrate, describe observations and verify important facts.</p></article><article><b>4</b><h3>Create</h3><p>Complete the map, model, timeline, paragraph, drawing or portfolio note.</p></article></div><div className="vrTrips">{trips.map(x=><article key={x.theme}><span>{x.icon}</span><small>CURRICULUM FIELD TRIP</small><h3>{x.theme}</h3><p>{x.experience}</p><div><b>Kameron</b>{x.kameron}</div><div><b>Jerome</b>{x.jerome}</div><em><b>Save:</b> {x.evidence}</em><button className={done.includes(x.theme)?"done":""} onClick={()=>toggle(x.theme)}>{done.includes(x.theme)?"✓ Trip + evidence complete":"Mark trip complete"}</button></article>)}</div><aside><b>VR safety and access:</b> Follow the headset manufacturer’s age guidance and account rules. Use guardian supervision, a clear play area, wrist straps and short sessions. Stop immediately for dizziness, headache, eye strain, nausea, disorientation or distress. A video, book, map or physical model is always an equal non-VR option.</aside></section>
}
