"use client";
import {useEffect,useState} from "react";
import "./vr-learning-lab.css";

const trips=[
 {icon:"🗺️",theme:"Maps & Geography",experience:"Explore a city, landmark, landform or world region in 360°.",kameron:"Find three physical or human features and draw a simple map with a compass rose.",jerome:"Compare the virtual location with a political or physical map; record scale, access, culture and one reliable fact to verify.",evidence:"Labeled map + three-sentence field note"},
 {icon:"🌊",theme:"Ecosystems & Ocean Science",experience:"Enter a forest, wetland, reef, ocean or other habitat.",kameron:"Name living/nonliving parts and build a three-link food chain.",jerome:"Identify producers, consumers, limiting factors and one human impact; write a claim-evidence-reasoning response.",evidence:"Food chain + ecosystem CER"},
 {icon:"🌎",theme:"Earth, Weather & Space",experience:"Observe Earth systems, weather, the Moon, planets or a virtual space mission.",kameron:"Describe one pattern, draw what was observed and ask one science question.",jerome:"Explain the scale or system shown, distinguish model from evidence and verify two facts after removing the headset.",evidence:"Observation sketch + verified fact check"},
 {icon:"🏛️",theme:"History & Museums",experience:"Visit a museum gallery, historic place, monument or reconstructed environment.",kameron:"Choose one object and tell who used it, what it did and what it teaches us.",jerome:"Analyze one artifact or place as a source: creator, context, perspective, limits and a second source needed.",evidence:"Artifact card + source analysis"},
 {icon:"✊🏽",theme:"Black History & Civil Rights",experience:"Explore an age-appropriate museum, memorial or historic location connected to Black life and the struggle for justice.",kameron:"Name the person, problem, action and result.",jerome:"Connect the location to a primary source, compare strategies and explain whose voice may be missing.",evidence:"Timeline card + cited reflection"},
 {icon:"⚙️",theme:"Engineering & Design",experience:"Inspect machines, structures, spatial models or a safe virtual build environment.",kameron:"Name shapes and forces, then build a matching model with blocks or a kit.",jerome:"Sketch the system, label forces or components and propose one measurable improvement.",evidence:"Physical model + design sketch"},
 {icon:"🫀",theme:"Life Science & the Human Body",experience:"Explore an age-appropriate model of a cell, organ, body system, plant or animal.",kameron:"Name three parts and match each part to one job.",jerome:"Trace how parts interact, explain limits of the model and connect the lesson to a lab or credible source.",evidence:"Part/function chart + systems explanation"},
 {icon:"🎨",theme:"Art, Architecture & Storytelling",experience:"Walk through an art space or create in a three-dimensional studio.",kameron:"Choose colors, shapes and a feeling; make a drawing inspired by the visit.",jerome:"Analyze design choices, spatial composition and audience; create a 3D scene or narrated critique.",evidence:"Artwork + artist statement"}
];

const programs=[
 {name:"VictoryXR / VXRLabs",fit:"Best broad curriculum trial",learners:"Kameron + Jerome, with instructor-selected modules",weeks:"Weeks 5, 10, 12 and 15",use:"Interactive science, CTE and field-trip labs. Choose one experience that matches the lesson, then require an off-headset diagram, CER or career reflection.",platform:"Most major VR headsets; Windows/Mac alternative",cost:"Subscription / free trial available",url:"https://www.victoryxr.com/",verdict:"START HERE"},
 {name:"Prisms",fit:"Best focused fit for Jerome",learners:"Jerome; secondary math and science",weeks:"Weeks 6, 7, 12, 14 and 16",use:"Use one problem-based module for fractions, ratios, functions, geometry, biology or chemistry. Transfer the 3D experience to a paper graph, equation or lab explanation.",platform:"School solution; confirm current home/headset access",cost:"Pricing and access can change",url:"https://www.prismsvr.com/what-is-prisms",verdict:"HIGH PRIORITY"},
 {name:"BRINK Traveler",fit:"Best geography and Earth-science fieldwork",learners:"Kameron + Jerome at different response levels",weeks:"Weeks 3 and 12",use:"Visit one scanned landform. Kameron labels visible features; Jerome identifies processes, scale and human impact, then verifies facts with a map or Earth-science source.",platform:"Check the official store for the family headset",cost:"Paid app",url:"https://www.brinkxr.com/",verdict:"STRONG FIT"},
 {name:"Open Brush",fit:"Best free creative option",learners:"Kameron + Jerome",weeks:"Weeks 2, 8, 13, 16 and 18",use:"Create a 3D character, habitat, timeline, set design or product advertisement. Save a screenshot and short artist statement; do not grade artistic polish.",platform:"Meta Quest, SteamVR and other supported systems",cost:"Free / open source",url:"https://openbrush.app/",verdict:"INSTALL"},
 {name:"Gravity Sketch",fit:"Best career and product-design option",learners:"Jerome primarily",weeks:"Weeks 6, 14, 15 and 16",use:"Sketch a tool, lamp, vehicle or product in 3D; label constraints, measure proportions and revise from feedback. Pair with a physical kit so VR supports making.",platform:"Standalone and tethered headsets; screen companion",cost:"Free individual access; education program has requirements",url:"https://gravitysketch.com/",verdict:"JEROME"},
 {name:"Anne Frank House VR",fit:"Powerful but emotionally sensitive history source",learners:"Jerome only after adult preview",weeks:"Week 13 extension",use:"Use as a reconstructed historic environment, not entertainment. Prepare Holocaust context first; afterward distinguish reconstruction, testimony and primary evidence. Never use it as a substitute for Black-history study.",platform:"Meta Quest, Steam and PICO",cost:"Free",url:"https://www.annefrank.org/en/about-us/what-we-do/publications/anne-frank-house-virtual-reality/",verdict:"PREVIEW FIRST"},
 {name:"ClassVR / Eduverse",fit:"Best managed school ecosystem—only if buying dedicated school service",learners:"Both; instructor-controlled",weeks:"All themes as selected",use:"Curriculum-aligned scenes, teacher notes, playlists and monitoring make this useful if the Academy wants managed devices and a content library. It is likely more system than a two-headset homeschool needs today.",platform:"ClassVR hardware; browser access is also advertised",cost:"Quote / subscription",url:"https://www.classvr.com/us/",verdict:"FUTURE OPTION"}
];

export function VrLearningLab(){
 const[done,setDone]=useState<string[]>([]);
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("academy-vr-trips")||"[]"))}catch{}},[]);
 const toggle=(theme:string)=>setDone(current=>{const next=current.includes(theme)?current.filter(x=>x!==theme):[...current,theme];localStorage.setItem("academy-vr-trips",JSON.stringify(next));return next});
 return <section className="vrLab"><header><div><small>GUIDED IMMERSIVE FIELD TRIPS</small><h2>VR Learning Lab</h2><p>Use the boys’ headsets for one curriculum-connected experience—not open-ended game time. Every trip begins with a question and ends off-screen with evidence.</p></div><span>🥽</span></header><div className="vrRoutine"><article><b>1</b><h3>Preview</h3><p>Adult checks the experience, comfort setting, space, privacy and lesson question.</p></article><article><b>2</b><h3>Explore</h3><p>10–20 minutes seated or inside a clear boundary, with an adult nearby.</p></article><article><b>3</b><h3>Explain</h3><p>Remove headset, hydrate, describe observations and verify important facts.</p></article><article><b>4</b><h3>Create</h3><p>Complete the map, model, timeline, paragraph, drawing or portfolio note.</p></article></div><div className="vrProgramsHead"><small>PROGRAM DEEP DIVE • OFFICIAL LINKS</small><h3>What to use, who it fits and where it belongs</h3><p>Start with the owned headset’s store listing and confirm current compatibility, price, age rating, account requirements and privacy terms before installing.</p></div><div className="vrPrograms">{programs.map(x=><article key={x.name}><span>{x.verdict}</span><h3>{x.name}</h3><b>{x.fit}</b><dl><div><dt>Student fit</dt><dd>{x.learners}</dd></div><div><dt>Curriculum</dt><dd>{x.weeks}</dd></div><div><dt>Instructor use</dt><dd>{x.use}</dd></div><div><dt>Access</dt><dd>{x.platform} • {x.cost}</dd></div></dl><a href={x.url} target="_blank" rel="noreferrer">Open official program site ↗</a></article>)}</div><div className="vrTrips">{trips.map(x=><article key={x.theme}><span>{x.icon}</span><small>CURRICULUM FIELD TRIP</small><h3>{x.theme}</h3><p>{x.experience}</p><div><b>Kameron</b>{x.kameron}</div><div><b>Jerome</b>{x.jerome}</div><em><b>Save:</b> {x.evidence}</em><button className={done.includes(x.theme)?"done":""} onClick={()=>toggle(x.theme)}>{done.includes(x.theme)?"✓ Trip + evidence complete":"Mark trip complete"}</button></article>)}</div><aside><b>VR safety and access:</b> Follow the headset manufacturer’s age guidance and account rules. Use guardian supervision, a clear play area, wrist straps and short sessions. Disable public voice/chat and avoid collecting personal information unless the family intentionally approves it. Stop immediately for dizziness, headache, eye strain, nausea, disorientation or distress. A video, book, map or physical model is always an equal non-VR option.</aside></section>
}
