import {SignIn} from "@clerk/nextjs";
import {getChatGPTUser} from "../chatgpt-auth";
import {isAdministrator,isApprovedDOEViewer} from "../access-control";

export const dynamic="force-dynamic";

export default async function DOEPortal(){
 const user=await getChatGPTUser();
 if(!user)return <main className="doeDenied"><section><img className="workspaceGateLogo" src="/branding/weems-rosenduft-academy-logo.jpg" alt="Academy logo"/><small>NYC PUBLIC SCHOOLS • AUTHORIZED VIEWERS</small><h1>DOE Records Portal</h1><p>Sign in using the approved NYC Public Schools email address associated with the students’ homeschool or special-education records.</p><SignIn routing="hash"/><a href="/">← Return to the Academy homepage</a></section></main>;
 if(!isApprovedDOEViewer(user.email)&&!isAdministrator(user.email))return <main className="doeDenied"><section><b>🔒</b><h1>Access not authorized</h1><p><strong>{user.email}</strong> is not on the approved DOE viewer list. Contact the Academy administrator to request access.</p><a href="/">← Return to the Academy homepage</a></section></main>;
 return <main className="doePortal"><nav><a href="/">← Academy homepage</a><span>Signed in: {user.email}</span></nav><header><small>SECURE • READ-ONLY DOE ACCESS</small><h1>Student Plans & Reporting Portal</h1><p>Review the instructional framework, student schedules, progress-tracking structure, report-card evidence and quarterly reporting plan. DOE viewers cannot edit, delete, approve or publish Academy records.</p></header><section className="doeGrid"><article><span>📅</span><h2>Plans & schedules</h2><p>The Academy uses a 180-day instructional framework divided into four manageable quarterly journeys.</p><ul><li>Kameron: focused instruction beginning around noon</li><li>Jerome: focused academics beginning around 3 PM</li><li>Online, hardcopy, hands-on and community instruction</li><li>Flexible accommodations for IEP and regulation needs</li></ul></article><article><span>📈</span><h2>Progress trackers</h2><p>Academic skills, attendance, instructional hours, accommodations, projects and portfolio evidence are tracked throughout each quarter.</p><ul><li>Standards and objective progress</li><li>Attendance and instructional hours</li><li>Assignments and instructor observations</li><li>Approved portfolio evidence</li></ul></article><article><span>📝</span><h2>Report cards</h2><p>Report cards summarize documented performance, participation, strengths, accommodations and next instructional steps.</p><ul><li>Subject progress and assessment evidence</li><li>Instructor observations</li><li>Practical-life and career-building growth</li><li>Parent review before submission</li></ul></article><article><span>📚</span><h2>Quarterly reports</h2><p>Each quarterly report connects completed instruction to the student’s IHIP objectives and annual program.</p><ul><li>Quarter dates and curriculum covered</li><li>Hours and attendance evidence</li><li>Progress toward individualized objectives</li><li>Next-quarter adjustments</li></ul></article><article className="doeNotice"><strong>Privacy boundary</strong><p>This role is intentionally read-only. Student documents will appear here only after the administrator has reviewed and approved them for DOE access. Private family notes, account settings, drafts and administrative controls remain restricted.</p></article></section></main>;
}
