import {doeLogin,doeLogout,getDOESession} from "../doe-auth";
export const dynamic="force-dynamic";
export default async function DOEPortal({searchParams}:{searchParams:Promise<{error?:string}>}){
 const params=await searchParams;const email=await getDOESession();
 if(!email)return <main className="doeDenied"><section><img className="workspaceGateLogo" src="/branding/weems-rosenduft-academy-logo.jpg" alt="Academy logo"/><small>NYC PUBLIC SCHOOLS • AUTHORIZED VIEWERS</small><h1>DOE Records Portal</h1><p>Enter an approved NYC Public Schools email address and the private DOE portal PIN to open the read-only reporting portal.</p>{params.error==="email"&&<p className="studentLoginError">This email is not on the approved DOE access list.</p>}{params.error==="pin"&&<p className="studentLoginError">That DOE portal PIN was not correct.</p>}{params.error==="setup"&&<p className="studentLoginError">The DOE access PIN still needs to be added in Vercel.</p>}<form action={doeLogin} className="doeLoginForm"><label>Approved DOE email<input name="email" type="email" autoComplete="email" required placeholder="name@schools.nyc.gov"/></label><label>Private DOE portal PIN<input name="pin" type="password" inputMode="numeric" autoComplete="current-password" required placeholder="Enter DOE PIN"/></label><button type="submit">Open DOE portal →</button></form><a href="/">← Return to the Academy homepage</a></section></main>;
 return <main className="doePortal"><nav><a href="/">← Academy homepage</a><span>Approved viewer: {email}</span><form action={doeLogout}><button type="submit">Sign out</button></form></nav><header><small>SECURE • READ-ONLY DOE ACCESS</small><h1>Daily Plans, Quarterly Learning & Reports</h1><p>Review the students’ instructional structure, quarterly curriculum, reporting system and approved learning resources. DOE viewers cannot edit, delete, approve or publish Academy records.</p><div className="doeQuickLinks"><a href="#daily-plan">Today’s plan</a><a href="#ninety-day">90-day plan</a><a href="#quarterly-reports">Quarterly reports</a><a href="#libraries">Libraries</a></div></header><section className="doeGrid">
 <article id="daily-plan"><span>📅</span><h2>Today’s learning plan</h2><p>The home-learning day begins around noon and adapts around services, travel and student regulation needs.</p><ul><li>Kameron: focused one-to-one instruction beginning around noon</li><li>Jerome: focused Grade 10 academics beginning around 3 PM</li><li>Online, hardcopy, hands-on and real-life instruction</li><li>Flexible breaks and IEP-informed accommodations</li></ul></article>
 <article id="ninety-day"><span>🧭</span><h2>Current 90-day journey</h2><p>Each quarter is one manageable part of the full 180-day school year.</p><ul><li>Weekly objectives connected to each student’s IHIP</li><li>Core academics, therapies, enrichment and career skills</li><li>Assessments, attendance and portfolio evidence</li><li>Quarter-end review before the next journey begins</li></ul><a href="/tour">View the public curriculum structure →</a></article>
 <article id="quarterly-reports"><span>📝</span><h2>Quarterly reports</h2><p>Reports connect completed instruction and documented evidence to the students’ annual plans.</p><ul><li>Quarter dates, curriculum and instructional hours</li><li>Progress toward individualized objectives</li><li>Accommodations, strengths and instructor observations</li><li>Parent-reviewed next-quarter adjustments</li></ul></article>
 <article id="libraries"><span>📚</span><h2>Libraries & approved resources</h2><p>Review the resource system used across online, printed, hands-on and community learning.</p><ul><li>Video and book libraries</li><li>Science, art, KiwiCo, MEL Science and CrunchLabs inventory</li><li>Instructor templates and learning supports</li><li>Career, financial-literacy and real-life resources</li></ul><a href="/resources/drive">Open the Academy resource library →</a></article>
 <article><span>📈</span><h2>Progress trackers</h2><p>Academic skills, attendance, hours, accommodations, labs, projects and portfolio evidence are tracked throughout each quarter.</p><ul><li>Standards and objective progress</li><li>Assignments and assessments</li><li>Instructor observations</li><li>Approved portfolio evidence</li></ul></article>
 <article className="doeNotice"><strong>Privacy boundary</strong><p>This role is intentionally read-only. Student documents appear only after the administrator approves them for DOE access. Private family notes, draft records, account settings and administrative controls remain restricted.</p></article>
 </section></main>;
}
